### ISSUE TITLE
ATAQC module failed

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#107]
The pipeline errors out during the ATAQC module with the following error:
```
Traceback (most recent call last):
  File "/home/nicolerg/.conda/envs/encode-atac-seq-pipeline/bin/encode_ataqc.py", line 12, in <module>
    from run_ataqc import *
  File "/home/nicolerg/.conda/envs/encode-atac-seq-pipeline/bin/run_ataqc.py", line 12, in <module>
    import pysam
ModuleNotFoundError: No module named 'pysam'
```
I entered the following commands to try to resolve this:
```
module load miniconda/3
source activate encode-atac-seq-pipeline
conda install pysam==0.8.4 -c defaults -y
```
and got the following output:
```
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.2
  latest version: 4.6.8

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.
```

**OS/Platform and dependencies**
- OS or Platform: SCG4
- Cromwell/dxWDL version: cromwell-34.jar
- Conda version: 4.6.2

**Comment by nicolerg** [comment]
Outside of the pipeline, the following commands do not result in an error:
```
module load miniconda/3
source activate encode-atac-seq-pipeline
which python # ~/.conda/envs/encode-atac-seq-pipeline/bin/python
cd /home/nicolerg/.conda/envs/encode-atac-seq-pipeline/bin/
python 
>>> from run_ataqc import *
>>> import pysam
```

**Comment by leepc12** [comment]
Can you try `pysam.__file__` on python cmd prompt?
```
-bash-4.2$ source activate encode-atac-seq-pipeline
(encode-atac-seq-pipeline) -bash-4.2$ which python
~/.conda/envs/encode-atac-seq-pipeline/bin/python
(encode-atac-seq-pipeline) -bash-4.2$ python
Python 2.7.15 | packaged by conda-forge | (default, Nov 28 2018, 18:42:13)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> pysam.__file__
'/home/leepc12/.conda/envs/encode-atac-seq-pipeline/lib/python2.7/site-packages/pysam/__init__.pyc'
>>>
(encode-atac-seq-pipeline) -bash-4.2$ source deactivate
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
-bash-4.2$ python
Python 3.7.1 (default, Dec 14 2018, 19:28:38)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pysam'
>>>
```

**Comment by nicolerg** [comment]
```
[nicolerg@smsx10srw-srcf-d15-38 ~]$ module load miniconda/3
[nicolerg@smsx10srw-srcf-d15-38 ~]$ source activate encode-atac-seq-pipeline
(encode-atac-seq-pipeline) [nicolerg@smsx10srw-srcf-d15-38 ~]$ which python
~/.conda/envs/encode-atac-seq-pipeline/bin/python
(encode-atac-seq-pipeline) [nicolerg@smsx10srw-srcf-d15-38 ~]$ python
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pysam
>>> pysam.__file__
'/home/nicolerg/.conda/envs/encode-atac-seq-pipeline/lib/python2.7/site-packages/pysam/__init__.pyc'
>>>
(encode-atac-seq-pipeline) [nicolerg@smsx10srw-srcf-d15-38 ~]$ source deactivate
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
[nicolerg@smsx10srw-srcf-d15-38 ~]$ python
Python 3.7.1 (default, Dec 14 2018, 19:28:38)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pysam'
```

**Comment by leepc12** [comment]
It's weird. I added `module load miniconda/3` to `examples/scg/ENCSR356KRQ_subsampled_scg_conda.sh` (right above `source activate encode-atac-seq-pipeline') and tested it with our lab's paid account on SCG and it worked fine. Did you use this shell script?
```
sbatch --account akundaje examples/scg/ENCSR356KRQ_subsampled_scg_conda.sh
```
I used SCG's shared (module) conda.
```
-bash-4.2$ module load miniconda/3
-bash-4.2$ which conda
/scg/apps/software/miniconda/3/condabin/conda
-bash-4.2$ conda env list
# conda environments:
#
encode-atac-seq-pipeline     /home/leepc12/.conda/envs/encode-atac-seq-pipeline
encode-atac-seq-pipeline-python3     /home/leepc12/.conda/envs/encode-atac-seq-pipeline-python3
base                  *  /scg/apps/software/miniconda/3
```

**Comment by nicolerg** [comment]
I was also able to run the test sample (`examples/scg/ENCSR356KRQ_subsampled_scg_conda.sh`) without a problem using `module load miniconda/3`. I should've mentioned I got this error when I was running the pipeline on a full-sized input sample. 

I do make a couple of small adjustments to the shell script to be able to specify a custom `outdir` since it is generally inconvenient for all pipeline outputs to be written to `atac-seq-pipeline/cromwell-executions/atac`. Could this be causing the problem? Does the ATAQC module specifically look for files in `pwd`? I attached the script I call with `sbatch` as well as the input JSON file
[run_encode_single.sh.zip](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3005701/run_encode_single.sh.zip)
[SCS11_S1.json.zip](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3005702/SCS11_S1.json.zip)

.

**Comment by leepc12** [comment]
No, that doesn't cause any problem. You can change an output directory by simply `cd`ing to it. We are also working on an output organizer wrapper script so that you can specify output directory as a parameter for the wrapper.

It's still weird. If you have successfully run a pipeline for the test sample, that means `pysam` is correctly imported in ATAQC. I suspect that your resumed workflow (with `INPUT=resume.*.json` went without Conda env activated for some reasons.

Please use this shell script to resume it. I added `set -o` and `python -c "import pysam"`. This will make your shell script fail if Conda environment is not loaded correctly.

```
#!/bin/bash
set -o

# do not touch these settings
#  number of tasks and nodes are fixed at 1
#SBATCH -n 1
#SBATCH --ntasks-per-node=1

# job name for pipeline
#  this name will appear when you monitor jobs with "squeue -u $USER"
#SBATCH --job-name=SCS11_S1_human_test

# walltime for your job
#  give long time enough to finish your pipeline
#  <12 hr: small/test samples
#  >24 hr: large samples
#SBATCH --time=24:00:00

# total amount of memory
#  depends on the size of your FASTQs
#  but should be <= NUM_CONCURRENT_TASK x 20GB for big samples
#  or <= NUM_CONCURRENT_TASK x 10GB for small samples
#  do not request too much memory
#  cluster will not accept your job
#SBATCH --mem=20G

# max number of cpus for each pipeline
#  should be <= NUM_CONCURRENT_TASK x "atac.bowtie2_cpu" in input JSON file
#  since bowtie2 is a bottlenecking task in the pipeline
#  "atac.bowtie2_cpu" is a number of cpus per replicate
#SBATCH --cpus-per-task=4

# email notification for job status
#SBATCH --mail-type=END,FAIL

# load java module if it exists
module load java
module load miniconda/3
source activate encode-atac-seq-pipeline

# check pysam
python -c "import pysam"

NUM_CONCURRENT_TASK=1

srcdir=/labs/smontgom/shared/atac_encode_pl/atac-seq-pipeline
outdir=/labs/smontgom/nicolerg/AFRICAN_OMICS

indir=/labs/smontgom/nicolerg/AFRICAN_OMICS/180319_NS500418_0808_AHLLWFBGX5/JSON
#INPUT=${indir}/SCS11_S1.json
INPUT=/labs/smontgom/nicolerg/AFRICAN_OMICS/180319_NS500418_0808_AHLLWFBGX5/JSON/resume.346be4fe-a76e-474e-9838-651b79fe6d35.json

PIPELINE_METADATA=${indir}/SCS11_S1_metadata_v2.json 
# If this pipeline fails, then use this metadata JSON file to resume a failed pipeline from where it left 
# See details in /utils/resumer/README.md

cd ${outdir}

java -jar -Dconfig.file=${srcdir}/backends/backend.conf \
/home/nicolerg/cromwell-34.jar run ${srcdir}/atac.wdl -i ${INPUT} -m ${PIPELINE_METADATA}
```

**Comment by nicolerg** [comment]
The script ran without error if I changed `set -o` to `set -e` and moved it below all of the `#SBATCH` options. However, the rest of the pipeline up until ATAQC wouldn't have run without a hitch if the Conda environment wasn't loaded from the beginning, so that doesn't explain the original error. The following `sbatch` script ran without error for a large ATAC-seq sample. I'll reopen this issue if it happens again. 
```
#!/bin/bash

#SBATCH --account=smontgom
#SBATCH --time=48:00:00
#SBATCH --job-name=HYLJ2BGX2_AFATACPoolK_17s002606-1-1_De-Gorter_lane1AF96
#SBATCH --mail-type=END,FAIL
#SBATCH --error=/labs/smontgom/nicolerg/AFRICAN_OMICS/slurm-%j-%x.out
#SBATCH --output=/labs/smontgom/nicolerg/AFRICAN_OMICS/slurm-%j-%x.out

# max number of cpus for each pipeline
#  should be <= NUM_CONCURRENT_TASK x "atac.bowtie2_cpu" in input JSON file
#  since bowtie2 is a bottlenecking task in the pipeline
#SBATCH --cpus-per-task=8

# total amount of memory
#  depends on the size of your FASTQs
#  but should be <= NUM_CONCURRENT_TASK x 20GB for big samples
#  or <= NUM_CONCURRENT_TASK x 10GB for small samples
#SBATCH --mem=40G

# do not touch these settings
#  number of tasks and nodes are fixed at 1
#SBATCH --ntasks=1
#SBATCH --nodes=1

set -e

module load java
module load miniconda/3
source activate encode-atac-seq-pipeline

# check pysam
python -c "import pysam"

NUM_CONCURRENT_TASK=2

srcdir=/labs/smontgom/shared/atac_encode_pl/atac-seq-pipeline
INPUT=/labs/smontgom/nicolerg/AFRICAN_OMICS/JSON/HYLJ2BGX2_AFATACPoolK_17s002606-1-1_De-Gorter_lane1AF96.json
PIPELINE_METADATA=/labs/smontgom/nicolerg/AFRICAN_OMICS/HYLJ2BGX2_AFATACPoolK_17s002606-1-1_De-Gorter_lane1AF96_metadata.json

cd /labs/smontgom/nicolerg/AFRICAN_OMICS

java -jar -Dconfig.file=${srcdir}/backends/backend.conf \
/home/nicolerg/cromwell-34.jar run ${srcdir}/atac.wdl -i ${INPUT} -m ${PIPELINE_METADATA}
```
