### ISSUE TITLE
Error when I start pipeline from tagAlign files

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#109]
I am trying to call peaks with the newest version of the pipeline using intermediate files from the old version of the pipeline (before outputs were written to `cromwell-execution`). I re-ran one sample with the new version of the pipeline from the FASTQs and found that `atac_dnase_pipelines/out/align/rep1/${SAMPLE}.trim.PE2SE.nodup.tn5.tagAlign.gz` was identical to `cromwell-executions/atac/c3709d48-68ce-40b9-b772-9713354f8c12/call-bam2ta/shard-0/execution/${SAMPLE}/trim.merged.nodup.tn5.tagAlign.gz` according to `zcmp`. Therefore, I am trying to generate new overlap peak sets from this step. I get the following error when I try to run the pipeline starting with old (but identical) tagAlign files:

```
[2019-03-27 14:41:59,76] [[38;5;1merror[0m] WorkflowManagerActor Workflow d9599b62-95cf-4f6c-9e1b-d82055087211 failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
No coercion defined from '"/labs/smontgom/mdegorte/Africa/ATAC/atac_dnase_pipelines/out/align/rep1/HY53YBGX2_AFATACPoolE_17s002600-1-1_De-Gorter_lane1AF9_1_sequence.txt.trim.PE2SE.nodup.tn5.tagAlign.gz"' of type 'spray.json.JsString' to 'Array[File?]'.
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:200)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:170)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:165)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:670)
	at akka.actor.FSM.processEvent$(FSM.scala:667)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:123)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:806)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:788)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:123)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:664)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:658)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:123)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
This is the `sbatch` script I am using:
```
#!/bin/bash

#SBATCH --account=smontgom
#SBATCH --time=48:00:00
#SBATCH --job-name=lane1AF9
#SBATCH --mail-type=END,FAIL
#SBATCH --error=/labs/smontgom/nicolerg/AFRICAN_OMICS/slurm_out/slurm-%j-%x.out
#SBATCH --output=/labs/smontgom/nicolerg/AFRICAN_OMICS/slurm_out/slurm-%j-%x.out

# max number of cpus for each pipeline
#  should be <= NUM_CONCURRENT_TASK x "atac.bowtie2_cpu" in input JSON file
#  since bowtie2 is a bottlenecking task in the pipeline
#SBATCH --cpus-per-task=8

# total amount of memory
#  depends on the size of your FASTQs
#  but should be <= NUM_CONCURRENT_TASK x 20GB for big samples
#  or <= NUM_CONCURRENT_TASK x 10GB for small samples
#SBATCH --mem=40G

# do not touch these settings
#  number of tasks and nodes are fixed at 1
#SBATCH --ntasks=1
#SBATCH --nodes=1

set -e 

module load java
module load miniconda/3
source activate encode-atac-seq-pipeline

# check pysam
python -c "import pysam"

NUM_CONCURRENT_TASK=2

srcdir=/labs/smontgom/shared/atac_encode_pl/atac-seq-pipeline
INPUT=/labs/smontgom/nicolerg/AFRICAN_OMICS/JSON/lane1AF9.json
PIPELINE_METADATA=/labs/smontgom/nicolerg/AFRICAN_OMICS/lane1AF9_metadata.json 

cd /labs/smontgom/nicolerg/AFRICAN_OMICS

java -jar -Dconfig.file=${srcdir}/backends/backend.conf \
/home/nicolerg/cromwell-34.jar run ${srcdir}/atac.wdl -i ${INPUT} -m ${PIPELINE_METADATA}
```
This is the JSON file:
```
{
    "atac.title" : "lane1AF9",
    "atac.description" : "African ATAC",

    "atac.pipeline_type" : "atac",

    "atac.genome_tsv" : "/reference/ENCODE/pipeline_genome_data/hg38_scg.tsv",
    "atac.paired_end" : true,

    "atac.tas" : "/labs/smontgom/mdegorte/Africa/ATAC/atac_dnase_pipelines/out/align/rep1/HY53YBGX2_AFATACPoolE_17s002600-1-1_De-Gorter_lane1AF9_1_sequence.txt.trim.PE2SE.nodup.tn5.tagAlign.gz",

    "atac.enable_count_signal_track" : false,
    "atac.enable_xcor" : false,
    "atac.enable_idr" : false,
    "atac.disable_ataqc" : true,

    "atac.cap_num_peak" : 300000,
    "atac.pval_thresh" : 0.01,
    "atac.smooth_win" : 150,

    "atac.filter_cpu" : 4,
    "atac.filter_mem_mb" : 20000,
    "atac.filter_time_hr" : 24,

    "atac.spr_mem_mb" : 20000,

    "atac.macs2_mem_mb" : 20000,
    "atac.macs2_time_hr" : 24
}
```

**OS/Platform and dependencies**
- OS or Platform: Stanford SCG cluster
- Cromwell/dxWDL version: cromwell-34.jar`
- Conda version: conda 4.6.2

**Comment by leepc12** [comment]
Your `tas` must be an array in your input JSON.
```
    "atac.tas" : ["/labs/smontgom/mdegorte/Africa/ATAC/atac_dnase_pipelines/out/align/rep1/HY53YBGX2_AFATACPoolE_17s002600-1-1_De-Gorter_lane1AF9_1_sequence.txt.trim.PE2SE.nodup.tn5.tagAlign.gz"],
```

**Comment by nicolerg** [comment]
Thank you! I didn't realize single files still had to be in an array.
