### ISSUE TITLE
SCG test sample fails with v1.1.7.1

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#111]
The SCG test sample with the newest pipeline release (v1.1.7.1) fails before the pipeline starts. The error log is below. It looks like there is an error parsing the wdl. I never had this issue with previous versions. Do I need to update cromwell, or is this another issue? Thanks. 

**OS/Platform and dependencies**
- OS or Platform: SCG
- Cromwell/dxWDL version: `cromwell-34.jar`
- Conda version: `conda 4.6.11`

```
[2019-04-10 11:42:26,87] [info] Running with database db.url = jdbc:hsqldb:mem:64705b4e-17ce-4417-98a1-eb6a877190b9;shutdown=false;hsqldb.tx=mvcc
[2019-04-10 11:42:39,35] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2019-04-10 11:42:39,36] [info] [RenameWorkflowOptionsInMetadata] 100%
[2019-04-10 11:42:39,57] [info] Running with database db.url = jdbc:hsqldb:mem:1784b84c-4364-4684-846a-ea83abde9121;shutdown=false;hsqldb.tx=mvcc
[2019-04-10 11:42:39,99] [warn] This actor factory is deprecated. Please use cromwell.backend.google.pipelines.v1alpha2.PipelinesApiLifecycleActorFactory for PAPI v1 or cromwell.backend.google.pipelines.v2alpha1.PipelinesApiLifecycleActorFactory for PAPI v2
[2019-04-10 11:42:40,02] [warn] Couldn't find a suitable DSN, defaulting to a Noop one.
[2019-04-10 11:42:40,03] [info] Using noop to send events.
[2019-04-10 11:42:40,33] [info] Slf4jLogger started
[2019-04-10 11:42:40,70] [info] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-3531327",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
[2019-04-10 11:42:40,82] [info] Metadata summary refreshing every 2 seconds.
[2019-04-10 11:42:40,96] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-04-10 11:42:40,97] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2019-04-10 11:42:40,98] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-04-10 11:42:42,22] [info] JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
[2019-04-10 11:42:42,35] [info] PAPIQueryManager Running with 3 workers
[2019-04-10 11:42:42,35] [info] JES batch polling interval is 33333 milliseconds
[2019-04-10 11:42:42,36] [info] JES batch polling interval is 33333 milliseconds
[2019-04-10 11:42:42,37] [info] JES batch polling interval is 33333 milliseconds
[2019-04-10 11:42:42,39] [info] SingleWorkflowRunnerActor: Version 34
[2019-04-10 11:42:42,39] [info] SingleWorkflowRunnerActor: Submitting workflow
[2019-04-10 11:42:42,46] [info] Unspecified type (Unspecified version) workflow 6a401b21-aef0-44dc-896e-cd4ff7436050 submitted
[2019-04-10 11:42:42,52] [info] SingleWorkflowRunnerActor: Workflow submitted 6a401b21-aef0-44dc-896e-cd4ff7436050
[2019-04-10 11:42:42,53] [info] 1 new workflows fetched
[2019-04-10 11:42:42,53] [info] WorkflowManagerActor Starting workflow 6a401b21-aef0-44dc-896e-cd4ff7436050
[2019-04-10 11:42:42,54] [info] WorkflowManagerActor Successfully started WorkflowActor-6a401b21-aef0-44dc-896e-cd4ff7436050
[2019-04-10 11:42:42,54] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2019-04-10 11:42:42,54] [warn] SingleWorkflowRunnerActor: received unexpected message: Done in state RunningSwraData
[2019-04-10 11:42:42,57] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
[2019-04-10 11:42:42,72] [info] MaterializeWorkflowDescriptorActor [6a401b21]: Parsing workflow as WDL draft-2
[2019-04-10 11:45:34,61] [info] MaterializeWorkflowDescriptorActor [6a401b21]: Call-to-Backend assignments: atac.count_signal_track_pooled -> local, atac.idr_pr -> local, atac.idr_ppr -> local, atac.overlap_ppr -> local, atac.reproducibility_idr -> local, atac.macs2_signal_track_pooled -> local, atac.pool_ta_pr1 -> local, atac.pool_ta_pr2 -> local, atac.spr -> local, atac.macs2_ppr2 -> local, atac.macs2_ppr1 -> local, atac.pool_ta -> local, atac.read_genome_tsv -> local, atac.trim_adapter -> local, atac.count_signal_track -> local, atac.overlap -> local, atac.bam2ta -> local, atac.macs2_pr1 -> local, atac.filter -> local, atac.reproducibility_overlap -> local, atac.ataqc -> local, atac.xcor -> local, atac.bowtie2 -> local, atac.overlap_pr -> local, atac.macs2_pooled -> local, atac.macs2 -> local, atac.macs2_pr2 -> local, atac.macs2_signal_track -> local, atac.qc_report -> local, atac.idr -> local
[2019-04-10 11:45:34,73] [error] Error parsing generated wdl:

java.lang.RuntimeException: Error parsing generated wdl:

        at cromwell.backend.impl.sfs.config.ConfigWdlNamespace.<init>(ConfigWdlNamespace.scala:55)
        at cromwell.backend.impl.sfs.config.ConfigInitializationActor.configWdlNamespace$lzycompute(ConfigInitializationActor.scala:39)
        at cromwell.backend.impl.sfs.config.ConfigInitializationActor.configWdlNamespace(ConfigInitializationActor.scala:39)
        at cromwell.backend.impl.sfs.config.ConfigInitializationActor.declarationValidations$lzycompute(ConfigInitializationActor.scala:42)
        at cromwell.backend.impl.sfs.config.ConfigInitializationActor.declarationValidations(ConfigInitializationActor.scala:41)
        at cromwell.backend.impl.sfs.config.ConfigInitializationActor.runtimeAttributesBuilder$lzycompute(ConfigInitializationActor.scala:53)
        at cromwell.backend.impl.sfs.config.ConfigInitializationActor.runtimeAttributesBuilder(ConfigInitializationActor.scala:52)
        at cromwell.backend.standard.StandardInitializationActor.coerceDefaultRuntimeAttributes(StandardInitializationActor.scala:82)
        at cromwell.backend.BackendWorkflowInitializationActor.initSequence(BackendWorkflowInitializationActor.scala:154)
        at cromwell.backend.BackendWorkflowInitializationActor.initSequence$(BackendWorkflowInitializationActor.scala:152)
        at cromwell.backend.standard.StandardInitializationActor.initSequence(StandardInitializationActor.scala:44)
        at cromwell.backend.BackendWorkflowInitializationActor$$anonfun$receive$1.$anonfun$applyOrElse$1(BackendWorkflowInitializationActor.scala:145)
        at cromwell.backend.BackendLifecycleActor.performActionThenRespond(BackendLifecycleActor.scala:44)
        at cromwell.backend.BackendLifecycleActor.performActionThenRespond$(BackendLifecycleActor.scala:40)
        at cromwell.backend.standard.StandardInitializationActor.performActionThenRespond(StandardInitializationActor.scala:44)
        at cromwell.backend.BackendWorkflowInitializationActor$$anonfun$receive$1.applyOrElse(BackendWorkflowInitializationActor.scala:145)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.backend.standard.StandardInitializationActor.aroundReceive(StandardInitializationActor.scala:44)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException: null
        at wdl.draft2.model.WdlNamespace$.apply(WdlNamespace.scala:196)
        at wdl.draft2.model.WdlNamespace$.$anonfun$load$1(WdlNamespace.scala:160)
        at scala.util.Try$.apply(Try.scala:209)
        at wdl.draft2.model.WdlNamespace$.load(WdlNamespace.scala:160)
        at wdl.draft2.model.WdlNamespace$.loadUsingSource(WdlNamespace.scala:156)
        at cromwell.backend.impl.sfs.config.ConfigWdlNamespace.<init>(ConfigWdlNamespace.scala:53)
        ... 27 common frames omitted
```

**Comment by leepc12** [comment]
Sorry, I am building singularity images for v1.1.7.1 on SCG now. This will be fixed in 2-3 hours. I will comment here when it's done.

**Comment by nicolerg** [comment]
Thank you!

**Comment by leepc12** [comment]
@nicolerg It's all done.
