### ISSUE TITLE
Chromosome size file truncated

### ISSUE THREAD

**Issue by gaotc200** [ENCODE-DCC/atac-seq-pipeline#117]
Hi!

I'm using worm's genome ce10 and build the genome database with the `build_genome_data.sh`. After that, under the genome database folder, it has file `ce10.chrom.sizes` containing 
```
chrI	15072423
chrII	15279345
chrIII	13783700
chrIV	17493793
chrM	13794
chrV	20924149
chrX	17718866
```
Then I run the pipeline, but it fails with the follwing stderr
```
==> ./call-macs2_pr1/shard-0/execution/stderr <==
Traceback (most recent call last):
  File "/ysm-gpfs/home/jg2447/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_macs2_atac.py", line 219, in <module>
    main()
  File "/ysm-gpfs/home/jg2447/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_macs2_atac.py", line 202, in main
    peak_to_bigbed(bfilt_npeak, 'narrowPeak', args.chrsz, args.keep_irregular_chr, args.out_dir)
  File "/gpfs/ysm/home/jg2447/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_common_genomic.py", line 361, in peak_to_bigbed
    run_shell_cmd(cmd3)
  File "/gpfs/ysm/home/jg2447/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=4872, PGID=4872, RC=255
STDERR=Chromosome chrI isn't in SRR7164236.trim.merged.nodup.tn5.pr1.pval0.01.300K.bfilt.chrsz.tmp line 1 of SRR7164236.trim.merged.nodup.tn5.pr1.pval0.01.300K.bfilt.bb.tmp: chrI:3636-4084
STDOUT=

==> ./call-macs2/shard-0/execution/stderr <==
Traceback (most recent call last):
  File "/ysm-gpfs/home/jg2447/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_macs2_atac.py", line 219, in <module>
    main()
  File "/ysm-gpfs/home/jg2447/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_macs2_atac.py", line 202, in main
    peak_to_bigbed(bfilt_npeak, 'narrowPeak', args.chrsz, args.keep_irregular_chr, args.out_dir)
  File "/gpfs/ysm/home/jg2447/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_common_genomic.py", line 361, in peak_to_bigbed
    run_shell_cmd(cmd3)
  File "/gpfs/ysm/home/jg2447/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=3954, PGID=3954, RC=255
STDERR=Chromosome chrI isn't in SRR7164236.trim.merged.nodup.tn5.pval0.01.300K.bfilt.chrsz.tmp line 1 of SRR7164236.trim.merged.nodup.tn5.pval0.01.300K.bfilt.bb.tmp: chrI:3631-4099
STDOUT=

==> ./call-macs2_pr2/shard-0/execution/stderr <==
Traceback (most recent call last):
  File "/ysm-gpfs/home/jg2447/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_macs2_atac.py", line 219, in <module>
    main()
  File "/ysm-gpfs/home/jg2447/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_macs2_atac.py", line 202, in main
    peak_to_bigbed(bfilt_npeak, 'narrowPeak', args.chrsz, args.keep_irregular_chr, args.out_dir)
  File "/gpfs/ysm/home/jg2447/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_common_genomic.py", line 361, in peak_to_bigbed
    run_shell_cmd(cmd3)
  File "/gpfs/ysm/home/jg2447/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=5069, PGID=5069, RC=255
STDERR=Chromosome chrI isn't in SRR7164236.trim.merged.nodup.tn5.pr2.pval0.01.300K.bfilt.chrsz.tmp line 1 of SRR7164236.trim.merged.nodup.tn5.pr2.pval0.01.300K.bfilt.bb.tmp: chrI:3640-4105
STDOUT=
```
If I go into those `.chrsz.tmp` file, they only have the last line of the chromosome size file: 
```
chrX	17718866
```

Could you help with this problem? Thank you.

Additional info:
- Cromwell version: `cromwell-34.jar`
- Conda version: `conda 4.6.13`
- I've successfully run the example data in the tutorial so the setting should be fine.

**Comment by leepc12** [comment]
Please activate `"atac.keep_irregular_chr_in_bfilt_peak" : true` in your input JSON.

**Comment by gaotc200** [comment]
Thank you. It seems to work now.
