### ISSUE TITLE
Pipeline fail at GC Quality Control Plot and after

### ISSUE THREAD

**Issue by tAndreani** [ENCODE-DCC/atac-seq-pipeline#119]
**Describe the bug**
I am running the pipeline and It works perfectly until the last part of the quality control steps. Then at the point of creating the "my_sample.gcPlot.pdf" it fails. Hence, I dont have the html page with the final resume of the analysis.

**OS/Platform and dependencies**
- OS or Platform: [`Ubuntu 16.04`]
- Cromwell/dxWDL version: [`cromwell-34.jar`]
- Conda version: If you have used Conda (`$ conda 4.6.12`).
- singularity version: If you have used singularity (`NA`).

**Attach error logs**
This is from the file `call-ataqc/shard-0/execution/stderr`
```
WorkflowManagerActor Workflow a431225b-3636-4956-9e71-d5e96d74ce09 failed (during ExecutingWorkflowState): Job atac.ataqc:0:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /data/pinello/PROJECTS/2019_03_scATAC/Datasets/Buenrostro_2018/bamtopeaks/atacseq_pipeline/CLP/cromwell-executions/atac/a431225b-3636-4956-9e71-d5e96d74ce09/call-ataqc/shard-0/execution/stderr.
 Picked up _JAVA_OPTIONS: -Xms256M -Xmx15000M -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/data/pinello/PROJECTS/2019_03_scATAC/Datasets/Buenrostro_2018/bamtopeaks/atacseq_pipeline/CLP/cromwell-executions/atac/a431225b-3636-4956-9e71-d5e96d74ce09/call-ataqc/shard-0/tmp.6e014e48
Exception in thread "main" htsjdk.samtools.SAMException: Reference sequence (25) not found in /data/pinello/PROJECTS/2019_03_scATAC/Datasets/Buenrostro_2018/bamtopeaks/atacseq_pipeline/CLP/cromwell-executions/atac/a431225b-3636-4956-9e71-d5e96d74ce09/call-ataqc/shard-0/inputs/-553901885/male.hg19.fa.gz
        at htsjdk.samtools.reference.ReferenceSequenceFileWalker.get(ReferenceSequenceFileWalker.java:99)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:134)
        at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:77)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:228)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
Picked up _JAVA_OPTIONS: -Xms256M -Xmx15000M -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/data/pinello/PROJECTS/2019_03_scATAC/Datasets/Buenrostro_2018/bamtopeaks/atacseq_pipeline/CLP/cromwell-executions/atac/a431225b-3636-4956-9e71-d5e96d74ce09/call-ataqc/shard-0/tmp.6e014e48
[bam_sort_core] merging from 12 files...
Picked up _JAVA_OPTIONS: -Xms256M -Xmx15000M -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/data/pinello/PROJECTS/2019_03_scATAC/Datasets/Buenrostro_2018/bamtopeaks/atacseq_pipeline/CLP/cromwell-executions/atac/a431225b-3636-4956-9e71-d5e96d74ce09/call-ataqc/shard-0/tmp.6e014e48
processing chromosomes
Traceback (most recent call last):
  File "/data/pinello/SHARED_SOFTWARE/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_ataqc.py", line 465, in <module>
    ataqc()
  File "/data/pinello/SHARED_SOFTWARE/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_ataqc.py", line 378, in ataqc
    SAMPLE['gc_bias'] = plot_gc(gc_out)
  File "/data/pinello/SHARED_SOFTWARE/anaconda3/envs/encode-atac-seq-pipeline/bin/run_ataqc.py", line 253, in plot_gc
    data = pd.read_table(data_file, comment="#")
  File "/data/pinello/SHARED_SOFTWARE/anaconda3/envs/encode-atac-seq-pipeline/lib/python2.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/data/pinello/SHARED_SOFTWARE/anaconda3/envs/encode-atac-seq-pipeline/lib/python2.7/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/data/pinello/SHARED_SOFTWARE/anaconda3/envs/encode-atac-seq-pipeline/lib/python2.7/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/data/pinello/SHARED_SOFTWARE/anaconda3/envs/encode-atac-seq-pipeline/lib/python2.7/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/data/pinello/SHARED_SOFTWARE/anaconda3/envs/encode-atac-seq-pipeline/lib/python2.7/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
```
It seems the main problem is the genome `male.hg19.fa.gz` and it is related with `
```
htsjdk.samtools.SAMException: Reference sequence (25) not found in /data/pinello/PROJECTS/2019_03_scATAC/Datasets/Buenrostro_2018/bamtopeaks/atacseq_pipeline/CLP/cromwell-executions/atac/a431225b-3636-4956-9e71-d5e96d74ce09/call-ataqc/shard-0/inputs/-553901885/male.hg19.fa.gz
```
I can anticipate that the genome is there (see the image below)
https://imgur.com/a/X33ssPn#vPIYE5u

Thanks in advance for any help

**Comment by leepc12** [comment]
Please check if this file exists first.
```
/data/pinello/PROJECTS/2019_03_scATAC/Datasets/Buenrostro_2018/bamtopeaks/atacseq_pipeline/CLP/cromwell-executions/atac/a431225b-3636-4956-9e71-d5e96d74ce09/call-ataqc/shard-0/inputs/-553901885/male.hg19.fa.gz
```
How did you install hg19 genome data? Please go to your genome database directory `some/where/hg19/` and check if `.fa.gz` is there.

**Comment by tAndreani** [comment]
Hi, 
this is where the file it is and seems to be there and okay.
https://imgur.com/YRIfF6d

The genome was installed in this way as suggested:

/data/SHARED_SOFTWARE/atac-seq-pipeline/genome/download_genome_data.sh hg19 ./

**Comment by leepc12** [comment]
@vervacity : Could you look into this issue?

**Comment by tAndreani** [comment]
i believe it is something related to the way the hg19 genome is obtained by the pipeline. If you look at the output of the genome preparation are not present the random chromosomes..

**Comment by leepc12** [comment]
@tAndreani : Can you upload a tar ball of all logs? What was your full command line to run a pipeline?

**Comment by vervacity** [comment]
the error message suggests that there is some sequence in your BAM that is not in the fasta file. it sounds like you're using BAMs that you've downloaded - this could lead to the error you're seeing because the BAM file may have been aligned using a slightly different FASTA file (in which case there will be sequence positions in your BAM file that do not match anything in our provided fasta file). there are two possible solutions here: 1) determine what fasta file was used for alignment, and use that fasta file in the pipeline 2) start from FASTQ and use our pipeline with no modification (everything is internally controlled when starting from FASTQ). best of luck!

**Comment by tAndreani** [comment]
The problem is solved. We had bam files with some chromosomes that were CONTIG. We removed them and that's it thanks.
