### ISSUE TITLE
pipeline hangs with error parsing generated wdl

### ISSUE THREAD

**Issue by jwtobias** [ENCODE-DCC/atac-seq-pipeline#120]
Release version installed 20190430, mm10 genome downloaded. Pipeline fails with error parsing generated wdl before writing anything to cromwell executions

**OS/Platform and dependencies**
$ uname -a
Linux r94001.hpc.local 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Cromwell/dxWDL version:cromwell-34.jar
- Conda version: conda 4.6.14

I've attached my .json input file, my console error log and the debug output including the logs in cromwell-workflow-logs.

Thanks for your help!

- John

[debug_120.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3132778/debug_120.tar.gz)
[rc_pe_pos.json.zip](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3132781/rc_pe_pos.json.zip)
[console_error_issue120.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3132785/console_error_issue120.txt)

**Comment by leepc12** [comment]
This looks like a duplicate issue of issue #111. What is your pipeline version?

**Comment by jwtobias** [comment]
I just downloaded the release version this morning.

**Comment by leepc12** [comment]
Please download cromwell-38.jar and use it instead of cromwell-34.jar.
https://github.com/broadinstitute/cromwell/releases/download/38/cromwell-38.jar

**Comment by jwtobias** [comment]
I just tried the cromwell upgrade and also changing the conda environment commands to "conda activate encode..." and conda deactivate in the appropriate conda/*.sh scripts.

Looks like the same error:

[2019-04-30 17:01:54,39] [info] Running with database db.url = jdbc:hsqldb:mem:7c44299a-dad4-4c42-856b-b84156b8fb75;shutdown=false;hsqldb.tx=mvcc
[2019-04-30 17:02:01,73] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2019-04-30 17:02:01,74] [info] [RenameWorkflowOptionsInMetadata] 100%
[2019-04-30 17:02:01,84] [info] Running with database db.url = jdbc:hsqldb:mem:f246db1a-64fc-4039-a74f-a9bfa7f2c5ab;shutdown=false;hsqldb.tx=mvcc
[2019-04-30 17:02:02,25] [warn] This actor factory is deprecated. Please use cromwell.backend.google.pipelines.v1alpha2.PipelinesApiLifecycleActorFactory for PAPI v1 or cromwell.backend.google.pipelines.v2alpha1.PipelinesApiLifecycleActorFactory for PAPI v2
[2019-04-30 17:02:02,58] [info] Slf4jLogger started
[2019-04-30 17:02:02,84] [info] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-7af9890",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
[2019-04-30 17:02:02,91] [info] Metadata summary refreshing every 2 seconds.
[2019-04-30 17:02:02,94] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-04-30 17:02:02,97] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-04-30 17:02:02,97] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2019-04-30 17:02:02,97] [warn] 'docker.hash-lookup.gcr-api-queries-per-100-seconds' is being deprecated, use 'docker.hash-lookup.gcr.throttle' instead (see reference.conf)
[2019-04-30 17:02:03,12] [info] JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
[2019-04-30 17:02:03,27] [info] SingleWorkflowRunnerActor: Version 38
[2019-04-30 17:02:03,28] [info] SingleWorkflowRunnerActor: Submitting workflow
[2019-04-30 17:02:03,45] [info] Unspecified type (Unspecified version) workflow f7068cbc-e8ee-49dd-afcb-49066ae48985 submitted
[2019-04-30 17:02:03,47] [info] SingleWorkflowRunnerActor: Workflow submitted f7068cbc-e8ee-49dd-afcb-49066ae48985
[2019-04-30 17:02:03,47] [info] 1 new workflows fetched
[2019-04-30 17:02:03,47] [info] WorkflowManagerActor Starting workflow f7068cbc-e8ee-49dd-afcb-49066ae48985
[2019-04-30 17:02:03,47] [info] WorkflowManagerActor Successfully started WorkflowActor-f7068cbc-e8ee-49dd-afcb-49066ae48985
[2019-04-30 17:02:03,48] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2019-04-30 17:02:03,49] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
[2019-04-30 17:02:03,54] [info] JES batch polling interval is 33333 milliseconds
[2019-04-30 17:02:03,54] [info] JES batch polling interval is 33333 milliseconds
[2019-04-30 17:02:03,54] [info] JES batch polling interval is 33333 milliseconds
[2019-04-30 17:02:03,56] [info] PAPIQueryManager Running with 3 workers
[2019-04-30 17:02:03,65] [info] MaterializeWorkflowDescriptorActor [f7068cbc]: Parsing workflow as WDL draft-2
[2019-04-30 17:02:06,51] [info] MaterializeWorkflowDescriptorActor [f7068cbc]: Call-to-Backend assignments: atac.xcor -> local, atac.bowtie2 -> local, atac.idr -> local, atac.read_genome_tsv -> local, atac.ataqc -> local, atac.overlap_pr -> local, atac.trim_adapter -> local, atac.macs2_ppr1 -> local, atac.overlap_ppr -> local, atac.idr_pr -> local, atac.macs2_signal_track -> local, atac.pool_ta_pr2 -> local, atac.macs2_signal_track_pooled -> local, atac.macs2 -> local, atac.pool_ta_pr1 -> local, atac.pool_ta -> local, atac.filter -> local, atac.idr_ppr -> local, atac.macs2_pr2 -> local, atac.macs2_ppr2 -> local, atac.qc_report -> local, atac.reproducibility_overlap -> local, atac.bam2ta -> local, atac.overlap -> local, atac.macs2_pooled -> local, atac.reproducibility_idr -> local, atac.spr -> local, atac.macs2_pr1 -> local, atac.count_signal_track_pooled -> local, atac.count_signal_track -> local
[2019-04-30 17:02:06,56] [error] Error parsing generated wdl:

java.lang.RuntimeException: Error parsing generated wdl:

	at cromwell.backend.impl.sfs.config.ConfigWdlNamespace.<init>(ConfigWdlNamespace.scala:55)
	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.configWdlNamespace$lzycompute(ConfigInitializationActor.scala:39)
	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.configWdlNamespace(ConfigInitializationActor.scala:39)
	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.declarationValidations$lzycompute(ConfigInitializationActor.scala:42)
	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.declarationValidations(ConfigInitializationActor.scala:41)
	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.runtimeAttributesBuilder$lzycompute(ConfigInitializationActor.scala:53)
	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.runtimeAttributesBuilder(ConfigInitializationActor.scala:52)
	at cromwell.backend.standard.StandardInitializationActor.coerceDefaultRuntimeAttributes(StandardInitializationActor.scala:82)
	at cromwell.backend.BackendWorkflowInitializationActor.initSequence(BackendWorkflowInitializationActor.scala:155)
	at cromwell.backend.BackendWorkflowInitializationActor.initSequence$(BackendWorkflowInitializationActor.scala:153)
	at cromwell.backend.standard.StandardInitializationActor.initSequence(StandardInitializationActor.scala:44)
	at cromwell.backend.BackendWorkflowInitializationActor$$anonfun$receive$1.$anonfun$applyOrElse$1(BackendWorkflowInitializationActor.scala:146)
	at cromwell.backend.BackendLifecycleActor.performActionThenRespond(BackendLifecycleActor.scala:44)
	at cromwell.backend.BackendLifecycleActor.performActionThenRespond$(BackendLifecycleActor.scala:40)
	at cromwell.backend.standard.StandardInitializationActor.performActionThenRespond(StandardInitializationActor.scala:44)
	at cromwell.backend.BackendWorkflowInitializationActor$$anonfun$receive$1.applyOrElse(BackendWorkflowInitializationActor.scala:146)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.backend.standard.StandardInitializationActor.aroundReceive(StandardInitializationActor.scala:44)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: Could not build AST from workflow source. Source is empty or contains only comments and whitespace.
	at wdl.draft2.model.WdlNamespace$.$anonfun$load$1(WdlNamespace.scala:166)
	at scala.util.Try$.apply(Try.scala:209)
	at wdl.draft2.model.WdlNamespace$.load(WdlNamespace.scala:159)
	at wdl.draft2.model.WdlNamespace$.loadUsingSource(WdlNamespace.scala:156)
	at cromwell.backend.impl.sfs.config.ConfigWdlNamespace.<init>(ConfigWdlNamespace.scala:53)
	... 27 common frames omitted
[2019-04-30 17:02:08,13] [info] Not triggering log of token queue status. Effective log interval = None

**Comment by leepc12** [comment]
Please remove `-Dconfig.file=backends/backend.conf` from command line and try again.

**Comment by jwtobias** [comment]
Running without -Dconfig.file=backends/backend.conf (and with cromwell-38.jar seems to have fixed the problem). Thanks! With your new commits, should the -Dconfig.file be added back in?

**Comment by leepc12** [comment]
Yes
