### ISSUE TITLE
Erorr running test data with conda -SAMTOOLS problem

### ISSUE THREAD

**Issue by hmaryam** [ENCODE-DCC/atac-seq-pipeline#125]
**Describe the bug**
I am running encode sample on a local linux using conda and it stops in the middle. I think it is samtools problem. My samtools version is 1.2. 
(I tried it with samtools 1.9 as well and got the same error as #90 Run test sample: samtools error)

**OS/Platform and dependencies**
- OS or Platform: [e.g. Ubuntu 16.04]
- Cromwell/dxWDL version: [e.g. `cromwell-34.jar`, `dxWDL-78.jar`]
- Conda version: conda 4.6.14

Below is what I get when I run java -jar -Dconfig.file=backends/backend.conf ../cromwell-34.jar run atac.wdl -i ${INPUT} -m ${PIPELINE_METADATA}

[2019-05-10 04:04:51,83] [info] BackgroundConfigAsyncJobExecutionActor [681820ffatac.bowtie2:1:1]: python $(which encode_bowtie2.py) \
	/home/genomics/hmaryam/Encode/atac-seq-pipeline/cromwell-executions/atac/681820ff-3bc4-4190-992a-d967a6a768c0/call-bowtie2/shard-1/inputs/1614955664/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.tar \
	/home/genomics/hmaryam/Encode/atac-seq-pipeline/cromwell-executions/atac/681820ff-3bc4-4190-992a-d967a6a768c0/call-bowtie2/shard-1/inputs/1245078046/ENCFF641SFZ.subsampled.400.merged.fastq.gz /home/genomics/hmaryam/Encode/atac-seq-pipeline/cromwell-executions/atac/681820ff-3bc4-4190-992a-d967a6a768c0/call-bowtie2/shard-1/inputs/2133361091/ENCFF031ARQ.subsampled.400.merged.fastq.gz \
	--paired-end \
	--multimapping 4 \
	--bowtie2-param-se ' --local' \
	--bowtie2-param-pe ' -X2000 --mm --local' \
	--nth 40
[2019-05-10 04:04:51,83] [info] BackgroundConfigAsyncJobExecutionActor [681820ffatac.bowtie2:1:1]: executing: /bin/bash /home/genomics/hmaryam/Encode/atac-seq-pipeline/cromwell-executions/atac/681820ff-3bc4-4190-992a-d967a6a768c0/call-bowtie2/shard-1/execution/script
[2019-05-10 04:04:56,47] [info] BackgroundConfigAsyncJobExecutionActor [681820ffatac.bowtie2:1:1]: job id: 390746
[2019-05-10 04:04:56,47] [info] BackgroundConfigAsyncJobExecutionActor [681820ffatac.bowtie2:1:1]: Status change from - to WaitingForReturnCodeFile
[2019-05-10 04:06:39,53] [info] BackgroundConfigAsyncJobExecutionActor [681820ffatac.bowtie2:0:1]: Status change from WaitingForReturnCodeFile to Done
[2019-05-10 04:07:05,40] [info] BackgroundConfigAsyncJobExecutionActor [681820ffatac.bowtie2:1:1]: Status change from WaitingForReturnCodeFile to Done
[2019-05-10 04:07:05,85] [error] WorkflowManagerActor Workflow 681820ff-3bc4-4190-992a-d967a6a768c0 failed (during ExecutingWorkflowState): Job atac.bowtie2:0:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /home/genomics/hmaryam/Encode/atac-seq-pipeline/cromwell-executions/atac/681820ff-3bc4-4190-992a-d967a6a768c0/call-bowtie2/shard-0/execution/stderr.
 Traceback (most recent call last):
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_bowtie2.py", line 209, in <module>
    main()
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_bowtie2.py", line 171, in main
    args.out_dir)
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_bowtie2.py", line 118, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=390794, PGID=390794, RC=13
STDERR=
STDOUT=

Job atac.bowtie2:1:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /home/genomics/hmaryam/Encode/atac-seq-pipeline/cromwell-executions/atac/681820ff-3bc4-4190-992a-d967a6a768c0/call-bowtie2/shard-1/execution/stderr.
 Traceback (most recent call last):
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_bowtie2.py", line 209, in <module>
    main()
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_bowtie2.py", line 171, in main
    args.out_dir)
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_bowtie2.py", line 118, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=390813, PGID=390813, RC=13
STDERR=
STDOUT=

[2019-05-10 04:07:05,86] [info] WorkflowManagerActor WorkflowActor-681820ff-3bc4-4190-992a-d967a6a768c0 is in a terminal state: WorkflowFailedState
[2019-05-10 04:07:42,42] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2019-05-10 04:07:46,53] [info] SingleWorkflowRunnerActor writing metadata to metadata.json
[2019-05-10 04:07:46,56] [info] Workflow polling stopped
[2019-05-10 04:07:46,57] [info] Shutting down WorkflowStoreActor - Timeout = 5 seconds
[2019-05-10 04:07:46,57] [info] Shutting down WorkflowLogCopyRouter - Timeout = 5 seconds
[2019-05-10 04:07:46,57] [info] Shutting down JobExecutionTokenDispenser - Timeout = 5 seconds
[2019-05-10 04:07:46,57] [info] Aborting all running workflows.
[2019-05-10 04:07:46,58] [info] JobExecutionTokenDispenser stopped
[2019-05-10 04:07:46,58] [info] WorkflowStoreActor stopped
[2019-05-10 04:07:46,58] [info] WorkflowLogCopyRouter stopped
[2019-05-10 04:07:46,58] [info] Shutting down WorkflowManagerActor - Timeout = 3600 seconds
[2019-05-10 04:07:46,58] [info] WorkflowManagerActor All workflows finished
[2019-05-10 04:07:46,58] [info] WorkflowManagerActor stopped
[2019-05-10 04:07:46,58] [info] Connection pools shut down
[2019-05-10 04:07:46,58] [info] Shutting down SubWorkflowStoreActor - Timeout = 1800 seconds
[2019-05-10 04:07:46,58] [info] Shutting down JobStoreActor - Timeout = 1800 seconds
[2019-05-10 04:07:46,58] [info] Shutting down CallCacheWriteActor - Timeout = 1800 seconds
[2019-05-10 04:07:46,58] [info] Shutting down ServiceRegistryActor - Timeout = 1800 seconds
[2019-05-10 04:07:46,58] [info] Shutting down DockerHashActor - Timeout = 1800 seconds
[2019-05-10 04:07:46,58] [info] Shutting down IoProxy - Timeout = 1800 seconds
[2019-05-10 04:07:46,58] [info] SubWorkflowStoreActor stopped
[2019-05-10 04:07:46,58] [info] CallCacheWriteActor Shutting down: 0 queued messages to process
[2019-05-10 04:07:46,58] [info] KvWriteActor Shutting down: 0 queued messages to process
[2019-05-10 04:07:46,58] [info] WriteMetadataActor Shutting down: 0 queued messages to process
[2019-05-10 04:07:46,58] [info] JobStoreActor stopped
[2019-05-10 04:07:46,58] [info] DockerHashActor stopped
[2019-05-10 04:07:46,58] [info] CallCacheWriteActor stopped
[2019-05-10 04:07:46,58] [info] IoProxy stopped
[2019-05-10 04:07:46,58] [info] ServiceRegistryActor stopped
[2019-05-10 04:07:46,63] [info] Database closed
[2019-05-10 04:07:46,63] [info] Stream materializer shut down
Workflow 681820ff-3bc4-4190-992a-d967a6a768c0 transitioned to state Failed
[2019-05-10 04:07:46,66] [info] Automatic shutdown of the async connection
[2019-05-10 04:07:46,66] [info] Gracefully shutdown sentry threads.
[2019-05-10 04:07:46,66] [info] Shutdown finished.

**Attach error logs**
(/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC) [genomics@genomics3 atac]$ $ find -name stderr -not -empty | xargs tail -n +1
bash: $: command not found...
(/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC) [genomics@genomics3 atac]$ find -name stderr -not -empty | xargs tail -n +1
==> ./59044189-7012-4793-9cc1-8e9b106dfca5/call-bowtie2/shard-0/execution/stderr <==
Traceback (most recent call last):
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_bowtie2.py", line 209, in <module>
    main()
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_bowtie2.py", line 171, in main
    args.out_dir)
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_bowtie2.py", line 118, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=126654, PGID=126654, RC=13
STDERR=
STDOUT=

==> ./59044189-7012-4793-9cc1-8e9b106dfca5/call-bowtie2/shard-1/execution/stderr <==
Traceback (most recent call last):
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_bowtie2.py", line 209, in <module>
    main()
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_bowtie2.py", line 171, in main
    args.out_dir)
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_bowtie2.py", line 118, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/home/genomics/bioinformatics/app/miniconda/minicoda3/ATAC/bin/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=126673, PGID=126673, RC=13
STDERR=
STDOUT=

**Comment by hmaryam** [comment]
I realized that it was the problem with my perl. running "$perl -V" , I got the error: "can't locate strict.pm:".
solving this problem, I could run the pipeline
