### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by rameshvnair** [ENCODE-DCC/atac-seq-pipeline#141]
I ran the latest ATAC-Seq v1.4.2 pipeline and it failed towards the end at step "call-ataqc" with the following error. So it never generated the "call-qc_report" folder.

ValueError: all the input array dimensions except for the concatenation axis must match exactly

Could you help me troubleshoot this error? Thanks.

**Comment by leepc12** [comment]
[2019-07-17 09:01:59,71] [[38;5;1merror[0m] WorkflowManagerActor Workflow aa2a7ce2-b627-4a99-a30f-03cfdc85d6cf failed (during ExecutingWorkflowState): Job atac.ataqc:1:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /BaaS/labs/longaker/gpfs_migrated/natalina/suture_explants_atac_seq/suture_explants_singularity_v142/sample_1_PF_C/cromwell-executions/atac/aa2a7ce2-b627-4a99-a30f-03cfdc85d6cf/call-ataqc/shard-1/execution/stderr.
 /usr/local/lib/python2.7/dist-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Picked up _JAVA_OPTIONS: -Xms256M -Xmx4000M -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/BaaS/labs/longaker/gpfs_migrated/natalina/suture_explants_atac_seq/suture_explants_singularity_v142/sample_1_PF_C/cromwell-executions/atac/aa2a7ce2-b627-4a99-a30f-03cfdc85d6cf/call-ataqc/shard-1/tmp.256e703a
Picked up _JAVA_OPTIONS: -Xms256M -Xmx4000M -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/BaaS/labs/longaker/gpfs_migrated/natalina/suture_explants_atac_seq/suture_explants_singularity_v142/sample_1_PF_C/cromwell-executions/atac/aa2a7ce2-b627-4a99-a30f-03cfdc85d6cf/call-ataqc/shard-1/tmp.256e703a
[bam_sort_core] merging from 106 files...
Picked up _JAVA_OPTIONS: -Xms256M -Xmx4000M -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/BaaS/labs/longaker/gpfs_migrated/natalina/suture_explants_atac_seq/suture_explants_singularity_v142/sample_1_PF_C/cromwell-executions/atac/aa2a7ce2-b627-4a99-a30f-03cfdc85d6cf/call-ataqc/shard-1/tmp.256e703a
processing chromosomes
Traceback (most recent call last):
  File "/software/atac-seq-pipeline/src/encode_ataqc.py", line 469, in <module>
    ataqc()
  File "/software/atac-seq-pipeline/src/encode_ataqc.py", line 283, in ataqc
    ROADMAP_META, OUTPUT_PREFIX)
  File "/software/atac-seq-pipeline/src/run_ataqc.py", line 996, in compare_to_roadmap
    sample_mean0_col)
  File "/usr/local/lib/python2.7/dist-packages/scipy-1.0.0-py2.7-linux-x86_64.egg/scipy/stats/stats.py", line 3309, in spearmanr
    rs = np.corrcoef(ar, br, rowvar=axisout)
  File "/usr/local/lib/python2.7/dist-packages/numpy-1.11.3-py2.7-linux-x86_64.egg/numpy/lib/function_base.py", line 2561, in corrcoef
    c = cov(x, y, rowvar)
  File "/usr/local/lib/python2.7/dist-packages/numpy-1.11.3-py2.7-linux-x86_64.egg/numpy/lib/function_base.py", line 2432, in cov
    X = np.vstack((X, y))
  File "/usr/local/lib/python2.7/dist-packages/numpy-1.11.3-py2.7-linux-x86_64.egg/numpy/core/shape_base.py", line 230, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

Job atac.ataqc:0:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /BaaS/labs/longaker/gpfs_migrated/natalina/suture_explants_atac_seq/suture_explants_singularity_v142/sample_1_PF_C/cromwell-executions/atac/aa2a7ce2-b627-4a99-a30f-03cfdc85d6cf/call-ataqc/shard-0/execution/stderr.
 /usr/local/lib/python2.7/dist-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Picked up _JAVA_OPTIONS: -Xms256M -Xmx4000M -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/BaaS/labs/longaker/gpfs_migrated/natalina/suture_explants_atac_seq/suture_explants_singularity_v142/sample_1_PF_C/cromwell-executions/atac/aa2a7ce2-b627-4a99-a30f-03cfdc85d6cf/call-ataqc/shard-0/tmp.b50918b0
Picked up _JAVA_OPTIONS: -Xms256M -Xmx4000M -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/BaaS/labs/longaker/gpfs_migrated/natalina/suture_explants_atac_seq/suture_explants_singularity_v142/sample_1_PF_C/cromwell-executions/atac/aa2a7ce2-b627-4a99-a30f-03cfdc85d6cf/call-ataqc/shard-0/tmp.b50918b0
[bam_sort_core] merging from 106 files...
Picked up _JAVA_OPTIONS: -Xms256M -Xmx4000M -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/BaaS/labs/longaker/gpfs_migrated/natalina/suture_explants_atac_seq/suture_explants_singularity_v142/sample_1_PF_C/cromwell-executions/atac/aa2a7ce2-b627-4a99-a30f-03cfdc85d6cf/call-ataqc/shard-0/tmp.b50918b0
processing chromosomes
Traceback (most recent call last):
  File "/software/atac-seq-pipeline/src/encode_ataqc.py", line 469, in <module>
    ataqc()
  File "/software/atac-seq-pipeline/src/encode_ataqc.py", line 283, in ataqc
    ROADMAP_META, OUTPUT_PREFIX)
  File "/software/atac-seq-pipeline/src/run_ataqc.py", line 996, in compare_to_roadmap
    sample_mean0_col)
  File "/usr/local/lib/python2.7/dist-packages/scipy-1.0.0-py2.7-linux-x86_64.egg/scipy/stats/stats.py", line 3309, in spearmanr
    rs = np.corrcoef(ar, br, rowvar=axisout)
  File "/usr/local/lib/python2.7/dist-packages/numpy-1.11.3-py2.7-linux-x86_64.egg/numpy/lib/function_base.py", line 2561, in corrcoef
    c = cov(x, y, rowvar)
  File "/usr/local/lib/python2.7/dist-packages/numpy-1.11.3-py2.7-linux-x86_64.egg/numpy/lib/function_base.py", line 2432, in cov
    X = np.vstack((X, y))
  File "/usr/local/lib/python2.7/dist-packages/numpy-1.11.3-py2.7-linux-x86_64.egg/numpy/core/shape_base.py", line 230, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

**Comment by leepc12** [comment]
We found that ATAQC part is not very stable and ATAQC is factored out to individual task and removed from the pipeline in the next release. This problematic task will be disabled by default.

You can disable ATAQC for now. Add the following to your input JSON.

```
    "atac.disable_ataqc" : true,
```

**Comment by rameshvnair** [comment]
So this means I can remove the following from my input json?
"atac.ataqc_mem_mb" : 5000,
"atac.ataqc_mem_java_mb" : 4000,
"atac.ataqc_time_hr" : 1,

**Comment by leepc12** [comment]
Yes you can remove them. BTW they look quite small. Did you change them?
Default should be like > 10000.

Jin

**Comment by rameshvnair** [comment]
Hi Jin,

I could not get caper to run so I pulled v1.4.2 simg and started singularity run as before. I used the recommendations for scg run which are smaller as opposed to caper run.

Best,
Ramesh
________________________________

**Comment by rameshvnair** [comment]
I could not get caper to run so I pulled v1.4.2 simg and started singularity run as before. I used the recommendations for scg run which are smaller as opposed to caper run.

**Comment by leepc12** [comment]
Closing this due to long inactivity
