### ISSUE TITLE
how actually does one run your atac pipeline? super frustrated

### ISSUE THREAD

**Issue by tanpuekai** [ENCODE-DCC/atac-seq-pipeline#149]
Hi,
     Glad to see that there is this ENCODE ATAC-seq pipeline.
     We are using some HPC to perform the computing, and as most others, we are not the admin, so a lot of times very difficult to install those packages.
      Anyway, I ve git clone your 'atac-seq-pipeline' files to folder with the same name on our HPC. We have also git cloned the `Caper`.
      I modified your minimum json input specification file to this [input.json]:

```
{
    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "https://storage.googleapis.com/encode-pipeline-genome-data/mm10_caper.tsv",
    "atac.fastqs_rep1_R1" : [
        "primary_seq/repa_1.fastq.gz",
        "primary_seq/repb_1.fastq.gz",
    ],
    "atac.fastqs_rep1_R2" : [
        "primary_seq/repa_2.fastq.gz",
        "primary_seq/repb_2.fastq.gz",
    ],
    "atac.paired_end" : true,
    "atac.multimapping" : 4,
    "atac.auto_detect_adapter" : true,
    "atac.trim_adapter.cpu" : 2,
    "atac.bowtie2_cpu" : 8,
    "atac.bowtie2_mem_mb" : 16000,
    "atac.filter_cpu" : 2,
    "atac.filter_mem_mb" : 12000,
    "atac.macs2_mem_mb" : 16000,
    "atac.smooth_win" : 73,
    "atac.enable_idr" : true,
    "atac.idr_thresh" : 0.05,
    "atac.enable_xcor" : true,
    "atac.title" : "Project1",
    "atac.description" : "Project1"
}
```

And then I submitted a job running this line:
`caper run atac.wdl -i $outdir/input.json --deepcopy --use-singularity`
and I got this error immediately:
```
usage: caper run [-h] [--dry-run] [-i INPUTS] [-o OPTIONS] [-l LABELS]
                 [-p IMPORTS] [-s STR_LABEL] [--hold]
                 [--singularity-cachedir SINGULARITY_CACHEDIR] [--no-deepcopy]
                 [--deepcopy-ext DEEPCOPY_EXT]
                 [--docker [DOCKER [DOCKER ...]]]
                 [--singularity [SINGULARITY [SINGULARITY ...]]]
                 [--no-build-singularity] [--slurm-partition SLURM_PARTITION]
                 [--slurm-account SLURM_ACCOUNT]
                 [--slurm-extra-param SLURM_EXTRA_PARAM] [--sge-pe SGE_PE]
                 [--sge-queue SGE_QUEUE] [--sge-extra-param SGE_EXTRA_PARAM]
                 [--pbs-queue PBS_QUEUE] [--pbs-extra-param PBS_EXTRA_PARAM]
                 [-m METADATA_OUTPUT] [--java-heap-run JAVA_HEAP_RUN]
                 [--db-timeout DB_TIMEOUT] [--file-db FILE_DB] [--no-file-db]
                 [--mysql-db-ip MYSQL_DB_IP] [--mysql-db-port MYSQL_DB_PORT]
                 [--mysql-db-user MYSQL_DB_USER]
                 [--mysql-db-password MYSQL_DB_PASSWORD] [--cromwell CROMWELL]
                 [--max-concurrent-tasks MAX_CONCURRENT_TASKS]
                 [--max-concurrent-workflows MAX_CONCURRENT_WORKFLOWS]
                 [--max-retries MAX_RETRIES] [--disable-call-caching]
                 [--backend-file BACKEND_FILE] [--out-dir OUT_DIR]
                 [--tmp-dir TMP_DIR] [--gcp-prj GCP_PRJ]
                 [--gcp-zones GCP_ZONES] [--out-gcs-bucket OUT_GCS_BUCKET]
                 [--tmp-gcs-bucket TMP_GCS_BUCKET]
                 [--aws-batch-arn AWS_BATCH_ARN] [--aws-region AWS_REGION]
                 [--out-s3-bucket OUT_S3_BUCKET]
                 [--tmp-s3-bucket TMP_S3_BUCKET] [--use-gsutil-over-aws-s3]
                 [-b BACKEND] [--http-user HTTP_USER]
                 [--http-password HTTP_PASSWORD] [--use-netrc]
                 wdl
caper run: error: argument --deepcopy-ext: expected one argument
```
What seems to be the problem?  Seems the `caper run` options are different from your documentations on the landing page of this project?

We have "python3/3.6.4" and "singularity/2.5.2" loaded in out HPC.

**Comment by leepc12** [comment]
We will make a release with fixed documentation soon this week. Please remove `--deepcopy` from the command line and use `--singularity` instead of `--use-singularity`.

**Comment by tanpuekai** [comment]
Hi Jin,
      Glad to hear from you. 
      Unfortunately, the pipeline is still not working. This is the latest error report:
(note that I git cloned the pipeline and caper only 24 hours ago; so they are all up-to-date.)
```
[CaperURI] write to local, target: /User1/atacseq_Proj2019/encode_pipe/Sample1/atac/7d9bcca2-2172-4015-bb4d-cf551a0a3482/metadata.json, size: 88976
[Caper] troubleshooting 7d9bcca2-2172-4015-bb4d-cf551a0a3482 ...
Found failures:
[
    {
        "causedBy": [
            {
                "message": "Job atac.trim_adapter:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.",
                "causedBy": []
            }
        ],
        "message": "Workflow failed"
    }
]

atac.trim_adapter RetryableFailure. SHARD_IDX=0, RC=1, JOB_ID=71318, RUN_START=2019-09-18T02:12:12.227Z, RUN_END=2019-09-18T02:13:51.639Z, STDOUT=/User1/atacseq_Proj2019/encode_pipe/Sample1/atac/7d9bcca2-2172-4015
STDERR_CONTENTS=
which: no encode_trim_adapter.py in (/software/bowtie2/2.3.4.3:/software/singularity/2.5.2/bin:/software/python/3.6.4/bin:/hpc/opt/conda/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/pbs/bin:/opt/dell/srvadmin/bin:/software/sequencing
  File "/User1/atacseq_Proj2019/encode_pipe/Sample1/atac/7d9bcca2-2172-4015-bb4d-cf551a0a3482/call-trim_adapter/shard-0/execution/write_tsv_a361f22de82bfe69988f3d0d0732dde6.tmp", line 1
    /User1/atacseq_Proj2019/encode_pipe/Sample1/atac/7d9bcca2-2172-4015-bb4d-cf551a0a3482/call-trim_adapter/shard-0/inputs/-2028208067/Sample1_1.fastq.gz  /User1/atacseq_Proj2019/encode_pi
    ^
SyntaxError: invalid syntax


atac.trim_adapter Failed. SHARD_IDX=0, RC=1, JOB_ID=71648, RUN_START=2019-09-18T02:13:54.207Z, RUN_END=2019-09-18T02:15:38.733Z, STDOUT=/User1/atacseq_Proj2019/encode_pipe/Sample1/atac/7d9bcca2-2172-4015-bb4d-cf55
STDERR_CONTENTS=
which: no encode_trim_adapter.py in (/software/bowtie2/2.3.4.3:/software/singularity/2.5.2/bin:/software/python/3.6.4/bin:/hpc/opt/conda/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/pbs/bin:/opt/dell/srvadmin/bin:/software/sequencing
  File "/User1/atacseq_Proj2019/encode_pipe/Sample1/atac/7d9bcca2-2172-4015-bb4d-cf551a0a3482/call-trim_adapter/shard-0/attempt-2/execution/write_tsv_f62438d3c442be1631887bbafd63d1c6.tmp", line 1
    /User1/atacseq_Proj2019/encode_pipe/Sample1/atac/7d9bcca2-2172-4015-bb4d-cf551a0a3482/call-trim_adapter/shard-0/attempt-2/inputs/-2028208067/Sample1_1.fastq.gz        /User1/atacseq_se
    ^
SyntaxError: invalid syntax

[Caper] run:  1 7d9bcca2-2172-4015-bb4d-cf551a0a3482 /User1/atacseq_Proj2019/encode_pipe/Sample1/atac/7d9bcca2-2172-4015-bb4d-cf551a0a3482/metadata.json
```

My script is as follows:
(Note that `--singularity` was not added because adding it produced even more premature errors.)

```
/User1/caper/bin/caper run \
    -i input.json \
    --tmp-dir /User1/encode_pipe/TMPDIR \
    atac-seq-pipeline/atac.wdl
```


And my `input.json` is as follows:


```{
    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "https://storage.googleapis.com/encode-pipeline-genome-data/mm10_caper.tsv",
    "atac.fastqs_rep1_R1" : ["/User1/atacseq_Proj2019/RAWDATA/Sample1_1.fastq.gz"],
    "atac.fastqs_rep1_R2": ["/User1/atacseq_Proj2019/RAWDATA/Sample1_2.fastq.gz"],

    "atac.paired_end" : true,
    "atac.multimapping" : 4,

    "atac.auto_detect_adapter" : true,

    "atac.trim_adapter.cpu" : 2,

    "atac.bowtie2_cpu" : 8,
    "atac.bowtie2_mem_mb" : 16000,

    "atac.filter_cpu" : 2,
    "atac.filter_mem_mb" : 12000,

    "atac.macs2_mem_mb" : 16000,

    "atac.smooth_win" : 73,
    "atac.enable_idr" : true,
    "atac.idr_thresh" : 0.05,

    "atac.enable_xcor" : true,

    "atac.title" : "Sample1",
    "atac.description" : "Sample1"
}
```

What seems to be the problem? Thanks!

**Comment by tanpuekai** [comment]
wow i found your pipeline has a lot of dependencies that were not listed in the landing page:

- cutadapt
- samtools
- python3 with pyhocon
- singularity
- ..

i have to run it and load them with every new error report.

**Comment by akundaje** [comment]
That's not how the installation works. All dependencies are automatically installed. Jin will reply with the correct way to install the pipeline.

**Comment by leepc12** [comment]
What is a full command line used for running a test pipeline?

**Comment by tanpuekai** [comment]
Hi Jin,

This is how I run your pipeline on our institution's HPC (where I am not an admin):

- installation:
 ```
$cd /User1
$git clone https://github.com/ENCODE-DCC/atac-seq-pipeline.git
$ git clone https://github.com/ENCODE-DCC/caper
$ echo "export PATH=\"\$PATH:$PWD/caper/bin\"" >> ~/.bashrc
```
- edit `input.json`:
```
{
    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "https://storage.googleapis.com/encode-pipeline-genome-data/mm10_caper.tsv",
    "atac.fastqs_rep1_R1" : ["/User1/RAWDATA/Sample1_1.fastq.gz"],
    "atac.fastqs_rep1_R2": ["/User1/RAWDATA/Sample1_2.fastq.gz"],
    "atac.paired_end" : true,
    "atac.multimapping" : 4,
    "atac.auto_detect_adapter" : true,
    "atac.trim_adapter.cpu" : 2,
    "atac.bowtie2_cpu" : 8,
    "atac.bowtie2_mem_mb" : 16000,
    "atac.filter_cpu" : 2,
    "atac.filter_mem_mb" : 12000,
    "atac.macs2_mem_mb" : 16000,
    "atac.smooth_win" : 73,
    "atac.enable_idr" : true,
    "atac.idr_thresh" : 0.05,
    "atac.enable_xcor" : true,
    "atac.title" : "Sample1",
    "atac.description" : "Sample1"
}
```

- run pipeline, submitting a script to our HPC queue with these lines:
```
        module load java
        module load samtools
        module load cutadapt
        module load python3
        module load singularity
        module load bowtie2/2.3.4.3
        cd /User1/Project1
        /User1/caper/bin/caper run \
                        -i input.json \
                        --tmp-dir /User1/Project1/encode_pipe/TMPDIR \
                       /User1/atac-seq-pipeline/atac.wdl

        cd /User1
        echo finished
```
And the latest error report is related to Samtools (probably version is not right):
```
atac.bowtie2 RetryableFailure. SHARD_IDX=0, RC=1, JOB_ID=128493, RUN_START=2019-09-18T14:47:25.401Z, RUN_END=2019-09-18T14:48:49.326Z, STDOUT=/home2/groups/paultam/pkchen/peter/atacseq_sept2019/encode_pipe/Q4f/atac/453527b2-3463-4329-a94
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/home2/groups/paultam/pkchen/peter/atacseq_sept2019/encode_pipe/atac-seq-pipeline/src/encode_bowtie2.py", line 214, in <module>
    main()
  File "/home2/groups/paultam/pkchen/peter/atacseq_sept2019/encode_pipe/atac-seq-pipeline/src/encode_bowtie2.py", line 176, in main
    args.out_dir)
  File "/home2/groups/paultam/pkchen/peter/atacseq_sept2019/encode_pipe/atac-seq-pipeline/src/encode_bowtie2.py", line 120, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/home2/groups/paultam/pkchen/peter/atacseq_sept2019/encode_pipe/atac-seq-pipeline/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=128727, PGID=128727, RC=1
STDERR=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]

```

Can you see what seems to be the problem?
How do I get your pipeline to auto install those dependencies with correct versions?

**Comment by leepc12** [comment]
Please do not use your own version of genomic softwares. Use our Conda environment (installer shell script included) or our singularity image to run pipelines. Or try with samtools 1.2.

**Comment by leepc12** [comment]
I saw that you posted an issue on Caper's repo. Add the following to your ~/.bashrc and re-login.
```
export PATH=$PATH:~/.local/bin
```

Check if `caper` works.
```
$ caper
```

And then run this.
```
module load singularity

cd /User1/Project1
/User1/caper/bin/caper run \
                        -i input.json \
                        --tmp-dir /User1/Project1/encode_pipe/TMPDIR \
                       /User1/atac-seq-pipeline/atac.wdl --singularity
```

This command will try to build a local singularity image. It can take 0.5~1 hour.

**Comment by leepc12** [comment]
Closing this due to long inactivity.
