### ISSUE TITLE
only one session at a time

### ISSUE THREAD

**Issue by yinshiyi** [ENCODE-DCC/atac-seq-pipeline#151]
I can run the json file okay.
but when one job is running i cannot get another one running at the same time

[2019-09-25 15:48:07,73] [info] Running with database db.url = jdbc:hsqldb:file:/home/sxx128/.caper/default_file_db;shutdown=false;hsqldb.tx=mvcc
[2019-09-25 15:48:10,94] [error] Failed to instantiate Cromwell System. Shutting down Cromwell.
java.sql.SQLTransientConnectionException: db - Connection is not available, request timed out after 3001ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
        at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
        at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[Caper] run:  1 None None

once the first job is done, i can run the second job no problem again

any fix for this?
thanks

**Comment by leepc12** [comment]
Because your first job was taking the DB file. You can use a different file DB with `--file-db` or `-d` or not using file DB at all `--no-file-db` or `-n`. Call-caching will not work without a file DB.

**Comment by yinshiyi** [comment]
thanks, problem solved

**Comment by yinshiyi** [comment]
@leepc12 a few years later, now the -n option is no longer available. 
Can you explain -db file a bit more, where can i download the db file?
Thank you.

**Comment by leepc12** [comment]
`-n` has been deprecated since Caper runs pipelines without a file DB by default.

If you run `caper server` then define a file DB path (`--db file --file-db DB_ABSOLUTE_PATH`) to store call-caching data for submitted workflows.

If you run `caper run` for a single workflow then define a file DB path. e.g. `--db file --file-db DB_ABSOLUTE_PATH_FOR_WORKFLOW1`, and then if you want to re-run a that workflow find the specific DB path used for the previous run.
