### ISSUE TITLE
ATACQC Failing when Running with Alignment Only Option

### ISSUE THREAD

**Issue by imk1** [ENCODE-DCC/atac-seq-pipeline#157]
**Describe the bug**
I ran the pipeline with the alignment only option ("atac.align_only" : "true"), and the pipeline failed after the reads had been aligned and filtered.  I think that the failure is happening because the ATACQC step is trying to compute the FRIP, but no peaks have been called.  Here is what I saw in the slurm file that made me think this:
Call input and runtime attributes evaluation failed for qc
_report:
Failed to lookup input value for required input frip_overlap_qcs
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1.applyOrElse(JobPreparationActor.scala:65)
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1.applyOrElse(JobPreparationActor.scala:61)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:670)
        at akka.actor.FSM.processEvent$(FSM.scala:667)
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor.processEvent(JobPreparationActor.scala:39)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:664)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:658)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor.aroundReceive(JobPreparationActor.scala:39)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**OS/Platform and dependencies**
- OS or Platform: Centos 6 on linux cluster
- Conda version: 4.7.11
- Caper version: N/A
- If not using Caper
  - Cromwell/dxWDL version: cromwell-34.jar

**Attach error logs**
Caper users:
Caper automatically run troubleshooter for failed workflows. If not and If you ran a Caper server and then get workflow_id of your failed workflow with `caper list`. Or directory use a `metadata.json` file on Cromwell's output directory
```
$ caper troubleshoot [WORKFLOW_ID_OR_METADATA_JSON_FILE]
```

Non-Caper users:
1) Move to your working directory where you ran a pipeline. You should be able to find a directory named `cromwell-executions/` which includes all outputs and logs for debugging.

2) Run the following command line to print all non-empty STDERR outputs. This will be greatly helpful for developers to figure out the problem. Copy-paste its output to the issue page.
```
$ find -name stderr -not -empty | xargs tail -n +1
```
Picked up _JAVA_OPTIONS: -Xms256M -Xmx15000M -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGant/HumanDNase/AMY/cromwell-executions/atac/79ab2430-1a2f-4300-ac40-52db6a94638b/call-ataqc/shard-0/tmp.f7bcb3cf
Picked up _JAVA_OPTIONS: -Xms256M -Xmx15000M -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGant/HumanDNase/AMY/cromwell-executions/atac/79ab2430-1a2f-4300-ac40-52db6a94638b/call-ataqc/shard-0/tmp.f7bcb3cf
[bam_sort_core] merging from 24 files...
Picked up _JAVA_OPTIONS: -Xms256M -Xmx15000M -XX:ParallelGCThreads=1 -Djava.io.tmpdir=/projects/pfenninggroup/machineLearningForComputationalBiology/regElEvoGant/HumanDNase/AMY/cromwell-executions/atac/79ab2430-1a2f-4300-ac40-52db6a94638b/call-ataqc/shard-0/tmp.f7bcb3cf
processing chromosomes

3) (OPTIONAL) Run the following command to collect all logs. For developer's convenience, please add `[ISSUE_ID]` to the name of the tar ball file. This command will generate a tar ball including all debugging information. Post an issue with the tar ball (`.tar.gz`) attached.
```
$ find . -type f -name 'stdout' -or -name 'stderr' -or -name 'script' -or \
-name '*.qc' -or -name '*.txt' -or -name '*.log' -or -name '*.png' -or -name '*.pdf' \
| xargs tar -zcvf debug_[ISSUE_ID].tar.gz
```

**Comment by leepc12** [comment]
We will make a new release soon (today or tomorrow). This is already fixed on the dev branch.

**Comment by imk1** [comment]
Great!  Thanks!

**Comment by leepc12** [comment]
Fixed
