### ISSUE TITLE
Error in pipeline

### ISSUE THREAD

**Issue by simonvh** [ENCODE-DCC/atac-seq-pipeline#17]
I get the following error when running the atac-seq pipeline:

```
[2018-06-27 23:46:30,67] [error] WorkflowManagerActor Workflow 9f195d75-602d-4df8-822d-d4737d7c99c8 failed (during ExecutingWorkflowState): Job atac.xcor:0:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /home/simon/git/atacomate/pipeline/cromwell-executions/atac/9f195d75-602d-4df8-822d-d4737d7c99c8/call-xcor/shard-0/execution/stderr.
 Traceback (most recent call last):
  File "/software/atac-seq-pipeline/src/encode_xcor.py", line 102, in <module>
    main()
  File "/software/atac-seq-pipeline/src/encode_xcor.py", line 91, in main
    ta_subsampled, args.speak, args.nth, args.out_dir)
  File "/software/atac-seq-pipeline/src/encode_xcor.py", line 53, in xcor
    run_shell_cmd(cmd1)
  File "/software/atac-seq-pipeline/src/encode_common.py", line 230, in run_shell_cmd
    os.killpg(pgid, signal.SIGKILL)
OSError: [Errno 3] No such process

Job atac.spr:0:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /home/simon/git/atacomate/pipeline/cromwell-executions/atac/9f195d75-602d-4df8-822d-d4737d7c99c8/call-spr/shard-0/execution/stderr.
 Traceback (most recent call last):
  File "/software/atac-seq-pipeline/src/encode_spr.py", line 130, in <module>
    main()
  File "/software/atac-seq-pipeline/src/encode_spr.py", line 116, in main
    ta_pr1, ta_pr2 = spr_pe(args.ta, args.out_dir)
  File "/software/atac-seq-pipeline/src/encode_spr.py", line 81, in spr_pe
    run_shell_cmd(cmd1)
  File "/software/atac-seq-pipeline/src/encode_common.py", line 230, in run_shell_cmd
    os.killpg(pgid, signal.SIGKILL)
OSError: [Errno 3] No such process

Failed to evaluate job outputs:
Bad output 'macs2.bfilt_npeak': Failed to find index Success(WomInteger(0)) on array:

Success([])

0
Bad output 'macs2.bfilt_npeak_bb': Failed to find index Success(WomInteger(0)) on array:

Success([])

0
Bad output 'macs2.sig_pval': Failed to find index Success(WomInteger(0)) on array:

Success([])

0
Bad output 'macs2.frip_qc': Failed to find index Success(WomInteger(0)) on array:

Success([])

0
cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'macs2.bfilt_npeak': Failed to find index Success(WomInteger(0)) on array:

Success([])

0
Bad output 'macs2.bfilt_npeak_bb': Failed to find index Success(WomInteger(0)) on array:

Success([])

0
Bad output 'macs2.sig_pval': Failed to find index Success(WomInteger(0)) on array:

Success([])

0
Bad output 'macs2.frip_qc': Failed to find index Success(WomInteger(0)) on array:

Success([])

0
	at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$handleExecutionSuccess$1(StandardAsyncExecutionActor.scala:786)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

The command I used:

```
java -jar -Dconfig.file=../../atac-seq-pipeline/backends/backend.conf cromwell-32.jar run ../../atac-seq-pipeline/atac.wdl -i input.json -o ../../atac-seq-pipeline/workflow_opts/docker.json
```

The contents of `input.json`:
```
{
    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "/data/genome_data/hg38/hg38.tsv",
    "atac.fastqs" : [[
	    [
		 "/home/simon/git/atacomate/Supp_GSM2977488_hESC_ATAC/SRR6667571_pass_1.fastq.gz",
		 "/home/simon/git/atacomate/Supp_GSM2977488_hESC_ATAC/SRR6667571_pass_2.fastq.gz"
    ]]],

    "atac.paired_end" : true,
    "atac.multimapping" : 4,

    "atac.trim_adapter.auto_detect_adapter" : true,

    "atac.bowtie2.cpu" : 12,
    "atac.bowtie2.mem_mb" : 16000,
    "atac.bowtie2.time_hr" : 36,

    "atac.filter.cpu" : 2,
    "atac.filter.mem_mb" : 12000,
    "atac.filter.time_hr" : 23,

    "atac.macs2_mem_mb" : 16000,

    "atac.smooth_win" : 73,
    "atac.enable_idr" : true,
    "atac.idr_thresh" : 0.05,

    "atac.qc_report.name" : "GSM2977488",
    "atac.qc_report.desc" : "hESC_ATAC"
}
```

Any ideas? Please let me know if you need more information.

**Comment by leepc12** [comment]
Please post stdout/stderr logs here

`/home/simon/git/atacomate/pipeline/cromwell-executions/atac/9f195d75-602d-4df8-822d-d4737d7c99c8/call-xcor/shard-0/execution/stderr`
`/home/simon/git/atacomate/pipeline/cromwell-executions/atac/9f195d75-602d-4df8-822d-d4737d7c99c8/call-xcor/shard-0/execution/stdout`

**Comment by simonvh** [comment]
Thanks for looking at this, here are the files:

[stdout.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2149313/stdout.txt)
[stderr.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2149314/stderr.txt)

**Comment by leepc12** [comment]
The error log says that subsampled TAG-ALIGN file is empty. Please run the following command on your working directory for more debugging info.
```
$ find -name SRR6667571_pass_1*.tagAlign.gz` | xargs ls -l
```

**Comment by leepc12** [comment]
Closing this due to long inactivity
