### ISSUE TITLE
said 'no module pysam.libchtslib' after 7 hrs running

### ISSUE THREAD

**Issue by tanpuekai** [ENCODE-DCC/atac-seq-pipeline#171]
Hi Jin,

I have given up `singularity`, and have used `conda`  instead.

Re-downloaded `caper` and `conda` and your `atac-seq-pipeline` on Oct 24 and installed according to your instructions.

Ran the pipeline for 7 hrs, and then it broke again, saying this package is not there: `pysam.libchtslib`. (see output below)

 What seems to be the problem?

Thanks!

Best
Chan

```
############################################
python3/3.6.4 is loaded
############################################
##########################  1  ############################
fq1=[/home/user1/project1/RAWDATA/primary_seq/REPLaf_1.fastq.gz]
fq2=[/home/user1/project1/RAWDATA/primary_seq/REPLaf_2.fastq.gz]
fq3=[/home/user1/project1/RAWDATA/primary_seq/REPLbf_1.fastq.gz]
fq4=[/home/user1/project1/RAWDATA/primary_seq/REPLbf_2.fastq.gz]
outdir=[REPL_f]
Workflow 79f07ad1-2bb4-47bc-b819-4ef023ebc3ab transitioned to state Failed
[CaperURI] read from local, src: /home/user1/project1/encode_pipe-oct24/REPL_f/input.json
[CaperURI] read from url, src: https://storage.googleapis.com/encode-pipeline-genome-data/mm10_caper.tsv
[CaperURI] copying from url to local, src: https://storage.googleapis.com/encode-pipeline-genome-data/mm10/mm10_no_alt_analysis_set_ENCODE.fasta.gz
[CaperURI] copying done, target: /home/user1/project1/encode_pipe-oct24/TMPDIR/a3a5d47041f6144861ffa9e9302e10f8/mm10_no_alt_analysis_set_ENCODE.fasta.gz
[CaperURI] copying from url to local, src: https://storage.googleapis.com/encode-pipeline-genome-data/mm10/mm10_no_alt_analysis_set_ENCODE.chrM.fa.gz
[CaperURI] copying done, target: /home/user1/project1/encode_pipe-oct24/TMPDIR/50a6717e701a2b150a642eb51e6c7415/mm10_no_alt_analysis_set_ENCODE.chrM.fa.gz
[CaperURI] copying from url to local, src: https://storage.googleapis.com/encode-pipeline-genome-data/mm10/mm10.blacklist.bed.gz
[CaperURI] copying done, target: /home/user1/project1/encode_pipe-oct24/TMPDIR/a34db28bdbbc4b4434b0b8dbdecf5f19/mm10.blacklist.bed.gz
[CaperURI] copying from url to local, src: https://storage.googleapis.com/encode-pipeline-genome-data/mm10/mm10.chrom.sizes
[CaperURI] copying done, target: /home/user1/project1/encode_pipe-oct24/TMPDIR/8ff81086627eaebba144c5d4ec800d17/mm10.chrom.sizes
[CaperURI] copying from url to local, src: https://storage.googleapis.com/encode-pipeline-genome-data/mm10/bowtie2_index/mm10_no_alt_analysis_set_ENCODE.fasta.tar
[CaperURI] copying done, target: /home/user1/project1/encode_pipe-oct24/TMPDIR/8d7d26e78479ff1ace6de4a9c7d25ee3/mm10_no_alt_analysis_set_ENCODE.fasta.tar
[CaperURI] copying from url to local, src: https://storage.googleapis.com/encode-pipeline-genome-data/mm10/bowtie2_index/mm10_no_alt_analysis_set_ENCODE.chrM.fa.tar
[CaperURI] copying done, target: /home/user1/project1/encode_pipe-oct24/TMPDIR/a26295a6636aea0ea77bf532504c26b1/mm10_no_alt_analysis_set_ENCODE.chrM.fa.tar
[CaperURI] copying from url to local, src: https://storage.googleapis.com/encode-pipeline-genome-data/mm10/bwa_index/mm10_no_alt_analysis_set_ENCODE.fasta.tar
[CaperURI] copying done, target: /home/user1/project1/encode_pipe-oct24/TMPDIR/048bd9c8e1fb0377b93c597780dba598/mm10_no_alt_analysis_set_ENCODE.fasta.tar
[2019-10-24 23:40:49,93] [info] DockerHashActor stopped
[2019-10-24 23:40:49,96] [info] Database closed
[2019-10-24 23:40:49,96] [info] Stream materializer shut down
[2019-10-24 23:40:49,96] [info] WDL HTTP import resolver closed
[CaperURI] write to local, target: /home/user1/project1/encode_pipe-oct24/Q4f/atac/79f07ad1-2bb4-47bc-b819-4ef023ebc3ab/metadata.json, size: 170590
[Caper] troubleshooting 79f07ad1-2bb4-47bc-b819-4ef023ebc3ab ...
Found failures:
[
    {
        "causedBy": [
            {
                "causedBy": [],
                "message": "Job atac.tss_enrich:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            }
        ],
        "message": "Workflow failed"
    }
]

atac.jsd RetryableFailure. SHARD_IDX=-1, RC=1, JOB_ID=2134, RUN_START=2019-10-24T15:19:18.570Z, RUN_END=2019-10-24T15:21:08.447Z, STDOUT=/home/user1/project1/encode_pipe-oct24/Q4f/atac/79f07ad1-2bb4-47bc-b8
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/software/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_jsd.py", line 133, in <module>
    main()
  File "/software/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_jsd.py", line 124, in main
    args.nth, args.out_dir)
  File "/software/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_jsd.py", line 93, in fingerprint
    run_shell_cmd(cmd)
  File "/software/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=2491, PGID=2491, RC=1
STDERR=Traceback (most recent call last):
  File "/software/miniconda3/envs/encode-atac-seq-pipeline/bin/plotFingerprint", line 5, in <module>
    from deeptools.plotFingerprint import main
  File "/software/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/deeptools/plotFingerprint.py", line 18, in <module>
    import deeptools.countReadsPerBin as countR
  File "/software/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/deeptools/countReadsPerBin.py", line 9, in <module>
    import deeptools.utilities
  File "/software/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/deeptools/utilities.py", line 4, in <module>
    from deeptools.bamHandler import openBam
  File "/software/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/deeptools/bamHandler.py", line 2, in <module>
    import pysam
  File "/home/user/.local/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ModuleNotFoundError: No module named 'pysam.libchtslib'
STDOUT=
```

and below are the packages under conda:
```
(encode-atac-seq-pipeline) user@HPC:/home/user$ conda list
# packages in environment at /software/miniconda3/envs/encode-atac-seq-pipeline:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_r-mutex                  1.0.1               anacondar_1    conda-forge
asn1crypto                1.2.0                    py37_0
bedtools                  2.29.0               h6ed99ea_1    bioconda
bioconductor-biocgenerics 0.18.0                 r3.2.2_0    bioconda
bioconductor-biocparallel 1.4.3                  r3.2.2_0    bioconda
bioconductor-biostrings   2.38.4                        0    bioconda
bioconductor-genomeinfodb 1.6.3                         0    bioconda
bioconductor-genomicranges 1.22.4                        0    bioconda
bioconductor-iranges      2.4.8                         0    bioconda
bioconductor-rsamtools    1.22.0                 r3.2.2_1    bioconda
bioconductor-s4vectors    0.8.11                        0    bioconda
bioconductor-xvector      0.10.0                        1    bioconda
bioconductor-zlibbioc     1.16.0                 r3.2.2_1    bioconda
blas                      2.11                   openblas    conda-forge
boost                     1.67.0                   py37_4
bowtie2                   2.3.4.3          py37he860b03_1    bioconda
bwa                       0.7.17               hed695b0_6    bioconda
bz2file                   0.98                     py37_1
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2019.10.16                    0
cairo                     1.14.12              h8948797_3
caper                     0.4.1                      py_0    bioconda
certifi                   2019.9.11                py37_0
cffi                      1.13.0           py37h2e261b9_0
chardet                   3.0.4                 py37_1003
croo                      0.1.8                      py_0    bioconda
cryptography              2.3.1            py37hc365091_0
curl                      7.64.0               h646f8bb_0    conda-forge
cutadapt                  2.5              py37h516909a_0    bioconda
cycler                    0.10.0                   py37_0
dbus                      1.13.6               h746ee38_0
deeptools                 3.3.1                      py_0    bioconda
deeptoolsintervals        0.1.9            py37h516909a_0    bioconda
dill                      0.3.0                    py37_0
dnaio                     0.3              py37h14c3975_1    bioconda
expat                     2.2.6                he6710b0_0
fontconfig                2.13.0               h9420a91_0
freetype                  2.9.1                h8a8886c_1
fribidi                   1.0.5                h7b6447c_0
gawk                      5.0.1                h7b6447c_0
ghostscript               9.18                          1    bioconda
giflib                    5.1.4                h14c3975_1
glib                      2.56.2               hd408876_0
gnuplot                   5.0.3                         4    bioconda
graphite2                 1.3.13               h23475e2_0
gsl                       2.2.1                h0c605f7_3
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
harfbuzz                  1.8.8                hffaf4a1_0
htslib                    1.9                  ha228f0b_7    bioconda
icu                       58.2                 h9c2bf20_1
idna                      2.8                      py37_0
idr                       2.0.4.2          py37hc1659b7_1    bioconda
java-jdk                  8.0.112                       1    bioconda
jinja2                    2.10.3                     py_0
jpeg                      9b                   h024ee3a_2
jsondiff                  1.1.1                    py37_0
kiwisolver                1.1.0            py37he6710b0_0
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libblas                   3.8.0               11_openblas    conda-forge
libboost                  1.67.0               h46d08c1_4
libcblas                  3.8.0               11_openblas    conda-forge
libcurl                   7.64.0               h01ee5af_0    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc                    7.2.0                h69d50b8_2
libgcc-ng                 9.1.0                hdf63c60_0
libgd                     2.2.5                hceca4fd_3
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0
liblapack                 3.8.0               11_openblas    conda-forge
liblapacke                3.8.0               11_openblas    conda-forge
libopenblas               0.3.6                h5a2b251_1
libpng                    1.6.37               hbc83047_0
libssh2                   1.8.0                h9cfc8f7_4
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.0.10               h2733197_2
libuuid                   1.0.3                h1bed415_2
libwebp                   1.0.1                h8e7db2f_0
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.9                hea5a465_1
macs2                     2.2.4            py37h516909a_0    bioconda
markupsafe                1.1.1            py37h7b6447c_0
matplotlib                3.1.1            py37h5429711_0
multiprocess              0.70.9           py37h516909a_0    conda-forge
mysql-connector-c         6.1.11               hf4847fb_0
ncurses                   6.1                  he6710b0_1
nomkl                     3.0                           0
numpy                     1.17.2           py37hf9bf1b6_0
numpy-base                1.17.2           py37h2f8d375_0
openblas                  0.2.20                        8    conda-forge
openjdk                   8.0.112          zulu8.19.0.1_3    conda-forge
openssl                   1.0.2t               h7b6447c_1
pandas                    0.25.2           py37he6710b0_0
pango                     1.42.4               h049681c_0
pcre                      8.43                 he6710b0_0
perl                      5.26.2               h14c3975_0
phantompeakqualtools      1.2.1                         0    bioconda
picard                    2.20.7                        0    bioconda
pigz                      2.4                  h84994c4_0
pip                       19.3.1                   py37_0
pixman                    0.38.0               h7b6447c_0
plotly                    4.1.1                      py_0
preseq                    2.0.3                h26b358d_2    bioconda
py-boost                  1.67.0           py37h04863e7_4
py2bit                    0.3.0            py37h14c3975_2    bioconda
pybedtools                0.8.0            py37he860b03_1    bioconda
pybigwig                  0.3.13           py37h5295baf_2    bioconda
pycparser                 2.19                     py37_0
pyfaidx                   0.5.5.2                    py_1    bioconda
pyhocon                   0.3.51                     py_0    conda-forge
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.4.2                      py_0
pyqt                      5.9.2            py37h05f1152_2
pysam                     0.15.3           py37hda2845c_1    bioconda
pysocks                   1.7.1                    py37_0
python                    3.7.0                h6e4f718_3
python-dateutil           2.8.0                    py37_0
pytz                      2019.3                     py_0
qt                        5.9.6                h8703b6f_2
r                         3.2.2                         0
r-base                    3.2.2                         0
r-bitops                  1.0_6                 r3.2.2_1a
r-boot                    1.3_17                r3.2.2_0a
r-catools                 1.17.1                r3.2.2_2a
r-class                   7.3_14                r3.2.2_0a
r-cluster                 2.0.3                 r3.2.2_0a
r-codetools               0.2_14                r3.2.2_0a
r-foreign                 0.8_66                r3.2.2_0a
r-futile.logger           1.4.1                  r3.2.2_0    bioconda
r-futile.options          1.0.0                  r3.2.2_0    bioconda
r-kernsmooth              2.23_15               r3.2.2_0a
r-lambda.r                1.1.7                  r3.2.2_0    bioconda
r-lattice                 0.20_33               r3.2.2_0a
r-mass                    7.3_45                r3.2.2_0a
r-matrix                  1.2_2                 r3.2.2_0a
r-mgcv                    1.8_9                 r3.2.2_0a
r-nlme                    3.1_122               r3.2.2_0a
r-nnet                    7.3_11                r3.2.2_0a
r-recommended             3.2.2                  r3.2.2_0
r-rpart                   4.1_10                r3.2.2_0a
r-snow                    0.4_1                  r3.2.2_0    bioconda
r-snowfall                1.84_6.1               r3.2.2_0    bioconda
r-spatial                 7.3_11                r3.2.2_0a
r-spp                     1.13                   r3.2.2_0    bioconda
r-survival                2.38_3                r3.2.2_0a
readline                  7.0                  h7b6447c_5
requests                  2.22.0                   py37_0
retrying                  1.3.3                    py37_2
sambamba                  0.6.6                         2    bioconda
samstats                  0.2.1                      py_0    bioconda
samtools                  1.9                 h10a08f8_12    bioconda
scipy                     1.3.1            py37he2b7bc3_0
setuptools                41.4.0                   py37_0
sip                       4.19.8           py37hf484d3e_0
six                       1.12.0                   py37_0
sqlite                    3.30.0               h7b6447c_0
tabix                     0.2.6                ha92aebf_0    bioconda
tbb                       2019.8               hfd86e86_0
tk                        8.6.9             hed695b0_1003    conda-forge
tornado                   6.0.3            py37h7b6447c_0
ucsc-bedclip              357                           1    bioconda
ucsc-bedgraphtobigwig     357                           1    bioconda
ucsc-bedtobigbed          357                           1    bioconda
ucsc-bigwigaverageoverbed 357                           1    bioconda
ucsc-bigwiginfo           357                           1    bioconda
ucsc-fetchchromsizes      357                  h5eb252a_2    bioconda
ucsc-twobittofa           357                           1    bioconda
ucsc-wigtobigwig          357                           1    bioconda
urllib3                   1.24.2                   py37_0
wget                      1.19.5               h1ad7b7a_0
wheel                     0.33.6                   py37_0
xopen                     0.7.3                      py_0    bioconda
xz                        5.2.4                h14c3975_4
zlib                      1.2.11               h7b6447c_3
zstd                      1.3.7                h0b5b093_0

```

**Comment by leepc12** [comment]
Try this one after activating the environment for debugging.
```
(encode-atac-seq-pipeline) leepc12@kadru:~$ python3
Python 3.7.0 (default, Oct  9 2018, 10:31:47)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> pysam.__file__
'/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/pysam/__init__.py'
>>> import pysam.libchtslib
>>> pysam.libchtslib.__file__
'/users/leepc12/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/pysam/libchtslib.cpython-37m-x86_64-linux-gnu.so'
>>>
```

`pysam.libchtslib.__file__` should point to a file on the env's lib directory.

**Comment by tanpuekai** [comment]
Hi Jin,

Yes it does point to the env's folder (see below). 
But what should I do next to let the pipeline continue running?

Best
Peikai

```
user@hpc:/home/user/project1/encode_pipe-oct24$ source activate encode-atac-seq-pipeline
(encode-atac-seq-pipeline) user@hpc:/home/user/project1/encode_pipe-oct24$ python
Python 3.7.0 (default, Oct  9 2018, 10:31:47)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> pysam.__file__
'/software/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/pysam/__init__.py'
>>> import pysam.libchtslib
>>> pysam.libchtslib.__file__
'/software/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/pysam/libchtslib.cpython-37m-x86_64-linux-gnu.so'
>>>
```

**Comment by leepc12** [comment]
Looking at your error log, I found that it's trying to load from your locally installed `pysam` (`/home/pkchen/.local/lib/python3.6/site-packages/pysam`). I think pipeline's Conda environment was not installed correctly?
```
  File "/software/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/deeptools/bamHandler.py", line 2, in <module>
    import pysam
  File "/home/pkchen/.local/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
```

You can try this for debugging first. If it's not `True` then pipeline's env was not installed correctly.
```
$ echo $PYTHONNOUSERSITE
```

(NOT RECOMMENDED) You can also remove your locally install pysam and try again.

**Comment by tanpuekai** [comment]
Hi Jin, 

Thanks a lot.
Problem solved now.

It was because I was not aware that your conda env includes python3.7.0, and so I performed `module load python3/3.6.4` in our HPC, which override your python3.7.0, and thus it tried to call packages from local lib path.

I removed that line, and the pipeline is running. Hope that solve the problem.


Best
Chan

**Comment by leepc12** [comment]
You should not `module load` any external python3. All dependencies including python3 is already included in the Conda environment `encode-atac-seq-pipeline`.
```
$ source activate encode-atac-seq-pipeline  # or "conda activate"
$ echo $PYTHONNOUSERSITE
$ which python3
$ which python
```

**Comment by tanpuekai** [comment]
Thanks Jin,

running for 14 hours now after I performed `export PYTHONPATH=""` before activating the conda env. Pipeline still running, not yet finished, seems quite slow (compared with prev DNASE-pipeline).

in the old `dnase-pipeline`, one can check the real-time progress on the web, is it available in this pipeline too?

Chan
