### ISSUE TITLE
croo fails on pipeline output

### ISSUE THREAD

**Issue by ro-joshi** [ENCODE-DCC/atac-seq-pipeline#177]
**OS/Platform and dependencies**
- OS or Platform: SCG cluster
- Conda version: conda 4.7.12
- Caper version 0.5.1

**Describe the bug**
After successfully running the atac-seq-pipeline, `croo metadata.json` (also `croo metadata.json --out-def-json ~/repos/atac-seq-pipeline/atac.croo.json`) fails with:

```
[CaperURI] symlinking from local to local, src: /N/projects/curtis/rohan/processed-TCGA-ATAC/atac/278c3788-f103-4cf1-8f13-c96f669cbc42/call-jsd/execution/glob-fc36854b6867c1581ab159b09dd7e2f4/ENCFF341MYG.subsampled.400.trim.merged.nodup.no_chrM_MT.jsd_plot.png
[CaperURI] symlinking skipped, target: /N/projects/curtis/rohan/processed-TCGA-ATAC/atac/278c3788-f103-4cf1-8f13-c96f669cbc42/qc/ENCFF341MYG.subsampled.400.trim.merged.nodup.no_chrM_MT.jsd_plot.png
Traceback (most recent call last):
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/bin/croo", line 13, in <module>
    main()
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/croo/croo.py", line 240, in main
    co.organize_output()
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/croo/croo.py", line 112, in organize_output
    target_url = CaperURI(target_uri).get_url()
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 285, in get_url
    return self.get_file(uri_type=URI_URL, no_copy=True)
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 290, in get_file
    return self.copy(target_uri_type=uri_type, no_copy=no_copy)
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 324, in copy
    path = self.__get_url()
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 668, in __get_url
    path=self._uri))
NotImplementedError: Cannot find a mapping from path to URL in MAPPING_PATH_TO_URL for path /N/projects/curtis/rohan/processed-TCGA-ATAC/atac/278c3788-f103-4cf1-8f13-c96f669cbc42/qc/ENCFF341MYG.subsampled.400.trim.merged.nodup.no_chrM_MT.jsd_plot.png
```

**Comment by leepc12** [comment]
It looks like your caper is still at 0.5.0 (buggy). There can be multiple installation of capers if you have activated a Conda environment. Please check the version (after activating Conda environment if you use Conda).
```
$ caper -v
```

**Comment by ro-joshi** [comment]
Thanks Jin, here are the versions:

```
(encode-atac-seq-pipeline) rojoshi@cbp-hn1 ~/repos $ croo --version
0.2.0
(encode-atac-seq-pipeline) rojoshi@cbp-hn1 ~/repos $ caper -v
0.5.1
```

**Comment by leepc12** [comment]
This is Croo's issue. Can you close this and re-post to Croo's issue page?
