### ISSUE TITLE
Quick pipeline error: Failed to instantiate Cromwell System. Shutting down Cromwell

### ISSUE THREAD

**Issue by grrompala** [ENCODE-DCC/atac-seq-pipeline#183]
Hi,

Pipeline fails immediately, giving following error: 

[error] Failed to instantiate Cromwell System. Shutting down Cromwell.
java.sql.SQLTransientConnectionException: db - Connection is not available, request timed out after 30001ms.

Tried setting up caper init for a local system after getting this error in case that was the issue, and still got same error. For reference, I am running this on an HPC BODE so not sure if something specific to that should be accounted for.

Any help would be great (hopefully it's something easy...)

**Whole workflow pasted below**

(encode-atac-seq-pipeline) [rompag01@li03c01 atac-seq-pipeline]$ caper run atac.wdl -i atac.json
[CaperURI] read from local, src: /sc/hydra/scratch/rompag01/atac-seq-pipeline/atac.json
[CaperURI] copying from url to local, src: https://github.com/broadinstitute/cromwell/releases/download/42/cromwell-42.jar
[CaperURI] file already exists. skip downloading and ignore HTTP_ERR 416
[CaperURI] copying skipped, target: /hpc/users/rompag01/.caper/cromwell_jar/cromwell-42.jar
[CaperURI] copying from url to local, src: https://github.com/broadinstitute/cromwell/releases/download/42/womtool-42.jar
[CaperURI] file already exists. skip downloading and ignore HTTP_ERR 416
[CaperURI] copying skipped, target: /hpc/users/rompag01/.caper/womtool_jar/womtool-42.jar
[Caper] Validating WDL/input JSON with womtool...
Success!
[Caper] cmd:  ['java', '-Xmx2G', '-XX:ParallelGCThreads=1', '-DLOG_LEVEL=INFO', '-jar', '-Dconfig.file=/sc/hydra/scratch/rompag01/atac/20191110_153758_153021/backend.conf', '/hpc/users/rompag01/.caper/cromwell_jar/cromwell-42.jar', 'run', '/sc/hydra/scratch/rompag01/atac-seq-pipeline/atac.wdl', '-i', '/sc/hydra/scratch/rompag01/atac-seq-pipeline/atac.json', '-o', '/sc/hydra/scratch/rompag01/atac/20191110_153758_153021/workflow_opts.json', '-l', '/sc/hydra/scratch/rompag01/atac/20191110_153758_153021/labels.json', '-m', '/sc/hydra/scratch/rompag01/atac/20191110_153758_153021/metadata.json']
[2019-11-10 15:39:03,01] [info] Running with database db.url = jdbc:hsqldb:file:./caper_file_db.atac;shutdown=false;hsqldb.tx=mvcc;hsqldb.lob_compressed=true
[2019-11-10 15:39:33,27] [error] Failed to instantiate Cromwell System. Shutting down Cromwell.
java.sql.SQLTransientConnectionException: db - Connection is not available, request timed out after 30001ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
        at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
        at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[Caper] run:  1 None None
(encode-atac-seq-pipeline) [rompag01@li03c01 atac-seq-pipeline]$ Failed to instantiate Cromwell System. Shutting down Cromwell

**Comment by leepc12** [comment]
Did you run multiple `caper run` commands at the same time or your previous `caper run` didn't die gracefully? Your file DB (files starting with `./caper_file_db.atac*`) seems to be locked. Cromwell's file DB does not allow multiple connections.

Also, there was an update for Caper (>=0.6.0) about such file DB. Caper no longer uses a file DB as a default metadata DB since it causes too many problems (huge/corrupted DB file `.lobs` and memory leak). We recommend to use a MySQL server instead. Caper provides a convenient shell script to run MySQL on docker/singularity.

If you don't have docker/singularity on your system, you may need to keep using a file DB (set DB type as file `db=file` in conf), which only allows a single connection, at your own risk. and then define file DB's name explicitly  (e.g. `--file-db db_for_atac1`).

Update your Caper (`pip install caper==0.6.0`)  and add the following to your `~/.caper/default.conf` file. 

1) `db=in-memory`: This will disable a file DB and you will run pipelines without storing metadata (hence, no call-caching).

2) `db=file` to keep using a file DB.

**Comment by leepc12** [comment]
Closing this due to long inactivity.
