### ISSUE TITLE
Croo error: AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#233]
When I run Croo on metadata.json output by the test ATAC-seq workflow, I get the following error:
```
Traceback (most recent call last):
  File "/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/bin/croo", line 13, in <module>
    main()
  File "/scg/apps/legacy/python/3.4.5/lib/python3.4/site-packages/croo/croo.py", line 211, in main
    co.organize_output()
  File "/scg/apps/legacy/python/3.4.5/lib/python3.4/site-packages/croo/croo.py", line 76, in organize_output
    path = out_var.get('path')
AttributeError: 'NoneType' object has no attribute 'get'
```
The conda environment is loaded:
```
(encode-atac-seq-pipeline) $ which python
/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/bin/python
(encode-atac-seq-pipeline) $ which python2
/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/bin/python2
(encode-atac-seq-pipeline) $ which python3
/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/bin/python3
(encode-atac-seq-pipeline) $ which croo
/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/bin/croo
```
**OS/Platform**
- OS/Platform: Stanford SCG
- Conda version: 4.7.12
- Pipeline version: 1.7.0

**Comment by leepc12** [comment]
Your croo looks out-dated. Please update your Croo and try again.
```
$ pip install croo --upgrade
```

**Comment by nicolerg** [comment]
I get this error:
```
Traceback (most recent call last):
  File "/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
```
I just uninstalled and reinstalled the conda environment this morning.

**Comment by leepc12** [comment]
Specify latest Croo version.
```
$ pip install croo==0.3.4
```

Or uninstall from Conda env, and re-install with pip
```
$ source activate encode-atac-seq-pipeline
$ conda uninstall croo
$ pip install croo==0.3.4
```

**Comment by nicolerg** [comment]
Great, thank you very much!
