### ISSUE TITLE
Call-filter fails

### ISSUE THREAD

**Issue by rleylek** [ENCODE-DCC/atac-seq-pipeline#244]
**Describe the bug**
I keep hitting the same error at the end of the call-filter step while running the pipeline on Sherlock. The Sherlock example runs perfectly, and if I start from a nodup_bam, everything works fine.

**OS/Platform**
- OS/Platform: Stanford Sherlock
- Conda version: conda 4.8.2
- Pipeline version: v1.7.0

- Caper version: 0.6.4

**Caper configuration file**
backend=slurm
slurm-partition=normal

tmp-dir=/home/groups/jidoyaga/rleylek/atac-seq-pipeline/temporary

**Input JSON file**
{
   "atac.pipeline_type" : "atac",
   "atac.genome_tsv" : "/home/groups/cherry/encode/pipeline_genome_data/hg19_sherlock.tsv",
    "atac.bams" : [
        "/home/groups/jidoyaga/rleylek/atac-seq-pipeline/output/Calderon/atac/bf321c40-62ca-4038-9ee0-b48d329a9d63/call-align/shard-0/execution/SRR7650729_1.fastq.trim.bam" ],

    "atac.paired_end" : true,
    "atac.enable_gc_bias" : false,
    "atac.enable_xcor" : true,
    "atac.auto_detect_adapter" : true,

    "atac.call_peak_mem_mb" : 4000,
    "atac.macs2_signal_track_mem_mb" : 4000,
    "atac.jsd_mem_mb" : 4000,
    "atac.filter_mem_mb" : 4000,

    "atac.filter_cpu" : 2,
    "atac.filter_time_hr" : 6,
    "atac.spr_mem_mb" : 4000,
    "atac.jsd_mem_mb" : 4000,
    "atac.bam2ta_mem_mb" : 4000,
    "atac.xcor_mem_mb" : 4000,
    "atac.fraglen_stat_picard_java_heap" : "4G",
    "atac.gc_bias_picard_java_heap" : "4G",
    "atac.title" : "Calderon",
    "atac.description" : "1001 Bulk B U"
}

**Error log**
Traceback (most recent call last):
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 364, in <module>
    main()
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 345, in main
    args.out_dir)
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 274, in pbc_qc_pe
    run_shell_cmd(cmd3)
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=4068, PGID=4068, RC=1
STDERR=
STDOUT=

```
$ caper debug [WORKFLOW_ID_OR_METADATA_JSON_FILE]
```
[Caper] troubleshooting 10482031-60a1-46c7-b4c1-25d6d3b3bfeb ...
Found failures:
[
    {
        "causedBy": [
            {
                "causedBy": [],
                "message": "Job atac.filter_no_dedup:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            },
            {
                "message": "Job atac.filter:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.",
                "causedBy": []
            }
        ],
        "message": "Workflow failed"
    }
]

atac.filter_no_dedup RetryableFailure. SHARD_IDX=0, RC=1, JOB_ID=64936789, RUN_START=2020-04-05T20:43:43.030Z, RUN_END=2020-04-05T21:27:43.988Z, STDOUT=/home/groups/jidoyaga/rleylek/atac-seq-pipeline/output/Calderon/test/atac/10482031-60a1-46c7-b4c1-25d6d3b3bfeb/call-filter_no_dedup/shard-0/execution/stdout, STDERR=/home/groups/jidoyaga/rleylek/atac-seq-pipeline/output/Calderon/test/atac/10482031-60a1-46c7-b4c1-25d6d3b3bfeb/call-filter_no_dedup/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 364, in <module>
    main()
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 345, in main
    args.out_dir)
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 274, in pbc_qc_pe
    run_shell_cmd(cmd3)
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=4195, PGID=4195, RC=1
STDERR=
STDOUT=

atac.filter_no_dedup Failed. SHARD_IDX=0, RC=1, JOB_ID=64937634, RUN_START=2020-04-05T21:27:45.022Z, RUN_END=2020-04-05T22:04:51.362Z, STDOUT=/home/groups/jidoyaga/rleylek/atac-seq-pipeline/output/Calderon/test/atac/10482031-60a1-46c7-b4c1-25d6d3b3bfeb/call-filter_no_dedup/shard-0/attempt-2/execution/stdout, STDERR=/home/groups/jidoyaga/rleylek/atac-seq-pipeline/output/Calderon/test/atac/10482031-60a1-46c7-b4c1-25d6d3b3bfeb/call-filter_no_dedup/shard-0/attempt-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 364, in <module>
    main()
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 345, in main
    args.out_dir)
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 274, in pbc_qc_pe
    run_shell_cmd(cmd3)
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=27335, PGID=27335, RC=1
STDERR=
STDOUT=

atac.filter RetryableFailure. SHARD_IDX=0, RC=1, JOB_ID=64936787, RUN_START=2020-04-05T20:43:41.033Z, RUN_END=2020-04-05T21:25:58.997Z, STDOUT=/home/groups/jidoyaga/rleylek/atac-seq-pipeline/output/Calderon/test/atac/10482031-60a1-46c7-b4c1-25d6d3b3bfeb/call-filter/shard-0/execution/stdout, STDERR=/home/groups/jidoyaga/rleylek/atac-seq-pipeline/output/Calderon/test/atac/10482031-60a1-46c7-b4c1-25d6d3b3bfeb/call-filter/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 364, in <module>
    main()
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 345, in main
    args.out_dir)
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 274, in pbc_qc_pe
    run_shell_cmd(cmd3)
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=4068, PGID=4068, RC=1
STDERR=
STDOUT=

atac.filter Failed. SHARD_IDX=0, RC=1, JOB_ID=64937616, RUN_START=2020-04-05T21:26:01.041Z, RUN_END=2020-04-05T22:07:30.669Z, STDOUT=/home/groups/jidoyaga/rleylek/atac-seq-pipeline/output/Calderon/test/atac/10482031-60a1-46c7-b4c1-25d6d3b3bfeb/call-filter/shard-0/attempt-2/execution/stdout, STDERR=/home/groups/jidoyaga/rleylek/atac-seq-pipeline/output/Calderon/test/atac/10482031-60a1-46c7-b4c1-25d6d3b3bfeb/call-filter/shard-0/attempt-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 364, in <module>
    main()
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 345, in main
    args.out_dir)
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 274, in pbc_qc_pe
    run_shell_cmd(cmd3)
  File "/home/groups/jidoyaga/rleylek/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=27138, PGID=27138, RC=1
STDERR=
STDOUT=

**Comment by leepc12** [comment]
Resources for `filter` task are too small. Try with defaults values by removing those from input JSON.
```
"atac.filter_mem_mb" : 4000,
"atac.filter_time_hr" : 6,
```

**Comment by rleylek** [comment]
Hi Jin, with the default values it fails when starting atac_filter with the error "Requested node configuration is not available". I tried with:

"atac.filter_cpu" : 4,
"atac.filter_mem_mb" : 20000,

and it still hits the same error.

**Comment by leepc12** [comment]
Sherlock `normal` partition does not allow such big mem jobs.
Use other partition with bigger memory. Or tweak filter_cpu and filter_mem_mb to make them work with `normal` partition.

**Comment by rleylek** [comment]
I'm waiting for it to run on the bigmem partition and also trying different parameters on the normal partition. I will let you know if I find a combination that works, but so far I've gotten the same problem in call-filter.

It just seems odd that it gets through the alignment step fine, and the default there calls for 20000mb. I also tried inputting a smaller bam file (just chr22) and that also fails. Lastly, while it's running, I can see it creating all of the temp files for the filt.bam, so it seems to be somewhere after that. Please let me know if there's anything else you can think to try!

**Comment by leepc12** [comment]
Check if you ran pipeline on slow/unstable storage like `$OAK`. Can you make a tar ball of logs (`stdout`, `stderr`) on your output directory for failed workflows.

**Comment by rleylek** [comment]
I don't think we have access to OAK so that shouldn't be it. I'm attaching two tar balls, one from when I started from fastqs, and one that started from the bam (using different parameters for filter_cpu and filter_mem_mb). Thank you!

[logs_from_bam.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/4441518/logs_from_bam.tar.gz)
[logs_from_fastq.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/4441519/logs_from_fastq.tar.gz)

**Comment by leepc12** [comment]
Failed at this line.
```
[2020-04-06 16:13:34,112 INFO] run_shell_cmd: PID=179655, PGID=179655, CMD=bedtools bamtobed -bedpe -i SRR7650729_1.fastq.trim.dupmark.nmsrt.bam | awk 'BEGIN{OFS="\t"}{print $1,$2,$4,$6,$9,$10}' | grep -v "^chrM\s" | sort | uniq -c | awk 'BEGIN{mt=0;m0=0;m1=0;m2=0} ($1==1){m1=m1+1} ($1==2){m2=m2+1} {m0=m0+1} {mt=mt+$1} END{m1_m2=-1.0; if(m2>0) m1_m2=m1/m2; m0_mt=0; if (mt>0) m0_mt=m0/mt; m1_m0=0; if (m0>0) m1_m0=m1/m0; printf "%d\t%d\t%d\t%d\t%f\t%f\t%f\n",mt,m0,m1,m2,m0_mt,m1_m0,m1_m2}' > SRR7650729_1.fastq.trim.dupmark.lib_complexity.qc
```

I think it ran out of memory in `sort` or `bedtools bamtobed`. Increase memory for `filter` task.

**Comment by leepc12** [comment]
Closing due to long inactivity.
