### ISSUE TITLE
Job atac.align_mito Failed

### ISSUE THREAD

**Issue by yingqingdeng** [ENCODE-DCC/atac-seq-pipeline#254]
Describe the bug
Recevied an erro at the atac.align_mito step.  

OS/Platform: slurm
Conda version:anconda3
Pipeline version: v1.7.0
Caper version: 0.6.4

Input json file
{
    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "/cluster/home/dengyingqing/encode/atac-seq-pipeline-genome/hg38.tsv",
    "atac.fastqs_rep1_R1" : [
        "/cluster/home/dengyingqing/atac/X101SC19112405-Z02-J001-B2/CleanFq/A14C_A_clean_1.fq.gz"
    ],
    "atac.fastqs_rep1_R2" : [
        "/cluster/home/dengyingqing/atac/X101SC19112405-Z02-J001-B2/CleanFq/A14C_A_clean_2.fq.gz"
    ],
    "atac.fastqs_rep2_R1" : [
        "/cluster/home/dengyingqing/atac/X101SC19112405-Z02-J001-B2/CleanFq/A26C_A_clean_1.fq.gz"
    ],
    "atac.fastqs_rep2_R2" : [
        "/cluster/home/dengyingqing/atac/X101SC19112405-Z02-J001-B2/CleanFq/A26C_A_clean_2.fq.gz"
    ],

    "atac.paired_end" : true,
    "atac.auto_detect_adapter" : true,
    "atac.title" : "test",
    "atac.description" : "ATAC-seq on primary keratinocytes in day 0.0 of differentiation"
}

Error log
Found failures:
[
    {
        "message": "Workflow failed",
        "causedBy": [
            {
                "message": "Job atac.align_mito:1:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.",
                "causedBy": []
            }
        ]
    }
]

atac.align_mito RetryableFailure. SHARD_IDX=0, RC=1, JOB_ID=19559, RUN_START=2020-04-17T07:17:35.463Z, RUN_END=2020-04-18T13:58:20.086Z, STDOUT=/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-0/execution/stdout, STDERR=/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 192, in <module>
    main()
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 166, in main
    args.out_dir)
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 101, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 308, in run_shell_cmd
    stdout, stderr = p.communicate(cmd)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 1721, in _communicate
    self.stdout.errors)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 816, in _translate_newlines
    data = data.decode(encoding, errors)
MemoryError
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-0/execution/*.bam’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-0/execution/*.bai’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-0/execution/*.samstats.qc’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-0/execution/non_mito/*.samstats.qc’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-0/execution/*.read_length.txt’: No such file or directory

atac.align_mito RetryableFailure. SHARD_IDX=1, RC=1, JOB_ID=19558, RUN_START=2020-04-17T07:17:33.469Z, RUN_END=2020-04-18T08:09:55.088Z, STDOUT=/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/execution/stdout, STDERR=/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 192, in <module>
    main()
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 166, in main
    args.out_dir)
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 101, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 308, in run_shell_cmd
    stdout, stderr = p.communicate(cmd)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 1721, in _communicate
    self.stdout.errors)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 816, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/execution/*.bam’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/execution/*.bai’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/execution/*.samstats.qc’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/execution/non_mito/*.samstats.qc’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/execution/*.read_length.txt’: No such file or directory

atac.align_mito Failed. SHARD_IDX=1, RC=1, JOB_ID=19577, RUN_START=2020-04-18T08:09:55.456Z, RUN_END=2020-04-18T09:45:38.408Z, STDOUT=/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/attempt-2/execution/stdout, STDERR=/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/attempt-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 192, in <module>
    main()
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 166, in main
    args.out_dir)
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 101, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 308, in run_shell_cmd
    stdout, stderr = p.communicate(cmd)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 1721, in _communicate
    self.stdout.errors)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 816, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/attempt-2/execution/*.bam’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/attempt-2/execution/*.bai’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/attempt-2/execution/*.samstats.qc’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/attempt-2/execution/non_mito/*.samstats.qc’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align_mito/shard-1/attempt-2/execution/*.read_length.txt’: No such file or directory

atac.align RetryableFailure. SHARD_IDX=0, RC=1, JOB_ID=19556, RUN_START=2020-04-17T07:17:27.470Z, RUN_END=2020-04-19T03:53:55.085Z, STDOUT=/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-0/execution/stdout, STDERR=/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 192, in <module>
    main()
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 166, in main
    args.out_dir)
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 101, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 308, in run_shell_cmd
    stdout, stderr = p.communicate(cmd)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 1721, in _communicate
    self.stdout.errors)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 816, in _translate_newlines
    data = data.decode(encoding, errors)
MemoryError
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-0/execution/*.bam’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-0/execution/*.bai’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-0/execution/*.samstats.qc’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-0/execution/non_mito/*.samstats.qc’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-0/execution/*.read_length.txt’: No such file or directory

atac.align RetryableFailure. SHARD_IDX=1, RC=1, JOB_ID=19557, RUN_START=2020-04-17T07:17:31.445Z, RUN_END=2020-04-18T20:01:45.087Z, STDOUT=/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-1/execution/stdout, STDERR=/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-1/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 192, in <module>
    main()
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 166, in main
    args.out_dir)
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 101, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 308, in run_shell_cmd
    stdout, stderr = p.communicate(cmd)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 1721, in _communicate
    self.stdout.errors)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 816, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-1/execution/*.bam’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-1/execution/*.bai’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-1/execution/*.samstats.qc’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-1/execution/non_mito/*.samstats.qc’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/call-align/shard-1/execution/*.read_length.txt’: No such file or directory

[Caper] run:  1 8ef9d43e-445c-4f0b-8cff-a03b2875bac3 /cluster/home/dengyingqing/encode/atac/8ef9d43e-445c-4f0b-8cff-a03b2875bac3/metadata.json

Can you please take a look at my JSON file and help me solve the problem?
Thanks for your help

**Comment by leepc12** [comment]
Did you run it on your laptop?

**Comment by yingqingdeng** [comment]
I ran it on the cluster and it's based on SLURM. Besides, my fastq files are relatively big in size. Could this be the memory issue?

**Comment by leepc12** [comment]
Check if `backend=slurm` in your conf `~/.caper/default.conf`.
Yes, increase memory `atac.align_mem_mb` in your input JSON.
Find default value from input documentation and try doubling it.

**Comment by yingqingdeng** [comment]
Thank for your reply, I have checked my conf : backend=slurm. Also, I increase memory atac.align_mem_mb to 128000 and rerun the task. However, I come into the same troubleshotting.
my stderr file : 
Traceback (most recent call last):
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 192, in <module>
    main()
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 166, in main
    args.out_dir)
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_task_bowtie2.py", line 101, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/cluster/apps/anaconda3/201907/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 308, in run_shell_cmd
    stdout, stderr = p.communicate(cmd)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 1721, in _communicate
    self.stdout.errors)
  File "/cluster/apps/anaconda3/201907/lib/python3.7/subprocess.py", line 816, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
ln: failed to access ‘/cluster/home/dengyingqing/atac/brencode/atac/d79e9549-44c2-4c27-a753-ed64ada63525/call-align/shard-1/execution/*.bam’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/atac/brencode/atac/d79e9549-44c2-4c27-a753-ed64ada63525/call-align/shard-1/execution/*.bai’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/atac/brencode/atac/d79e9549-44c2-4c27-a753-ed64ada63525/call-align/shard-1/execution/*.samstats.qc’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/atac/brencode/atac/d79e9549-44c2-4c27-a753-ed64ada63525/call-align/shard-1/execution/non_mito/*.samstats.qc’: No such file or directory
ln: failed to access ‘/cluster/home/dengyingqing/atac/brencode/atac/d79e9549-44c2-4c27-a753-ed64ada63525/call-align/shard-1/execution/*.read_length.txt’: No such file or directory

**Comment by leepc12** [comment]
Can you uninstall pipeline's Conda env and reinstall it?
Deactivate your conda env before doing this.
```bash
$bash scripts/uninstall_conda_env.sh
$bash scripts/install_conda_env.sh
```

**Comment by leepc12** [comment]
Closing due to long inactivity.
