### ISSUE TITLE
Caper fails to launch pipeline

### ISSUE THREAD

**Issue by kdemuren** [ENCODE-DCC/atac-seq-pipeline#272]
Exception thrown on pipeline launch, seems to be a Caper problem (get same output when running caper without input JSON). Running on SLURM cluster with pipeline v1.8.0.

**Caper configuration file**
```
backend=slurm

# define one of the followings (or both) according to your
# cluster's SLURM configuration.
slurm-partition=normal
slurm-account=

# Hashing strategy for call-caching (3 choices)
# This parameter is for local (local/slurm/sge/pbs) backend only.
# This is important for call-caching,
# which means re-using outputs from previous/failed workflows.
# Cache will miss if different strategy is used.
# "file" method has been default for all old versions of Caper<1.0.
# "path+modtime" is a new default for Caper>=1.0,
#   file: use md5sum hash (slow).
#   path: use path.
#   path+modtime: use path and modification time.
local-hash-strat=path+modtime

# Local directory for localized files and Cromwell's intermediate files
# If not defined, Caper will make .caper_tmp/ on local-out-dir or CWD.
# /tmp is not recommended here since Caper store all localized data files
# on this directory (e.g. input FASTQs defined as URLs in input JSON).
local-loc-dir=/home/kdemuren/data/tmp-caper/

cromwell=/home/kdemuren/.caper/cromwell_jar/cromwell-52.jar
womtool=/home/kdemuren/.caper/womtool_jar/womtool-52.jar
```
**Stdout/error from pipeline run**
```
2020-08-22 18:05:03,673|caper.caper_base|INFO| Creating a timestamped temporary directory. /home/kdemuren/data/tmp-caper/atac/20200822_180503_672685
2020-08-22 18:05:03,673|caper.caper_runner|INFO| Localizing files on work_dir. /home/kdemuren/data/tmp-caper/atac/20200822_180503_672685
2020-08-22 18:05:05,158|caper.cromwell|INFO| Validating WDL/inputs/imports with Womtool...
2020-08-22 18:05:10,364|caper.cromwell|INFO| Womtool validation passed.
2020-08-22 18:05:10,365|caper.caper_runner|INFO| launching run: wdl=/net/bmc-pub14/data/boyer/users/kdemuren/atac-seq-pipeline/atac.wdl, inputs=/net/bmc-pub14/data/boyer/users/kdemuren/CM_ATAC_DMSO.json, backend_conf=/home/kdemuren/data/tmp-caper/atac/20200822_180503_672685/backend.conf
2020-08-22 18:05:27,113|caper.cromwell_workflow_monitor|INFO| Workflow: id=4238d010-93c3-40f2-b315-ab71b795acfc, status=Submitted
2020-08-22 18:05:27,175|caper.cromwell_workflow_monitor|INFO| Workflow: id=4238d010-93c3-40f2-b315-ab71b795acfc, status=Running
2020-08-22 18:05:30,631|caper.cromwell_workflow_monitor|INFO| Workflow: id=4238d010-93c3-40f2-b315-ab71b795acfc, status=Failed
2020-08-22 18:05:37,153|caper.cromwell_metadata|WARNING| Failed to write metadata file. workflowRoot not found. wf_id=4238d010-93c3-40f2-b315-ab71b795acfc
2020-08-22 18:05:37,153|caper.cromwell|INFO| Workflow failed. Auto-troubleshooting...
2020-08-22 18:05:37,153|caper.nb_subproc_thread|ERROR| Subprocess failed. returncode=1
2020-08-22 18:05:37,153|caper.cli|ERROR| Check stdout/stderr in /net/bmc-pub14/data/boyer/users/kdemuren/output-atac/CM_DMSO/cromwell.out
* Started troubleshooting workflow: id=4238d010-93c3-40f2-b315-ab71b795acfc, status=Failed
* Found failures JSON object.
[
    {
        "causedBy": [
            {
                "message": "Task raise_exception has an invalid runtime attribute memory = !! NOT FOUND !!",
                "causedBy": []
            }
        ],
        "message": "Runtime validation failed"
    }
]
* Recursively finding failures in calls (tasks)...
```
**cromwell.out**
```
2020-08-22 18:05:12,893  INFO  - Running with database db.url = jdbc:hsqldb:mem:ceaa239f-a238-454e-b534-c2601dc92129;shutdown=false;hsqldb.tx=mvcc
2020-08-22 18:05:25,396  INFO  - Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
2020-08-22 18:05:25,422  INFO  - [RenameWorkflowOptionsInMetadata] 100%
2020-08-22 18:05:25,583  INFO  - Running with database db.url = jdbc:hsqldb:mem:aea05e05-7f06-4502-bd4c-8e5edebef296;shutdown=false;hsqldb.tx=mvcc
2020-08-22 18:05:26,180  INFO  - Slf4jLogger started
2020-08-22 18:05:26,424 cromwell-system-akka.dispatchers.engine-dispatcher-5 INFO  - Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-28ec5ec",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "failureShutdownDuration" : "5 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
2020-08-22 18:05:26,475 cromwell-system-akka.dispatchers.service-dispatcher-12 INFO  - Metadata summary refreshing every 1 second.
2020-08-22 18:05:26,504 cromwell-system-akka.dispatchers.service-dispatcher-8 INFO  - WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
2020-08-22 18:05:26,508 cromwell-system-akka.actor.default-dispatcher-4 INFO  - KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
2020-08-22 18:05:26,526 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
2020-08-22 18:05:26,527  WARN  - 'docker.hash-lookup.gcr-api-queries-per-100-seconds' is being deprecated, use 'docker.hash-lookup.gcr.throttle' instead (see reference.conf)
2020-08-22 18:05:27,000 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - JobExecutionTokenDispenser - Distribution rate: 1 per 2 seconds.
2020-08-22 18:05:27,030 cromwell-system-akka.dispatchers.engine-dispatcher-5 INFO  - SingleWorkflowRunnerActor: Version 52
2020-08-22 18:05:27,043 cromwell-system-akka.dispatchers.engine-dispatcher-5 INFO  - SingleWorkflowRunnerActor: Submitting workflow
2020-08-22 18:05:27,103 cromwell-system-akka.dispatchers.api-dispatcher-36 INFO  - Unspecified type (Unspecified version) workflow 4238d010-93c3-40f2-b315-ab71b795acfc submitted
2020-08-22 18:05:27,131 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - SingleWorkflowRunnerActor: Workflow submitted UUID(4238d010-93c3-40f2-b315-ab71b795acfc)
2020-08-22 18:05:27,144 cromwell-system-akka.dispatchers.engine-dispatcher-33 INFO  - 1 new workflows fetched by cromid-28ec5ec: 4238d010-93c3-40f2-b315-ab71b795acfc
2020-08-22 18:05:27,160 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - WorkflowManagerActor Starting workflow UUID(4238d010-93c3-40f2-b315-ab71b795acfc)
2020-08-22 18:05:27,169 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - WorkflowManagerActor Successfully started WorkflowActor-4238d010-93c3-40f2-b315-ab71b795acfc
2020-08-22 18:05:27,169 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - Retrieved 1 workflows from the WorkflowStoreActor
2020-08-22 18:05:27,202 cromwell-system-akka.dispatchers.engine-dispatcher-33 INFO  - WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
2020-08-22 18:05:27,329 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - MaterializeWorkflowDescriptorActor [UUID(4238d010)]: Parsing workflow as WDL 1.0
2020-08-22 18:05:30,315 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - MaterializeWorkflowDescriptorActor [UUID(4238d010)]: Call-to-Backend assignments: atac.reproducibility_idr -> slurm, atac.fraglen_stat_pe -> slurm, atac.macs2_signal_track -> slurm, atac.idr_pr -> slurm, atac.count_signal_track -> slurm, atac.tss_enrich -> slurm, atac.pool_blacklist -> slurm, atac.idr -> slurm, atac.xcor -> slurm, atac.compare_signal_to_roadmap -> slurm, atac.filter_no_dedup -> slurm, atac.overlap -> slurm, atac.read_genome_tsv -> slurm, atac.frac_mito -> slurm, atac.reproducibility_overlap -> slurm, atac.bam2ta -> slurm, atac.idr_ppr -> slurm, atac.macs2_signal_track_pooled -> slurm, atac.gc_bias -> slurm, atac.error_input_data -> slurm, atac.preseq -> slurm, atac.filter -> slurm, atac.call_peak_ppr1 -> slurm, atac.call_peak_pr1 -> slurm, atac.pool_ta_pr2 -> slurm, atac.count_signal_track_pooled -> slurm, atac.call_peak_pooled -> slurm, atac.align_mito -> slurm, atac.align -> slurm, atac.call_peak_ppr2 -> slurm, atac.jsd -> slurm, atac.call_peak -> slurm, atac.qc_report -> slurm, atac.call_peak_pr2 -> slurm, atac.bam2ta_no_dedup -> slurm, atac.pool_ta_pr1 -> slurm, atac.pool_ta -> slurm, atac.overlap_pr -> slurm, atac.spr -> slurm, atac.annot_enrich -> slurm, atac.overlap_ppr -> slurm
2020-08-22 18:05:30,627 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - WorkflowManagerActor Workflow 4238d010-93c3-40f2-b315-ab71b795acfc failed (during InitializingWorkflowState): Task raise_exception has an invalid runtime attribute memory = !! NOT FOUND !!
2020-08-22 18:05:30,631 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - WorkflowManagerActor WorkflowActor-4238d010-93c3-40f2-b315-ab71b795acfc is in a terminal state: WorkflowFailedState
2020-08-22 18:05:32,009 cromwell-system-akka.dispatchers.engine-dispatcher-6 INFO  - Not triggering log of token queue status. Effective log interval = None
2020-08-22 18:05:32,521 cromwell-system-akka.dispatchers.engine-dispatcher-6 INFO  - SingleWorkflowRunnerActor workflow finished with status 'Failed'.
2020-08-22 18:05:36,645 cromwell-system-akka.dispatchers.engine-dispatcher-68 INFO  - SingleWorkflowRunnerActor writing metadata to /home/kdemuren/data/tmp-caper/atac/20200822_180503_672685/metadata.json
2020-08-22 18:05:36,676  INFO  - Workflow polling stopped
2020-08-22 18:05:36,689  INFO  - 0 workflows released by cromid-28ec5ec
2020-08-22 18:05:36,693  INFO  - Shutting down WorkflowStoreActor - Timeout = 5 seconds
2020-08-22 18:05:36,696  INFO  - Shutting down WorkflowLogCopyRouter - Timeout = 5 seconds
2020-08-22 18:05:36,698  INFO  - Shutting down JobExecutionTokenDispenser - Timeout = 5 seconds
2020-08-22 18:05:36,699 cromwell-system-akka.dispatchers.engine-dispatcher-60 INFO  - Aborting all running workflows.
2020-08-22 18:05:36,699  INFO  - JobExecutionTokenDispenser stopped
2020-08-22 18:05:36,700  INFO  - WorkflowStoreActor stopped
2020-08-22 18:05:36,705  INFO  - WorkflowLogCopyRouter stopped
2020-08-22 18:05:36,705  INFO  - Shutting down WorkflowManagerActor - Timeout = 3600 seconds
2020-08-22 18:05:36,705 cromwell-system-akka.dispatchers.engine-dispatcher-68 INFO  - WorkflowManagerActor All workflows finished
2020-08-22 18:05:36,705  INFO  - WorkflowManagerActor stopped
2020-08-22 18:05:37,015  INFO  - Connection pools shut down
2020-08-22 18:05:37,017  INFO  - Shutting down SubWorkflowStoreActor - Timeout = 1800 seconds
2020-08-22 18:05:37,017  INFO  - Shutting down JobStoreActor - Timeout = 1800 seconds
2020-08-22 18:05:37,017  INFO  - Shutting down CallCacheWriteActor - Timeout = 1800 seconds
2020-08-22 18:05:37,017  INFO  - Shutting down ServiceRegistryActor - Timeout = 1800 seconds
2020-08-22 18:05:37,017  INFO  - Shutting down DockerHashActor - Timeout = 1800 seconds
2020-08-22 18:05:37,017  INFO  - Shutting down IoProxy - Timeout = 1800 seconds
2020-08-22 18:05:37,018  INFO  - JobStoreActor stopped
2020-08-22 18:05:37,018  INFO  - CallCacheWriteActor Shutting down: 0 queued messages to process
2020-08-22 18:05:37,018  INFO  - SubWorkflowStoreActor stopped
2020-08-22 18:05:37,018  INFO  - CallCacheWriteActor stopped
2020-08-22 18:05:37,018  INFO  - WriteMetadataActor Shutting down: 0 queued messages to process
2020-08-22 18:05:37,019  INFO  - KvWriteActor Shutting down: 0 queued messages to process
2020-08-22 18:05:37,021  INFO  - IoProxy stopped
```

**Error log**
Caper automatically runs a troubleshooter for failed workflows. If it doesn't then get a `WORKFLOW_ID` of your failed workflow with `caper list` or directly use a `metadata.json` file on Caper's output directory.
```
2020-08-22 18:19:23,146|caper.server_heartbeat|ERROR| Failed to read from a heartbeat file. ~/.caper/default_server_heartbeat
Traceback (most recent call last):
  File "/home/kdemuren/miniconda3/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/home/kdemuren/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cli.py", line 504, in main
    client(parsed_args)
  File "/home/kdemuren/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cli.py", line 269, in client
    subcmd_troubleshoot(c, args)
  File "/home/kdemuren/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cli.py", line 454, in subcmd_troubleshoot
    wf_ids_or_labels=args.wf_id_or_label, embed_subworkflow=True
  File "/home/kdemuren/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_client.py", line 129, in metadata
    embed_subworkflow=embed_subworkflow,
  File "/home/kdemuren/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cromwell_rest_api.py", line 144, in get_metadata
    workflows = self.find(workflow_ids, labels)
  File "/home/kdemuren/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cromwell_rest_api.py", line 226, in find
    CromwellRestAPI.ENDPOINT_WORKFLOWS, params=CromwellRestAPI.PARAMS_WORKFLOWS
  File "/home/kdemuren/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cromwell_rest_api.py", line 299, in __request_get
    ) from None
Exception: Failed to connect to Cromwell server. req=GET, url=http://localhost:8000/api/workflows/v1/query
```

**Comment by atreeneedsaforest** [comment]
Hi, 
I have the same error. I am trying to run the pipeline v1.8.0 using the example json https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ_subsampled_caper.json on a PBS cluster, please find here the last lines I got on standard output/error:
`2020-08-24 19:18:55,981|caper.cromwell|INFO| Validating WDL/inputs/imports with Womtool...
2020-08-24 19:19:00,785|caper.cromwell|INFO| Womtool validation passed.
2020-08-24 19:19:00,786|caper.caper_runner|INFO| launching run: wdl=/home/users/ngs/software/encode/atac-seq-pipeline/atac.wdl, inputs=/home/users/ngs/software/encode/tmp/home/users/ngs/DNAnalysis/ATAC_test_ENCSR356KRQ/ENCSR356KRQ_subsampled_caper.local.json, backend_conf=/home/users/ngs/software/encode/tmp/atac/20200824_184016_924429/backend.conf
2020-08-24 19:19:13,758|caper.cromwell_workflow_monitor|INFO| Workflow: id=e665757a-0c3f-47ee-adbe-87616a980ef6, status=Submitted
2020-08-24 19:19:13,820|caper.cromwell_workflow_monitor|INFO| Workflow: id=e665757a-0c3f-47ee-adbe-87616a980ef6, status=Running
2020-08-24 19:19:17,336|caper.cromwell_workflow_monitor|INFO| Workflow: id=e665757a-0c3f-47ee-adbe-87616a980ef6, status=Failed
2020-08-24 19:19:23,879|caper.cromwell_metadata|WARNING| Failed to write metadata file. workflowRoot not found. wf_id=e665757a-0c3f-47ee-adbe-87616a980ef6
2020-08-24 19:19:23,879|caper.cromwell|INFO| Workflow failed. Auto-troubleshooting...
*Started troubleshooting workflow: id=e665757a-0c3f-47ee-adbe-87616a980ef6, status=Failed
*Found failures JSON object.
[
    {
        "causedBy": [
            {
                "message": "Task raise_exception has an invalid runtime attribute memory = !! NOT FOUND !!",
                "causedBy": []
            }
        ],
        "message": "Runtime validation failed"
    }
]
*Recursively finding failures in calls (tasks)...
2020-08-24 19:19:23,879|caper.nb_subproc_thread|ERROR| Subprocess failed. returncode=1
2020-08-24 19:19:23,880|caper.cli|ERROR| Check stdout/stderr in /home/ngstree/ngs/DNAnalysis/ATAC_test_ENCSR356KRQ/cromwell.out
`
can you please provide a hint? 
Thank you in advance.
Best, 

Margherita

**Comment by leepc12** [comment]
`raise_exception` is a trivial WDL task just to raise an error with some debugging messages. Your cluster didn't run this trivial task  since resource information is not given. I will fix that error in the next release.

Until I fix it, please edit https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/atac.wdl#L2658 of your `atac.wdl` and re-run. This will show a correct error message.
```
    runtime {
        maxRetries : 0
        memory : '4000 MB'
        time : 1
    }
```

The actual reason for the error might be related to your input JSON file.
```
No FASTQ/BAM/TAG-ALIGN/PEAK defined in your input JSON. Check if your FASTQs are defined as "atac.fastqs_repX_RY". DO NOT MISS suffix _R1 even for single ended FASTQ.
```
Please check if your input JSON has all inputs defined correctly.

@atreeneedsaforest: I am not sure why this error occurred with the test input JSON file. What was your full command line? Please post contents of your `~/.caper/default.conf`.

**Comment by atreeneedsaforest** [comment]
@leepc12 here is the command line: 
`caper run /home/users/ngs/software/encode/atac-seq-pipeline/atac.wdl -i /home/users/ngs/DNAnalysis/ATAC_test_ENCSR356KRQ/ENCSR356KRQ_subsampled_caper.json --local-out-dir /home/users/ngs/DNAnalysis/ATAC_test_ENCSR356KRQ
`

and please find below the content of the .caper/default.conf file:

```
backend=pbs

# Hashing strategy for call-caching (3 choices)
# This parameter is for local (local/slurm/sge/pbs) backend only.
# This is important for call-caching,
# which means re-using outputs from previous/failed workflows.
# Cache will miss if different strategy is used.
# "file" method has been default for all old versions of Caper<1.0.
# "path+modtime" is a new default for Caper>=1.0,
#   file: use md5sum hash (slow).
#   path: use path.
#   path+modtime: use path and modification time.
local-hash-strat=path+modtime

# Local directory for localized files and Cromwell's intermediate files
# If not defined, Caper will make .caper_tmp/ on local-out-dir or CWD.
# /tmp is not recommended here since Caper store all localized data files
# on this directory (e.g. input FASTQs defined as URLs in input JSON).
local-loc-dir=/home/users/ngs/software/encode/tmp

cromwell=/home/users/mutarelli/.caper/cromwell_jar/cromwell-52.jar
womtool=/home/users/mutarelli/.caper/womtool_jar/womtool-52.jar
```

**Comment by leepc12** [comment]
@atreeneedsaforest Please post contents of `/home/users/ngs/software/encode/tmp/home/users/ngs/DNAnalysis/ATAC_test_ENCSR356KRQ/ENCSR356KRQ_subsampled_caper.local.json`.

**Comment by kdemuren** [comment]
the WDL fix solved my problem - thanks!

**Comment by leepc12** [comment]
@atreeneedsaforest : Can you `--dry-run` caper to find the overriden `backend.conf` file in INFO log?

Example:
```
$ caper run mem_retry.wdl --db in-memory
2020-08-26 15:41:32,769|caper.caper_base|INFO| Creating a timestamped temporary directory. /mnt/data/scratch/leepc12/test_caper_tmp/mem_retry/20200826_154132_767222
2020-08-26 15:41:32,769|caper.caper_runner|INFO| Localizing files on work_dir. /mnt/data/scratch/leepc12/test_caper_tmp/mem_retry/20200826_154132_767222
2020-08-26 15:41:33,488|caper.caper_workflow_opts|WARNING| Docker image not found in WDL. wdl=/mnt/data/scratch/leepc12/test_wdl1_sub/mem_retry.wdl
2020-08-26 15:41:33,502|caper.cromwell|INFO| Validating WDL/inputs/imports with Womtool...
2020-08-26 15:41:35,166|caper.cromwell|INFO| Womtool validation passed.
2020-08-26 15:41:35,167|caper.caper_runner|INFO| launching run: wdl=/mnt/data/scratch/leepc12/test_wdl1_sub/mem_retry.wdl, inputs=None, backend_conf=/mnt/data/scratch/leepc12/test_caper_tmp/mem_retry/20200826_154132_767222/backend.conf
```
See path under INFO log's key `backend_conf=`. Please find the conf file and it's overriden with your custom backend.conf file. Your custom backend conf file looks good though.

**Comment by atreeneedsaforest** [comment]
Hi @leepc12,
first of all thank you very much for your time!
> @atreeneedsaforest : Can you `--dry-run` caper to find the overriden `backend.conf` file in INFO log?

yes, that's where I started to create the custom backend.conf: following the example I took and modified the "submit" part of pbs section from the backend.conf file that was generated after a dry run:
```
$ caper run ${atacpipdir}/atac.wdl --dry-run
2020-08-27 02:10:04,642|caper.caper_base|INFO| Creating a timestamped temporary directory. /home/users/ngs/software/encode/tmp/atac/20200827_021004_641095
2020-08-27 02:10:04,642|caper.caper_runner|INFO| Localizing files on work_dir. /home/users/ngs/software/encode/tmp/atac/20200827_021004_641095
2020-08-27 02:10:05,865|caper.cromwell|INFO| Validating WDL/inputs/imports with Womtool...
2020-08-27 02:10:10,089|caper.cromwell|INFO| Womtool validation passed.
2020-08-27 02:10:10,090|caper.caper_runner|INFO| launching run: wdl=/home/users/ngs/software/encode/atac-seq-pipeline/atac.wdl, inputs=None, backend_conf=/home/users/ngs/software/encode/tmp/atac/20200827_021004_641095/backend.conf
```

> See path under INFO log's key `backend_conf=`. Please find the conf file and it's overriden with your custom backend.conf file. Your custom backend conf file looks good though.

sorry, I'm not sure i got what you mean: is the backend.conf file generated in tmp/atac always a copy of the default one even if it is in part overriden by a custom file? I thought the two were someway integrated, e.g. I added `pbs_queue=ngs` in default.conf and I find it in /home/users/ngs/software/encode/tmp/atac/20200827_021004_641095/backend.conf
after the run

I have also tried to create a new "torque" backend by copying the entire pbs section and renaming it, please find here the command line: 
`caper run /home/users/ngs/software/encode/atac-seq-pipeline/atac.wdl -b torque --backend-file /home/users/ngs/software/encode/atac-seq-pipeline/test.torque.conf -i /home/users/ngs/DNAnalysis/ATAC_test_ENCSR356KRQ/ENCSR356KRQ_subsampled_caper.json --local-out-dir /home/users/ngs/DNAnalysis/ATAC_test_ENCSR356KRQ`

but in this case it fails and exits before submitting any job, but I don't understand the error reported in cromwell.out
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at cromwell.server.CromwellSystem.$init$(CromwellSystem.scala:68)
        at cromwell.CromwellEntryPoint$$anon$1.<init>(CromwellEntryPoint.scala:126)
        at cromwell.CromwellEntryPoint$.$anonfun$buildCromwellSystem$1(CromwellEntryPoint.scala:126)
        at scala.util.Try$.apply(Try.scala:213)
        at cromwell.CromwellEntryPoint$.buildCromwellSystem(CromwellEntryPoint.scala:126)
```
and please find below the test.torque.conf:
```
backend {
  default = "torque"
  providers {
    torque {
      config {
        default-runtime-attributes {
          time = 24
          pbs_queue = "ngs"
        }
        concurrent-job-limit = 1000
        script-epilogue = "sleep 30 && sync"
        filesystems {
          local {
            localization = [
              "soft-link"
              "hard-link"
              "copy"
            ]
            caching {
              check-sibling-md5 = true
              duplication-strategy = [
                "soft-link"
                "hard-link"
                "copy"
              ]
              hashing-strategy = "path+modtime"
            }
          }
        }
        run-in-background = true
        runtime-attributes = """String? docker
String? docker_user
Int cpu = 1
Int? gpu
Int? time
Int? memory_mb
String? pbs_queue
String? pbs_extra_param
String? singularity
String? singularity_bindpath
String? singularity_cachedir
"""
        submit = """if [ -z \"$SINGULARITY_BINDPATH\" ]; then export SINGULARITY_BINDPATH=${singularity_bindpath}; fi; \
if [ -z \"$SINGULARITY_CACHEDIR\" ]; then export SINGULARITY_CACHEDIR=${singularity_cachedir}; fi;

echo "${if !defined(singularity) then '/bin/bash ' + script
        else
          'singularity exec --cleanenv ' +
          '--home ' + cwd + ' ' +
          (if defined(gpu) then '--nv ' else '') +
          singularity + ' /bin/bash ' + script}" | \
qsub \
    -N ${job_name} \
    -o ${out} \
    -e ${err} \
    ${true="-lnodes=1:ppn=" false="" defined(cpu)}${cpu}${true=":mem=" false="" defined(memory_mb)}${memory_mb}${true="mb" false="" defined(memory_mb)} \
    ${'-lwalltime=' + time + ':0:0'} \
    ${'-lngpus=' + gpu} \
    ${'-q ' + pbs_queue} \
    ${pbs_extra_param} \
    -V
"""
        root = "/home/ngstree/ngs/DNAnalysis/ATAC_test_ENCSR356KRQ"
        exit-code-timeout-seconds = 180
        kill = "qdel ${job_id}"
        check-alive = "qstat ${job_id}"
        job-id-regex = "(\\d+)"
      }
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
    }
  }
}

include required(classpath("application"))
backend {
  default = TORQUE
  providers {
    TORQUE {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        runtime-attributes = """
        String walltime = "48:00:00"
        Float memory_mb = 12000.0
        """

        submit = "qsub -N ${job_name} -lwalltime=${walltime},lnodes=1:ppn=${cpu},mem=${ceil(memory_mb)}mb -d ${cwd} -o ${out} -e ${err} ${script}"
        kill = "qdel ${job_id}"
        check-alive = "qstat ${job_id}"
        job-id-regex = "(\\d+)"
      }
    }
  }
}
```

**Comment by atreeneedsaforest** [comment]
Dear @leepc12 ,
just an update to let you close the issue also for me: it worked! Apparently there is a problem in torque which for some mysterious reason let the pipeline jobs waiting in queue even when resources are available, but after some time (or asking the admin to force them) they end up running and all the analysis was concluded smoothly. So the custom backend was successfully processed in the end. Now I launched the pipeline it on my samples with fingers crossed.
Thank you very much for help!

**Comment by atreeneedsaforest** [comment]
Dear @leepc12 ,
just an update to let you close the issue also for me: it worked! Apparently there is a problem in torque which for some mysterious reason let the pipeline jobs waiting in queue even when resources are available, but after some time (or asking the admin to force them) they end up running and all the analysis was concluded smoothly. So the custom backend was successfully processed in the end. Now I launched the pipeline on my samples with fingers crossed.
Thank you very much for help!

**Comment by leepc12** [comment]
`-lnodes=1:ppn=` will be applied to Caper.
https://github.com/ENCODE-DCC/caper/pull/91
