### ISSUE TITLE
Issue with executing the pipeline on my data

### ISSUE THREAD

**Issue by genomebio-nk** [ENCODE-DCC/atac-seq-pipeline#279]
Hi there,

I am relatively new to bioinformatics, specifically working with pipelines. I have successfully installed the conda environment and was able to run the test with no issues. However, when trying to run the pipeline with my own data, I kept getting errors, as shown below. Any help is greatly appreciated!

I executed the following command: 

caper run /home/genomebio_nk/atac-seq-pipeline/atac.wdl -i /home/genomebio_nk/Encode_ATAC_Dec2019/Mouse_Tissue_ATAC.json

OS/Platform
OS/Platform: [e.g. Ubuntu 18.04, Google Cloud, Stanford Sherlock/SCG cluster, ...]
Conda version: If you used Conda (conda 4.8.3).
Pipeline version: [v1.8.0]
Caper version: [v1.1.0]
Caper configuration file
Paste contents of ~/.caper/default.conf.

PASTE CAPER CONF CONTENTS HERE
Input JSON file
Paste contents of your input JSON file.

{
    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "/home/genomebio_nk/mm10_genome/mm10.tsv",

    "atac.fastqs_rep1_R1" : [“/home/genomebio_nk/Encode_ATAC_Dec2019/Mouse_Tissue_R2-1_S4_L001_R1_001.fastq.gz”],

    "atac.fastqs_rep1_R2" : [“/home/genomebio_nk/Encode_ATAC_Dec2019/Mouse_Tissue_R2-1_S4_L001_R2_001.fastq.gz”],

    "atac.fastqs_rep2_R1" : [“/home/genomebio_nk/Encode_ATAC_Dec2019/Mouse_Tissue_R5_S1_L001_R1_001.fastq.gz”],

    "atac.fastqs_rep2_R2" : [“/home/genomebio_nk/Encode_ATAC_Dec2019/Mouse_Tissue_R5_S1_L001_R2_001.fastq.gz”],

    "atac.paired_end" : true,
    "atac.auto_detect_adapter" : true,
    "atac.enable_tss_enrich" : false,
    "atac.title" : "Mouse_Tissue_ATACseq (n = 1)",
    "atac.description" : "ATAC-seq on Mouse Tissue"

}

This was the error message that I received:

2020-09-16 13:55:23,031|caper.caper_base|INFO| Creating a timestamped temporary directory. /home/genomebio_nk/Encode_ATAC_Dec2019/.caper_tmp/atac/20200916_135523_031226
2020-09-16 13:55:23,031|caper.caper_runner|INFO| Localizing files on work_dir. /home/genomebio_nk/Encode_ATAC_Dec2019/.caper_tmp/atac/20200916_135523_031226
2020-09-16 13:55:23,031|caper.cli|ERROR|
********** DO NOT CTRL+C MULTIPLE TIMES **********

Traceback (most recent call last):
  File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 344, in subcmd_run
    dry_run=args.dry_run,
  File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/caper_runner.py", line 368, in run
    inputs, backend=backend, recursive=not no_deepcopy, make_md5_file=True
  File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/caper_base.py", line 156, in localize_on_backend_if_modified
    f=f, backend=backend, recursive=recursive, make_md5_file=make_md5_file
  File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/caper_base.py", line 141, in localize_on_backend
    loc_prefix, recursive=recursive, make_md5_file=make_md5_file
  File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/autouri/autouri.py", line 405, in localize_on
    depth=depth,
  File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/autouri/autouri.py", line 612, in localize
    src_contents, fnc_loc
  File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/autouri/loc_aux.py", line 54, in recurse_json
    d = json.loads(contents)
  File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 30 (char 129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 502, in main
    return runner(parsed_args, nonblocking_server=nonblocking_server)
  File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 208, in runner
    subcmd_run(c, args)
File "/home/genomebio_nk/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 355, in subcmd_run
    if thread:
UnboundLocalError: local variable 'thread' referenced before assignment

**Comment by leepc12** [comment]
```
json.decoder.JSONDecodeError: Expecting value: line 5 column 30 (char 129)
```
Your input JSON is not a valid JSON.

**Comment by genomebio-nk** [comment]
Oh I see, how can I fix it?

**Comment by leepc12** [comment]
Use any online JSON validator.

**Comment by genomebio-nk** [comment]
I've ran it with a validated JSON file, however, now it only runs partially. I get this message:

2020-09-22 22:43:17,350|caper.caper_base|INFO| Creating a timestamped temporary directory. /home/genomebio_nk/Encode_ATAC_Dec2019/.caper_tmp/atac/20200922_224317_334471
2020-09-22 22:43:17,350|caper.caper_runner|INFO| Localizing files on work_dir. /home/genomebio_nk/Encode_ATAC_Dec2019/.caper_tmp/atac/20200922_224317_334471
2020-09-22 22:43:18,701|caper.cromwell|INFO| Installing Womtool JAR... https://github.com/broadinstitute/cromwell/releases/download/52/womtool-52.jar
2020-09-22 22:43:19,299|autouri.autouri|INFO| cp: skipped due to md5_match, md5=258d2eb824b66e38a0624105c26df6db, src=https://github.com/broadinstitute/cromwell/releases/download/52/womtool-52.jar, dest=/home/genomebio_nk/.caper/womtool_jar/womtool-52.jar
2020-09-22 22:43:19,300|caper.cromwell|INFO| Validating WDL/inputs/imports with Womtool...
2020-09-22 22:43:23,240|caper.cromwell|INFO| Womtool validation passed.
2020-09-22 22:43:23,240|caper.caper_runner|INFO| launching run: wdl=/home/genomebio_nk/atac-seq-pipeline/atac.wdl, inputs=/home/genomebio_nk/Encode_ATAC_Dec2019/Mouse_Tissue_ATAC.json, backend_conf=/home/genomebio_nk/Encode_ATAC_Dec2019/.caper_tmp/atac/20200922_224317_334471/backend.conf
2020-09-22 22:43:23,241|caper.cromwell|INFO| Installing Cromwell JAR... https://github.com/broadinstitute/cromwell/releases/download/52/cromwell-52.jar
2020-09-22 22:43:24,742|autouri.autouri|INFO| cp: skipped due to md5_match, md5=5ff39628c67af8d5b9d35d7fd9584775, src=https://github.com/broadinstitute/cromwell/releases/download/52/cromwell-52.jar, dest=/home/genomebio_nk/.caper/cromwell_jar/cromwell-52.jar
2020-09-22 22:43:36,924|caper.cromwell_workflow_monitor|INFO| Workflow: id=829e0254-98a2-4745-9d9a-1f6dc03c17c1, status=Submitted
2020-09-22 22:43:36,986|caper.cromwell_workflow_monitor|INFO| Workflow: id=829e0254-98a2-4745-9d9a-1f6dc03c17c1, status=Running
2020-09-22 22:43:46,424|caper.cromwell_workflow_monitor|INFO| Task: id=829e0254-98a2-4745-9d9a-1f6dc03c17c1, task=atac.read_genome_tsv:-1, retry=0, status=Started, job_id=1125820
2020-09-22 22:43:46,435|caper.cromwell_workflow_monitor|INFO| Task: id=829e0254-98a2-4745-9d9a-1f6dc03c17c1, task=atac.read_genome_tsv:-1, retry=0, status=WaitingForReturnCode
2020-09-22 22:43:57,331|caper.cromwell_workflow_monitor|INFO| Task: id=829e0254-98a2-4745-9d9a-1f6dc03c17c1, task=atac.read_genome_tsv:-1, retry=0, status=Done
2020-09-22 22:44:01,414|caper.cromwell_workflow_monitor|INFO| Task: id=829e0254-98a2-4745-9d9a-1f6dc03c17c1, task=atac.align:1, retry=0, status=Started, job_id=1125863
2020-09-22 22:44:01,424|caper.cromwell_workflow_monitor|INFO| Task: id=829e0254-98a2-4745-9d9a-1f6dc03c17c1, task=atac.align:1, retry=0, status=WaitingForReturnCode
2020-09-22 22:44:11,918|caper.cromwell_workflow_monitor|INFO| Task: id=829e0254-98a2-4745-9d9a-1f6dc03c17c1, task=atac.align_mito:1, retry=0, status=Started, job_id=1126294
2020-09-22 22:44:11,928|caper.cromwell_workflow_monitor|INFO| Task: id=829e0254-98a2-4745-9d9a-1f6dc03c17c1, task=atac.align_mito:1, retry=0, status=WaitingForReturnCode


And at the end, I only get the following folders: 
call-align
call-align_mito
call-read_genome_tsv

**Comment by leepc12** [comment]
I think they were still running. Are you running from your laptop/desktop?

**Comment by genomebio-nk** [comment]
No, this is all it shows for hours.
Yes, this is from my laptop, however I am connected to a remote server.

**Comment by ViriyaK** [comment]
Hello,

I am also having this problem. The pipeline gets stuck at at task=atac.align_mito:1 and doesn't output anything past those three folders. I am using Slurm and this problem occurs whether I run it as part of a script or using the command line. However, the pipeline completes if I am using the example json. I am using the correct hard path for my fastqs and basically follows the same convention of the example json.

**Comment by leepc12** [comment]
@ViriyaK If the pipeline completes with the test sample, I think your job is still running. I am not sure how large your sample is. e.g. pipeline's full test PE sample (unsubsampled version of the test sample you ran) it takes 18 hours on Google Cloud with 8 cpus.

Please check the status of your job. `squeue -j JOB_ID`. Check if it's still running.
Get JOB_ID for the task in `cromwell.out` on your CWD.

**Comment by ViriyaK** [comment]
@leepc12 Thank you for your prompt reply.

I have tried running it for a full 24 hours before and it still did not finish. I will try again with increased resources and let you know if it works. I have 2 paired-end fastq.gz of around 1.5GB each (4 fastq total).

**Comment by leepc12** [comment]
@ViriyaK: It's weird. That looks like a small sample and it should finish in several hours.

**Comment by genomebio-nk** [comment]
This is the same issue I am having, with two paired-end fastq files, (each of 2 GB). I am not on a slurm scheduler and  can't see whether the job is still running, is there anything else I could do?

**Comment by leepc12** [comment]
@genomebio-nk: Did it work with our test sample?

**Comment by genomebio-nk** [comment]
Yes it worked with the test samples

**Comment by leepc12** [comment]
@genomebio-nk: If that worked with the test sample then pipeline might be still running. If you run it locally on your laptop, those 4 jobs (align, align_mito) will run at the same time and will request 4 x cpu, ram for the align task.
Let's serialize those jobs (by limiting concurrent task to 1)
`caper run ... --max-concurrent-tasks 1`

**Comment by ViriyaK** [comment]
@leepc12 It has worked for the first time. I think you are correct. I believe I simply did not request enough resources, which is weird because I have requested an entire node before and it still failed. I had to specifically include --ntasks-per-node=8 and --mem 40G, which might be overkill and I will adjust accordingly, but it worked. Thank you very much.

**Comment by genomebio-nk** [comment]
I've tried running it as you suggested (--max-concurrent-tasks 1), however, I am still encountering the same issue.

**Comment by leepc12** [comment]
Please run `sync` on a compute node and see if it hangs.

**Comment by genomebio-nk** [comment]
Sorry, could you clarify what that means?

**Comment by leepc12** [comment]
Just run `sync` and see if it hagns.

**Comment by genomebio-nk** [comment]
No it does not

**Comment by leepc12** [comment]
@genomebio-nk: If it worked with the test sample, and I think it's still running.
Please check any error messages in Caper's log/screen output and Cromwell's log `cromwell.out`.

**Comment by genomebio-nk** [comment]
I've send you an e-mail containing the cromwell.out file.

**Comment by leepc12** [comment]
@genomebio-nk: I got it. looking at it.

**Comment by leepc12** [comment]
I haven't seen this error before. Looks like somewhat related to file system and localization of files.
```
java.lang.Exception: Failed command instantiation
```
Double quotes in your inputT JSON look weird. Can you use any online JSON validator to validate it?
Also, please check all paths in your input JSON and genome TSV.

**Comment by genomebio-nk** [comment]
I have validated the JSON file using https://jsonlint.com/ and it says it is a valid JSON file. I have also checked to make sure all paths in my input JSON file are correct. 
T build the genome, I executed the command "./download_genome_data.sh" which created a directory containing mm10 genome info (including the TSV which is what I used in my JSON file).

**Comment by leepc12** [comment]
Can you try with this mm10 TSV?
```
    "atac.genome_tsv": "https://storage.googleapis.com/encode-pipeline-genome-data/genome_tsv/v3/mm10.tsv",
```

**Comment by genomebio-nk** [comment]
Thank you so much for all of your help and time, this is now working! :)
