### ISSUE TITLE
issue with pipeline: no module named matplotlib

### ISSUE THREAD

**Issue by BenvanderVeer** [ENCODE-DCC/atac-seq-pipeline#312]
Dear developers,

First, thank you for giving us this pipeline, it is a great help!

I am trying to run it, and at the point that it tries to make the TSS enrichment plot and calculate the GC bias it crashes. See the output below:

```
2021-03-03 16:12:37,381|caper.caper_base|INFO| Creating a timestamped temporary directory. /scratch/leuven/328/vsc32808/atac/20210303_161237_380747
2021-03-03 16:12:37,381|caper.caper_runner|INFO| Localizing files on work_dir. /scratch/leuven/328/vsc32808/atac/20210303_161237_380747
2021-03-03 16:12:39,892|autouri.autouri|INFO| cp: skipped due to name_size_match, size=870379095, mt=1549678384.0, src=https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE/@@download/mm10_no_alt_analysis_set_ENCODE.fasta.gz, dest=/scratch/leuven/328/vsc32808/72041e824adb499a4974d85ba31fe30d/mm10_no_alt_analysis_set_ENCODE.fasta.gz
2021-03-03 16:12:41,389|autouri.autouri|INFO| cp: skipped due to md5_match, md5=a4c7d8527b74a37ae524dda0a1fe0042, src=https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE_mito_only/@@download/mm10_no_alt_analysis_set_ENCODE_mito_only.fasta.gz, dest=/scratch/leuven/328/vsc32808/bbf176bc384fbe2a734ff0122b8315b3/mm10_no_alt_analysis_set_ENCODE_mito_only.fasta.gz
2021-03-03 16:12:42,941|autouri.autouri|INFO| cp: skipped due to md5_match, md5=5d19eeb4197ae10540252c61399f3131, src=https://www.encodeproject.org/files/ENCFF547MET/@@download/ENCFF547MET.bed.gz, dest=/scratch/leuven/328/vsc32808/da42a1c4b0f9d3225600da56b2c9571d/ENCFF547MET.bed.gz
2021-03-03 16:12:45,883|autouri.autouri|INFO| cp: skipped due to md5_match, md5=5a103c9a15dd660c295a089ef5035672, src=https://www.encodeproject.org/files/mm10_no_alt.chrom.sizes/@@download/mm10_no_alt.chrom.sizes.tsv, dest=/scratch/leuven/328/vsc32808/a4733a4e097a19c869b1cb1aae1b33c9/mm10_no_alt.chrom.sizes.tsv
2021-03-03 16:12:48,328|autouri.autouri|INFO| cp: skipped due to name_size_match, size=3369625230, mt=1571468994.0, src=https://www.encodeproject.org/files/ENCFF309GLL/@@download/ENCFF309GLL.tar.gz, dest=/scratch/leuven/328/vsc32808/042925a7d9816ca478718df2aee1b980/ENCFF309GLL.tar.gz
2021-03-03 16:12:49,838|autouri.autouri|INFO| cp: skipped due to md5_match, md5=d8e6d7a95cbe338c4b340d5c0909472a, src=https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE_mito_only_bowtie2_index/@@download/mm10_no_alt_analysis_set_ENCODE_mito_only_bowtie2_index.tar.gz, dest=/scratch/leuven/328/vsc32808/820a6f4379a41332ddf3f25fc09101d5/mm10_no_alt_analysis_set_ENCODE_mito_only_bowtie2_index.tar.gz
2021-03-03 16:12:52,399|autouri.autouri|INFO| cp: skipped due to name_size_match, size=3916743172, mt=1549726735.0, src=https://www.encodeproject.org/files/ENCFF018NEO/@@download/ENCFF018NEO.tar.gz, dest=/scratch/leuven/328/vsc32808/506b880ea82aeae31802ecd4b265cff9/ENCFF018NEO.tar.gz
2021-03-03 16:12:53,944|autouri.autouri|INFO| cp: skipped due to md5_match, md5=3660491701075d79c82502b467b17f6d, src=https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE_mito_only_bwa_index/@@download/mm10_no_alt_analysis_set_ENCODE_mito_only_bwa_index.tar.gz, dest=/scratch/leuven/328/vsc32808/4ce6df75b5bc0d2c95fb08049d00b722/mm10_no_alt_analysis_set_ENCODE_mito_only_bwa_index.tar.gz
2021-03-03 16:12:55,477|autouri.autouri|INFO| cp: skipped due to md5_match, md5=cf91ddf998ea78560a47538f34839fd9, src=https://www.encodeproject.org/files/ENCFF498BEJ/@@download/ENCFF498BEJ.bed.gz, dest=/scratch/leuven/328/vsc32808/e4b3a5b822cdb43f38f1a028bfdfc469/ENCFF498BEJ.bed.gz
2021-03-03 16:12:57,929|autouri.autouri|INFO| cp: skipped due to name_size_match, size=24830198, mt=1592463729.0, src=https://www.encodeproject.org/files/ENCFF015KVI/@@download/ENCFF015KVI.bed.gz, dest=/scratch/leuven/328/vsc32808/b7f1373597857ea4d8a11c3915c4455d/ENCFF015KVI.bed.gz
2021-03-03 16:12:59,479|autouri.autouri|INFO| cp: skipped due to md5_match, md5=52bcf15a04b4e1731ebd1a03c1c2fdbc, src=https://www.encodeproject.org/files/ENCFF206BQS/@@download/ENCFF206BQS.bed.gz, dest=/scratch/leuven/328/vsc32808/571f676aa2f98f5bffdb06c91453cffd/ENCFF206BQS.bed.gz
2021-03-03 16:13:01,958|autouri.autouri|INFO| cp: skipped due to name_size_match, size=24266900, mt=1592463727.0, src=https://www.encodeproject.org/files/ENCFF580RGZ/@@download/ENCFF580RGZ.bed.gz, dest=/scratch/leuven/328/vsc32808/799bb08d7265d45d0a81bd65d6b7c7f0/ENCFF580RGZ.bed.gz
2021-03-03 16:13:02,465|autouri.autouri|INFO| cp: skipped due to md5_match, md5=c8f7d987d4c7f14145400c47d52c9cb4, src=https://storage.googleapis.com/encode-pipeline-genome-data/mm10/ataqc/mm10_dnase_avg_fseq_signal_formatted.txt.gz, dest=/scratch/leuven/328/vsc32808/cf2b604559fb2950d79aa439cafa86d0/mm10_dnase_avg_fseq_signal_formatted.txt.gz
2021-03-03 16:13:02,999|autouri.autouri|INFO| cp: skipped due to md5_match, md5=816a8d22ff0c9241e21a57cc075cdb40, src=https://storage.googleapis.com/encode-pipeline-genome-data/mm10/ataqc/mm10_celltype_compare_subsample.bed.gz, dest=/scratch/leuven/328/vsc32808/6cb5db6af37a5741fb86a6a9bf21f3f1/mm10_celltype_compare_subsample.bed.gz
2021-03-03 16:13:03,159|autouri.autouri|INFO| cp: skipped due to md5_match, md5=078f14bf4c6e6aad467f835c65a3c045, src=https://storage.googleapis.com/encode-pipeline-genome-data/mm10/ataqc/mm10_dnase_avg_fseq_signal_metadata.txt, dest=/scratch/leuven/328/vsc32808/fe37c3c5d22dfa5e5b26520a3ba8ac8f/mm10_dnase_avg_fseq_signal_metadata.txt
2021-03-03 16:13:03,820|caper.cromwell|INFO| Validating WDL/inputs/imports with Womtool...
2021-03-03 16:13:06,473|caper.cromwell|INFO| Womtool validation passed.
2021-03-03 16:13:06,474|caper.caper_runner|INFO| launching run: wdl=/staging/leuven/stg_00072/Ben/colabs/ATACseq_Enrico/atac.wdl, inputs=/scratch/leuven/328/vsc32808/staging/leuven/stg_00072/Ben/colabs/ATACseq_Enrico/KMR46_ctrl.local.json, backend_conf=/scratch/leuven/328/vsc32808/atac/20210303_161237_380747/backend.conf
2021-03-03 16:13:15,867|caper.cromwell_workflow_monitor|INFO| Workflow: id=2189bf5a-e68c-4031-b933-d0b0350badf2, status=Submitted
2021-03-03 16:13:15,909|caper.cromwell_workflow_monitor|INFO| Workflow: id=2189bf5a-e68c-4031-b933-d0b0350badf2, status=Running
2021-03-03 16:13:25,497|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.read_genome_tsv:-1, retry=0, status=Started, job_id=7653
2021-03-03 16:13:25,508|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.read_genome_tsv:-1, retry=0, status=WaitingForReturnCode
2021-03-03 16:13:36,088|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.read_genome_tsv:-1, retry=0, status=Done
2021-03-03 16:13:45,485|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.align:0, retry=0, status=Started, job_id=8385
2021-03-03 16:13:45,495|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.align:1, retry=0, status=Started, job_id=8241
2021-03-03 16:13:45,505|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.align:1, retry=0, status=WaitingForReturnCode
2021-03-03 16:13:45,516|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.align:0, retry=0, status=WaitingForReturnCode
2021-03-03 16:13:50,491|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.align_mito:1, retry=0, status=Started, job_id=8662
2021-03-03 16:13:50,501|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.align_mito:0, retry=0, status=Started, job_id=8521
2021-03-03 16:13:50,511|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.align_mito:0, retry=0, status=WaitingForReturnCode
2021-03-03 16:13:50,522|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.align_mito:1, retry=0, status=WaitingForReturnCode
2021-03-03 16:45:57,077|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.align_mito:1, retry=0, status=Done
2021-03-03 16:48:26,002|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.align_mito:0, retry=0, status=Done
2021-03-03 17:06:11,860|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.align:1, retry=0, status=Done
2021-03-03 17:06:20,488|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.filter:1, retry=0, status=Started, job_id=35282
2021-03-03 17:06:20,498|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.frac_mito:1, retry=0, status=Started, job_id=35255
2021-03-03 17:06:20,509|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.filter:1, retry=0, status=WaitingForReturnCode
2021-03-03 17:06:20,519|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.frac_mito:1, retry=0, status=WaitingForReturnCode
2021-03-03 17:06:29,260|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.frac_mito:1, retry=0, status=Done
2021-03-03 17:06:52,968|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.align:0, retry=0, status=Done
2021-03-03 17:07:00,493|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.frac_mito:0, retry=0, status=Started, job_id=35634
2021-03-03 17:07:00,503|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.frac_mito:0, retry=0, status=WaitingForReturnCode
2021-03-03 17:07:05,486|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.filter:0, retry=0, status=Started, job_id=35661
2021-03-03 17:07:05,497|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.filter:0, retry=0, status=WaitingForReturnCode
2021-03-03 17:07:12,036|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.frac_mito:0, retry=0, status=Done
2021-03-03 17:26:40,344|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.filter:1, retry=0, status=Done
2021-03-03 17:26:50,492|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.bam2ta:1, retry=0, status=Started, job_id=8557
2021-03-03 17:26:50,503|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.gc_bias:1, retry=0, status=Started, job_id=8579
2021-03-03 17:26:50,513|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.gc_bias:1, retry=0, status=WaitingForReturnCode
2021-03-03 17:26:50,524|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.bam2ta:1, retry=0, status=WaitingForReturnCode
2021-03-03 17:26:55,487|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.tss_enrich:1, retry=0, status=Started, job_id=8598
2021-03-03 17:26:55,498|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.tss_enrich:1, retry=0, status=WaitingForReturnCode
2021-03-03 17:27:02,741|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.tss_enrich:1, retry=0, status=Done
2021-03-03 17:27:10,490|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.tss_enrich:1, retry=1, status=Started, job_id=9019
2021-03-03 17:27:10,500|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.tss_enrich:1, retry=1, status=WaitingForReturnCode
2021-03-03 17:27:18,095|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.tss_enrich:1, retry=1, status=Done
2021-03-03 17:28:03,866|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.bam2ta:1, retry=0, status=Done
2021-03-03 17:28:13,348|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.filter:0, retry=0, status=Done
2021-03-03 17:31:15,089|caper.cromwell_workflow_monitor|INFO| Task: id=2189bf5a-e68c-4031-b933-d0b0350badf2, task=atac.gc_bias:1, retry=0, status=Done
2021-03-03 17:31:15,937|caper.cromwell_workflow_monitor|INFO| Workflow: id=2189bf5a-e68c-4031-b933-d0b0350badf2, status=Failed
2021-03-03 17:31:40,934|caper.cromwell_metadata|INFO| Wrote metadata file. /staging/leuven/stg_00072/Ben/colabs/ATACseq_Enrico/pipelineOutput/KMR46_ctrl/atac/2189bf5a-e68c-4031-b933-d0b0350badf2/metadata.json
2021-03-03 17:31:40,934|caper.cromwell|INFO| Workflow failed. Auto-troubleshooting...
* Started troubleshooting workflow: id=2189bf5a-e68c-4031-b933-d0b0350badf2, status=Failed
* Found failures JSON object.
[
    {
        "causedBy": [
            {
                "causedBy": [],
                "message": "Job atac.tss_enrich:1:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            }
        ],
        "message": "Workflow failed"
    }
]
* Recursively finding failures in calls (tasks)...

==== NAME=atac.tss_enrich, STATUS=RetryableFailure, PARENT=
SHARD_IDX=1, RC=1, JOB_ID=8598
START=2021-03-03T16:26:51.842Z, END=2021-03-03T16:27:05.488Z
STDOUT=/staging/leuven/stg_00072/Ben/colabs/ATACseq_Enrico/pipelineOutput/KMR46_ctrl/atac/2189bf5a-e68c-4031-b933-d0b0350badf2/call-tss_enrich/shard-1/execution/stdout
STDERR=/staging/leuven/stg_00072/Ben/colabs/ATACseq_Enrico/pipelineOutput/KMR46_ctrl/atac/2189bf5a-e68c-4031-b933-d0b0350badf2/call-tss_enrich/shard-1/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/data/leuven/328/vsc32808/miniconda/envs/encode-atac-seq-pipeline/bin/encode_task_tss_enrich.py", line 6, in <module>
    import matplotlib as mpl
ImportError: No module named matplotlib


==== NAME=atac.tss_enrich, STATUS=Failed, PARENT=
SHARD_IDX=1, RC=1, JOB_ID=9019
START=2021-03-03T16:27:07.813Z, END=2021-03-03T16:27:18.104Z
STDOUT=/staging/leuven/stg_00072/Ben/colabs/ATACseq_Enrico/pipelineOutput/KMR46_ctrl/atac/2189bf5a-e68c-4031-b933-d0b0350badf2/call-tss_enrich/shard-1/attempt-2/execution/stdout
STDERR=/staging/leuven/stg_00072/Ben/colabs/ATACseq_Enrico/pipelineOutput/KMR46_ctrl/atac/2189bf5a-e68c-4031-b933-d0b0350badf2/call-tss_enrich/shard-1/attempt-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/data/leuven/328/vsc32808/miniconda/envs/encode-atac-seq-pipeline/bin/encode_task_tss_enrich.py", line 6, in <module>
    import matplotlib as mpl
ImportError: No module named matplotlib

2021-03-03 17:31:40,935|caper.nb_subproc_thread|ERROR| Subprocess failed. returncode=1
2021-03-03 17:31:40,936|caper.cli|ERROR| Check stdout/stderr in /ddn1/vol1/staging/leuven/stg_00072/Ben/colabs/ATACseq_Enrico/cromwell.out
(encode-atac-seq-pipeline) 
```

I first tried installing matplotlib manually in the conda environment, but it says that the package is already present. I tried re-installing the pipeline, with both `bash install_conda_env.sh` and `bash install_conda_env.sh mamba`.

Both give the same issue. I can run the pipeline without making the TSS enrichment plot and calculating the GC bias.

I hope you can help.

best, Ben

**Comment by leepc12** [comment]
Activate the python2 environment and use `conda activate` if `source activate` doesn't work.
Please run the following for debugging.
```bash
# activate the py2 env
$ source activate encode-atac-seq-pipeline-python2

# check if python2 points to the python2 executable on the py2 env
$ which python2
$ conda list matplotlib

# check if it's installed in python2
$ python2
> import matplotlib
```
