### ISSUE TITLE
Pipeline

### ISSUE THREAD

**Issue by ksebby** [ENCODE-DCC/atac-seq-pipeline#320]
## **Describe the bug**
We're trying to reproduce the results described in the paper: https://doi.org/10.1016/j.ajhg.2018.08.001. The experiments are listed here https://www.ncbi.nlm.nih.gov/sra?term=SRP142360. Everything works good for all the experiments except https://www.ncbi.nlm.nih.gov/sra/SRX3994928[accn] which has two technical replicates with very different file sizes. According to the metadata.json, it's failing on the `atac.filter` step.
`"Job atac.filter:0:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."`
I've seen this before and increasing resources usually handles it. I've increased memory a lot but doesn't seem to be helping this time and looking at `monitoring.log` doesn't show it bumping up against the limits. Looking at the log file for the filter step it looks like `betools bamtobed` is the problem. I can't seem to get past this error. I can give you access to the output bucket if you want it.
```
run_shell_cmd: PID=699, PGID=699, CMD=bedtools bamtobed -bedpe -i 1508.1.trim.merged.dupmark.nmsrt.bam | awk 'BEGIN{OFS="\t"}{print $1,$2,$4,$6,$9,$10}' | grep -v "^chrM\s" | sort | uniq -c | awk 'BEGIN{mt=0;m0=0;m1=0;m2=0} ($1==1){m1=m1+1} ($1==2){m2=m2+1} {m0=m0+1} {mt=mt+$1} END{m1_m2=-1.0; if(m2>0) m1_m2=m1/m2; m0_mt=0; if (mt>0) m0_mt=m0/mt; m1_m0=0; if (m0>0) m1_m0=m1/m0; printf "%d\t%d\t%d\t%d\t%f\t%f\t%f\n",mt,m0,m1,m2,m0_mt,m1_m0,m1_m2}' > 1508.1.trim.merged.dupmark.lib_complexity.qc
Traceback (most recent call last):
  File "/software/atac-seq-pipeline/src/encode_task_filter.py", line 364, in <module>
    main()
  File "/software/atac-seq-pipeline/src/encode_task_filter.py", line 345, in main
    args.out_dir)
  File "/software/atac-seq-pipeline/src/encode_task_filter.py", line 274, in pbc_qc_pe
    run_shell_cmd(cmd3)
  File "/software/atac-seq-pipeline/src/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=699, PGID=699, RC=1
```

## **OS/Platform**
- OS/Platform: Google Cloud through truwl.com
- Pipeline version: v1.8.0
- Caper version: [e.g. v1.2.0]

## **Input JSON file**
Paste contents of your input JSON file.
```json
{
    "atac.title": " SRP142360ATAC SRR7064065/SRR7064066 runs only",
    "atac.filter_cpu": 6,
    "atac.genome_tsv": "https://storage.googleapis.com/encode-pipeline-genome-data/genome_tsv/v3/hg38.tsv",
    "atac.paired_end": true,
    "atac.description": "subset of atac-seq samples listed in https://doi.org/10.1016/j.ajhg.2018.08.001 ",
    "atac.enable_xcor": true,
    "atac.call_peak_cpu": 2,
    "atac.filter_mem_mb": 100000,
    "atac.fastqs_rep1_R1": [
        "gs://truwl-quertermous/SRR7064065/1508.1.fastq.gz",
        "gs://truwl-quertermous/SRR7064066/1508.1.fastq.gz"
    ],
    "atac.fastqs_rep1_R2": [
        "gs://truwl-quertermous/SRR7064065/1508.2.fastq.gz",
        "gs://truwl-quertermous/SRR7064066/1508.2.fastq.gz"
    ],
    "atac.auto_detect_adapter": true,
    "atac.macs2_signal_track_mem_mb": 32000

```

**Comment by ksebby** [comment]
I can get the replicates through the pipeline individually, but not together. Below works.
```
 "atac.fastqs_rep1_R1": [
        "gs://truwl-quertermous/SRR7064065/1508.1.fastq.gz",
    ],
    "atac.fastqs_rep1_R2": [
        "gs://truwl-quertermous/SRR7064065/1508.2.fastq.gz",
    ]
```

**Comment by leepc12** [comment]
These two parameters have been deprecated.
```
atac.filter_mem_mb
atac.macs2_signal_track_mem_mb
```
The pipeline determines instance's memory based on input files' size.
Roughly, input file size (e.g. sum of all FASTQs for rep1) x factor + bowtie2 index size + 4.0 GB.
Therefore, instead of the above two, please define the followings and try doubling/tripling them:
```
atac.filter_mem_factor (0.4 by default)
atac.macs2_signal_track_mem_factor (12.0 by default)
```

**Comment by ksebby** [comment]
Okay thanks. Looks like I'll have to upgrade to v1.9. Were these parameters not working properly in v1.8?

**Comment by leepc12** [comment]
No, let's stick to that old version without mem_factors.
Let's increase disk space instead.
```javascript 
{
    "atac.filter_disks": "local-disk 900 HDD"
}
```

Also, that STDOUT file has all the command lines to reproduce the problem.
Please download the problematic BAM file first and then install/activate pipeline's Conda environment on a local computer. Then activate the environment and run those command lines there.

```
# download/install miniconda3 and then
# install pipeline's env
$ bash scripts/install_conda.env.sh mamba
# activate it
$ source activate encode-atac-seq-pipeline
# run command lines
$ bedtools bamtobed ....
```
