### ISSUE TITLE
how to run this pipeline locally

### ISSUE THREAD

**Issue by xinmiaoyan** [ENCODE-DCC/atac-seq-pipeline#328]
## **Describe the bug**
I've already installed the pipeline successfully, and pip install caper. 
after that I used "caper init local" to create the default.conf file and change the local_dir into one of my server file directory "test".

the problem is when I run the pipeline on my server, it can't create the link under the  "test/servername/filename/"
which showed that Connectionerror: connection time out even when the reference genome files were automatically download in the target directory in the default.conf of caper.  

how to deal with this issue? Really appreciate your response.

**Comment by leepc12** [comment]
@xinmiaoyan Please paste your error log here. Does your cluster/filesystem allow soft-linking (`ln -s`)?

**Comment by xinmiaoyan** [comment]
thanks for your response.
yes, my cluster allow soft-linking.
here's the error log:
`
2021-06-25 12:39:22,803|caper.caper_base|INFO| Creating a timestamped temporary directory. /rsrch3/scratch/genomic_med/xyan4/Software/atac-seq-pipeline/caper_test/atac/20210625_123922_801430
2021-06-25 12:39:22,803|caper.caper_runner|INFO| Localizing files on work_dir. /rsrch3/scratch/genomic_med/xyan4/Software/atac-seq-pipeline/caper_test/atac/20210625_123922_801430
2021-06-25 12:39:22,805|autouri.autouri|INFO| cp: (bf176aaa) started. src=https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE/@@download/mm10_no_alt_analysis_set_ENCODE.fasta.gz, dest=/rsrch3/scratch/genomic_med/xyan4/Software/atac-seq-pipeline/caper_test/72041e824adb499a4974d85ba31fe30d/mm10_no_alt_analysis_set_ENCODE.fasta.gz
Traceback (most recent call last):
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x2aaabc566400>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.encodeproject.org', port=443): Max retries exceeded with url: /files/mm10_no_alt_analysis_set_ENCODE/@@download/mm10_no_alt_analysis_set_ENCODE.fasta.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2aaabc566400>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xyan4/.conda/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cli.py", line 675, in main
    return runner(parsed_args, nonblocking_server=nonblocking_server)
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cli.py", line 226, in runner
    subcmd_run(c, args)
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cli.py", line 370, in subcmd_run
    dry_run=args.dry_run,
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_runner.py", line 381, in run
    inputs, backend=backend, recursive=not no_deepcopy, make_md5_file=True
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_base.py", line 163, in localize_on_backend_if_modified
    f=f, backend=backend, recursive=recursive, make_md5_file=make_md5_file
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_base.py", line 148, in localize_on_backend
    loc_prefix, recursive=recursive, make_md5_file=make_md5_file
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/autouri.py", line 429, in localize_on
    no_checksum=no_checksum,
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/autouri.py", line 644, in localize
    src_contents, fnc_loc
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/loc_aux.py", line 56, in recurse_json
    modified = recurse_dict(d, fnc)
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/loc_aux.py", line 35, in recurse_dict
    v, fnc, d_parent=d, d_parent_key=k, modified=modified
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/loc_aux.py", line 42, in recurse_dict
    new_val, modified_ = fnc(d)
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/autouri.py", line 636, in fnc_loc
    no_checksum=no_checksum,
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/autouri.py", line 644, in localize
    src_contents, fnc_loc
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/loc_aux.py", line 83, in recurse_tsv
    new_val, modified_ = fnc(v)
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/autouri.py", line 636, in fnc_loc
    no_checksum=no_checksum,
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/autouri.py", line 664, in localize
    no_checksum=no_checksum,
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/autouri.py", line 348, in cp
    if not self._cp(dest_uri=d):
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/httpurl.py", line 146, in _cp
    headers=requests.utils.default_headers(),
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.encodeproject.org', port=443): Max retries exceeded with url: /files/mm10_no_alt_analysis_set_ENCODE/@@download/mm10_no_alt_analysis_set_ENCODE.fasta.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2aaabc566400>: Failed to establish a new connection: [Errno 110] Connection timed out'))
`
do you have any idea on this issue?

**Comment by leepc12** [comment]
Please run the following to check if your cluster allows downloading files from the internet.
```
$ wget https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE/@@download/mm10_no_alt_analysis_set_ENCODE.fasta.gz
```

**Comment by xinmiaoyan** [comment]
Thanks for your response.
since the firewall role, so my cluster can't link to internet, but the IT team gave a another server which can be linked to encode, and I've downloaded files in /rsrch3/scratch/genomic_med/xyan4/Software/atac-seq-pipeline/caper_test/
it has these directories:
drwx------ 2 4096 Jun 25 09:18 042925a7d9816ca478718df2aee1b980
drwx------ 2 4096 Jun 25 09:18 4ce6df75b5bc0d2c95fb08049d00b722
drwx------ 2 4096 Jun 25 09:18 506b880ea82aeae31802ecd4b265cff9
drwx------ 2 4096 Jun 25 09:18 571f676aa2f98f5bffdb06c91453cffd
drwx------ 2 4096 Jun 25 09:18 6cb5db6af37a5741fb86a6a9bf21f3f1
drwx------ 2 4096 Jun 25 12:43 72041e824adb499a4974d85ba31fe30d
drwx------ 2 4096 Jun 25 09:18 799bb08d7265d45d0a81bd65d6b7c7f0
drwx------ 2 4096 Jun 25 09:18 820a6f4379a41332ddf3f25fc09101d5
drwx------ 2 4096 Jun 25 09:18 a4733a4e097a19c869b1cb1aae1b33c9
drwx------ 7 4096 Jun 25 12:39 atac
drwx------ 2 4096 Jun 25 09:18 b7f1373597857ea4d8a11c3915c4455d
drwx------ 2 4096 Jun 25 09:18 bbf176bc384fbe2a734ff0122b8315b3
drwx------ 2 4096 Jun 25 09:18 cf2b604559fb2950d79aa439cafa86d0
drwx------ 2 4096 Jun 25 09:18 da42a1c4b0f9d3225600da56b2c9571d
drwx------ 2 4096 Jun 25 09:18 e4b3a5b822cdb43f38f1a028bfdfc469
drwx------ 2 4096 Jun 25 09:18 fe37c3c5d22dfa5e5b26520a3ba8ac8f
drwx------ 3 4096 Jun 25 00:25 rsrch3

the last one "rsrch3 " is the soft-link directory, but it can't create the link to the target-directory which we run the pipeline.

**Comment by leepc12** [comment]
On that transfer node, please try this. Even thoug your cluster allows soft-linking, make sure that the localization target directory (`/rsrch3/scratch`?) is on the same filesystem (check with `df -h YOUR_DIRECTORY`) as caper's output directory (`local-out-dir` in your Caper conf or --`local-out-dir` in cmd line args) so that there will be no file-linking issues.
```
$ cd LOCALIZATION_TARGET_DIRECTORY]
$ autouri loc YOUR_INPUT_JSON_FILE .
```
This will recursively (also recursively localizing `.tsv` and `.json` in the file) localizes all files in your input JSON and will make `YOUR_INPUT_JSON.local.json` under CWD. Use that `.local.json` file, which has local paths only. Make sure that all files defined in it are local absolute paths. (e.g. `hg38.local.tsv`).

**Comment by leepc12** [comment]
Closing this due to inactivity
