### ISSUE TITLE
ImportError: No module named _sysconfigdata_x86_64_conda_linux_gnu

### ISSUE THREAD

**Issue by baishengjun** [ENCODE-DCC/atac-seq-pipeline#329]
Hi,
First of all, thank you for providing a wonderful tool. 
I use `scripts/install_conda_env.sh mamba` to install the pipeline, and activate environment. then I use `pip install caper`, it throws `ImportError: No module named _sysconfigdata_x86_64_conda_linux_gnu`. I reinstall python=3.6.1 by `mamba install python=3.6.1`, it works.
But I ran the ATAC-seq pipeline using the example json file: ENCSR356KRQ_subsampled.json. it throws the same error `ImportError: No module named _sysconfigdata_x86_64_conda_linux_gnu`
`2021-06-27 22:31:10,061|caper.cromwell|INFO| Workflow failed. Auto-troubleshooting...
* Started troubleshooting workflow: id=09ae0e11-3ba8-4e4e-9edd-fe300f2a1069, status=Failed
* Found failures JSON object.
[
    {
        "causedBy": [
            {
                "causedBy": [],
                "message": "Job atac.filter:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            },
            {
                "causedBy": [],
                "message": "Job atac.filter_no_dedup:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            }
        ],
        "message": "Workflow failed"
    }
]
* Recursively finding failures in calls (tasks)...

==== NAME=atac.filter, STATUS=RetryableFailure, PARENT=
SHARD_IDX=0, RC=1, JOB_ID=58861
START=2021-06-28T02:29:00.134Z, END=2021-06-28T02:29:18.644Z
STDOUT=/mnt/sda/boshengjun/atac-seq-pipeline/atac/09ae0e11-3ba8-4e4e-9edd-fe300f2a1069/call-filter/shard-0/execution/stdout
STDERR=/mnt/sda/boshengjun/atac-seq-pipeline/atac/09ae0e11-3ba8-4e4e-9edd-fe300f2a1069/call-filter/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/mnt/sdf1/boshengjun/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 438, in <module>
    main()
  File "/mnt/sdf1/boshengjun/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 344, in main
    args.nth, args.mem_gb, args.out_dir)
  File "/mnt/sdf1/boshengjun/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 136, in rm_unmapped_lowq_reads_pe
    res_param=get_samtools_res_param('fixmate', nth=nth),
  File "/mnt/sdf1/boshengjun/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 359, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=59205, PGID=59205, RC=1, DURATION_SEC=0.1
STDERR=Traceback (most recent call last):
  File "/mnt/sdf1/boshengjun/miniconda3/envs/encode-atac-seq-pipeline/bin/../../encode-atac-seq-pipeline-python2/lib/python2.7/site.py", line 548, in <module>
    main()
  File "/mnt/sdf1/boshengjun/miniconda3/envs/encode-atac-seq-pipeline/bin/../../encode-atac-seq-pipeline-python2/lib/python2.7/site.py", line 530, in main
    known_paths = addusersitepackages(known_paths)
  File "/mnt/sdf1/boshengjun/miniconda3/envs/encode-atac-seq-pipeline/bin/../../encode-atac-seq-pipeline-python2/lib/python2.7/site.py", line 275, in addusersitepackages
    user_site = getusersitepackages()
  File "/mnt/sdf1/boshengjun/miniconda3/envs/encode-atac-seq-pipeline/bin/../../encode-atac-seq-pipeline-python2/lib/python2.7/site.py", line 250, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/mnt/sdf1/boshengjun/miniconda3/envs/encode-atac-seq-pipeline/bin/../../encode-atac-seq-pipeline-python2/lib/python2.7/site.py", line 240, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/mnt/sdf1/boshengjun/miniconda3/envs/encode-atac-seq-pipeline-python2/lib/python2.7/sysconfig.py", line 530, in get_config_var
    return get_config_vars().get(name)
  File "/mnt/sdf1/boshengjun/miniconda3/envs/encode-atac-seq-pipeline-python2/lib/python2.7/sysconfig.py", line 482, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/mnt/sdf1/boshengjun/miniconda3/envs/encode-atac-seq-pipeline-python2/lib/python2.7/sysconfig.py", line 365, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ImportError: No module named _sysconfigdata_x86_64_conda_linux_gnu
[bam_mating_core] ERROR: Couldn't read header
`
Thank you and looking forward to your reply

**Comment by leepc12** [comment]
Can you uninstall the environment and install without mamba and try again?
```bash
$ scripts/uninstall_conda_env.sh
$ scripts/install_conda_env.sh # without mamba
```

**Comment by baishengjun** [comment]
Thanks a lot, it works

**Comment by fentouxungui** [comment]
Great!
