### ISSUE TITLE
caper run

### ISSUE THREAD

**Issue by shenlinyong** [ENCODE-DCC/atac-seq-pipeline#333]
## **Describe the bug**
A clear and concise description of what the problem is.
Thank you very much for the pipline, but encountered difficulties when running `caper run /home/SLY69/biosoft/atac-seq-pipeline/atac.wdl -i /home/SLY69/project/encode-atac-seq-pipeline/input.json`error，and I don't know how to solve it.

## **OS/Platform**
- OS/Platform: [use xshell to connect remotely centoa7 for 144 CPU version ]
- Conda version: If you used Conda (`$ conda --version`).
- Pipeline version: [e.g. v1.8.0]
- Caper version: [e.g. v1.2.0]

## **Caper configuration file**
Paste contents of `~/.caper/default.conf`.
```backend=local

# Hashing strategy for call-caching (3 choices)
# This parameter is for local (local/slurm/sge/pbs) backend only.
# This is important for call-caching,
# which means re-using outputs from previous/failed workflows.
# Cache will miss if different strategy is used.
# "file" method has been default for all old versions of Caper<1.0.
# "path+modtime" is a new default for Caper>=1.0,
#   file: use md5sum hash (slow).
#   path: use path.
#   path+modtime: use path and modification time.
local-hash-strat=path+modtime

# Local directory for localized files and Cromwell's intermediate files
# If not defined, Caper will make .caper_tmp/ on local-out-dir or CWD.
# /tmp is not recommended here since Caper store all localized data files
# on this directory (e.g. input FASTQs defined as URLs in input JSON).
local-loc-dir=/home/SLY69/project/encode-atac-seq-pipeline/caper_tmp

cromwell=/home/SLY69/.caper/cromwell_jar/cromwell-59.jar
```

## **Input JSON file**
Paste contents of your input JSON file.
```{
    "atac.title" : "gallu_ATAC",
    "atac.description" : "ATAC analysis results used by Shen Linyong.",

    "atac.pipeline_type" : "atac",
    "atac.align_only" : false, 
    "atac.true_rep_only" : false, 

    "atac.genome_tsv" : "/home/SLY69/biodata/ref/atac/galGal6.tsv",

    "atac.paired_end" : true, 

    "atac.fastqs_rep1_R1" : [ "/home/SLY69/project/atac/raw/AF124701.R1.fastq.gz" ],
    "atac.fastqs_rep1_R2" : [ "/home/SLY69/project/atac/raw/AF124701.R2.fastq.gz" ],
    "atac.fastqs_rep2_R1" : [ "/home/SLY69/project/atac/raw/AF124704.R1.fastq.gz" ],
    "atac.fastqs_rep2_R2" : [ "/home/SLY69/project/atac/raw/AF124704.R2.fastq.gz" ],
        "atac.fastqs_rep3_R1" : [ "/home/SLY69/project/atac/raw/AF124705.R1.fastq.gz" ],
        "atac.fastqs_rep3_R2" : [ "/home/SLY69/project/atac/raw/AF124705.R1.fastq.gz" ],
    "atac.auto_detect_adapter" : true,

    "atac.multimapping" : 6
}

```

## **Troubleshooting result**

If you ran `caper run` without Caper server then Caper automatically runs a troubleshooter for failed workflows. Find troubleshooting result in the bottom of Caper's screen log.

If you ran `caper submit` with a running Caper server then first find your workflow ID (1st column) with `caper list` and run `caper debug [WORKFLOW_ID]`.

Paste troubleshooting result.
```
2021-07-20 13:40:54,466|caper.caper_base|INFO| Creating a timestamped temporary directory. /home/SLY69/project/encode-atac-seq-pipeline/caper_tmp/atac/20210720_134054_466005
2021-07-20 13:40:54,466|caper.caper_runner|INFO| Localizing files on work_dir. /home/SLY69/project/encode-atac-seq-pipeline/caper_tmp/atac/20210720_134054_466005
2021-07-20 13:40:55,131|caper.cromwell|INFO| Installing Womtool JAR... https://github.com/broadinstitute/cromwell/releases/download/59/womtool-59.jar
2021-07-20 13:40:55,131|autouri.autouri|INFO| cp: (a81f2ce3) started. src=https://github.com/broadinstitute/cromwell/releases/download/59/womtool-59.jar, dest=/home/SLY69/.caper/womtool_jar/womtool-59.jar
Traceback (most recent call last):
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cli.py", line 675, in main
    return runner(parsed_args, nonblocking_server=nonblocking_server)
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cli.py", line 226, in runner
    subcmd_run(c, args)
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cli.py", line 370, in subcmd_run
    dry_run=args.dry_run,
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_runner.py", line 433, in run
    self._cromwell.validate(wdl=wdl, inputs=inputs, imports=imports)
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cromwell.py", line 102, in validate
    self.install_womtool()
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cromwell.py", line 481, in install_womtool
    self._womtool, self._womtool_install_dir, 'Womtool JAR'
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cromwell.py", line 33, in install_file
    return AutoURI(f).cp(path)
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/autouri.py", line 348, in cp
    if not self._cp(dest_uri=d):
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/autouri/httpurl.py", line 146, in _cp
    headers=requests.utils.default_headers(),
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/SLY69/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by leepc12** [comment]
Does your cluster allow downloading external files on the internet? Please try this for debugging. 
```
$ wget https://github.com/broadinstitute/cromwell/releases/download/59/womtool-59.jar
```

**Comment by shenlinyong** [comment]
Thank you, I solved it through```wget -o ~/.caper/womtool_jar https://github.com/broadinstitute/cromwell/releases/download/59/womtool-59.jar```

**Comment by shenlinyong** [comment]
My pipline was interrupted. The following is the error message:
```bash
64 2021-07-21 07:24:54,707|caper.cromwell_workflow_monitor|INFO| Task: id=8c515e80-a1cf-4264-8ba7-55353554e8a0, task=atac.align:1, retry=0, status=Done
     65 2021-07-21 07:24:55,959|caper.cromwell_workflow_monitor|INFO| Workflow: id=8c515e80-a1cf-4264-8ba7-55353554e8a0, status=Failed
     66 2021-07-21 07:25:44,031|caper.cromwell_metadata|INFO| Wrote metadata file. /home/SLY69/project/encode-atac-seq-pipeline/atac/8c515e80-a1cf-4264-8ba7-55353554e8a0/metadata.json
     67 2021-07-21 07:25:44,031|caper.cromwell|INFO| Workflow failed. Auto-troubleshooting...
     68 * Started troubleshooting workflow: id=8c515e80-a1cf-4264-8ba7-55353554e8a0, status=Failed
     69 * Found failures JSON object.
     70 [
     71     {
     72         "causedBy": [
     73             {
     74                 "message": "Job atac.macs2_signal_track:2:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute 
     75                 "causedBy": []
     76             },
     77             {
     78                 "causedBy": [],
     79                 "message": "Job atac.call_peak:2:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more 
     80             }
     81         ],
     82         "message": "Workflow failed"
     83     }
     84 ]
     85 * Recursively finding failures in calls (tasks)...
     86 
     87 ==== NAME=atac.macs2_signal_track, STATUS=RetryableFailure, PARENT=
     88 SHARD_IDX=2, RC=1, JOB_ID=87856
```

**Comment by leepc12** [comment]
How much memory and CPU did you reserve for the pipeline?

**Comment by shenlinyong** [comment]
Since I'm new to caper, I didn't set the number of threads and memory, but the default mode. How should I set this up properly? Each fa.zg has 10G in my rawdata .

**Comment by leepc12** [comment]
Please check contents of STDOUT and STDERR files of that failed task. If you find error messages like `Killed` then the job is killed due to out-of-memory. Then try with enough memory like 60GB. Otherwise, please post any helpful log.

**Comment by leepc12** [comment]
Closing this due to inactivity
