### ISSUE TITLE
Error during local conda pipeline execution

### ISSUE THREAD

**Issue by tiagobrc** [ENCODE-DCC/atac-seq-pipeline#34]
Hi,

I was testing the local pipeline with conda. And it threw an error. I can't tell what is the problem by looking this error message. Can you tell me what I could possibly be doing wrong?

This is the command I used:

```
java -jar -Dconfig.file=backends/backend.conf cromwell-34.jar run atac.wdl -i examples/local/ENCSR356KRQ_subsampled.json | tee -a output.txt
```
Thanks!

```
[2018-09-20 16:10:58,17] [info] BackgroundConfigAsyncJobExecutionActor [142a7da3atac.pool_ta:NA:1]: Status change f
rom WaitingForReturnCodeFile to Done
^[[D^[[D^[[D^[f[2018-09-20 16:15:14,03] [info] BackgroundConfigAsyncJobExecutionActor [142a7da3atac.macs2:0:1]: Sta
tus change from WaitingForReturnCodeFile to Done
[2018-09-20 16:15:46,95] [info] BackgroundConfigAsyncJobExecutionActor [142a7da3atac.macs2:1:1]: Status change from
 WaitingForReturnCodeFile to Done
[2018-09-20 16:15:47,22] [error] WorkflowManagerActor Workflow 142a7da3-bbb8-4762-9e12-e11886eb6c0c failed (during 
ExecutingWorkflowState): Job atac.xcor:0:1 exited with return code 1 which has not been declared as a valid return 
code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /home/trezende/atac-seq-pipeline/cromwell-executi
ons/atac/142a7da3-bbb8-4762-9e12-e11886eb6c0c/call-xcor/shard-0/execution/stderr.
 Traceback (most recent call last):
  File "/home/trezende/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_xcor.py", line 102, in <module>
    main()
  File "/home/trezende/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_xcor.py", line 91, in main
    ta_subsampled, args.speak, args.nth, args.out_dir)
  File "/home/trezende/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_xcor.py", line 53, in xcor
    run_shell_cmd(cmd1)
  File "/home/trezende/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_common.py", line 230, in run_shell_cmd
    os.killpg(pgid, signal.SIGKILL)
OSError: [Errno 3] No such process

Job atac.xcor:1:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnRetu
rnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /home/trezende/atac-seq-pipeline/cromwell-executi
ons/atac/142a7da3-bbb8-4762-9e12-e11886eb6c0c/call-xcor/shard-1/execution/stderr.
 Traceback (most recent call last):
  File "/home/trezende/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_xcor.py", line 102, in <module>
    main()
  File "/home/trezende/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_xcor.py", line 91, in main
    ta_subsampled, args.speak, args.nth, args.out_dir)
  File "/home/trezende/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_xcor.py", line 53, in xcor
    run_shell_cmd(cmd1)
  File "/home/trezende/anaconda3/envs/encode-atac-seq-pipeline/bin/encode_common.py", line 230, in run_shell_cmd
    os.killpg(pgid, signal.SIGKILL)
OSError: [Errno 3] No such process

[2018-09-20 16:15:47,22] [info] WorkflowManagerActor WorkflowActor-142a7da3-bbb8-4762-9e12-e11886eb6c0c is in a ter
minal state: WorkflowFailedState
[2018-09-20 16:15:59,19] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2018-09-20 16:16:03,74] [info] Workflow polling stopped

```

**Comment by leepc12** [comment]
Please make a tar ball of all log files and post `debug_34.tar.gz` here.
```
$ find . -type f -name 'stdout' -or -name 'stderr' -or -name 'script' -or \
-name '*.qc' -or -name '*.txt' -or -name '*.log' -or -name '*.png' -or -name '*.pdf' \
| xargs tar -zcvf debug_34.tar.gz
```

**Comment by tiagobrc** [comment]
Hi,

Thank you very much for your help.

Here is the file:

[debug_34.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2403358/debug_34.tar.gz)

**Comment by tiagobrc** [comment]
Hi,

Thank you again for spending your time helping me out. Here is the new tarball. It seems that the error persists.

I will try to use singularity.

[debug_34.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2408197/debug_34.tar.gz)

**Comment by tiagobrc** [comment]
Hi,

I could not use singularity since I don't have root access to my machine. I'am trying the Google Cloud option and the test worked fine. Do you have instructions to how upload our data?

**Comment by tiagobrc** [comment]
> Please try the following things:
> 
> 1. (RECOMMENDED) Try out a singularity method (https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/docs/tutorial_local_singularity.md) instead on Conda one.
> 2. Run the following command line to fix the error and see if it works. If 2) doesn't work please report with a new tar ball and try out method 1).
> 
> ```
> $ source activate encode-atac-seq-pipeline
> $ conda install ncurses ==6.1 -c conda-forge
> ```

Hi ,


Thanks for all support. I could not use Singularity because of admin rights in the server. But I fixed the Conda pipeline by reinstalling Miniconda in the home Directory and Removing the Linuxbrew from the PATH.

Thanks!
