### ISSUE TITLE
Ast has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by gavinjzg** [ENCODE-DCC/atac-seq-pipeline#373]
i run this pipeline ，meet some trouble，how should i deal with it?
## **Describe the bug**
A clear and concise des2022-02-28 15:21:16,489|autouri.autouri|INFO| cp: (898d16d3) done.
2022-02-28 15:21:17,496|caper.cromwell|INFO| Validating WDL/inputs/imports with Womtool...
Traceback (most recent call last):
  File "/home/zjin/anaconda3/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/home/zjin/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 705, in main
    return runner(parsed_args, nonblocking_server=nonblocking_server)
  File "/home/zjin/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 249, in runner
    subcmd_run(c, args)
  File "/home/zjin/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 401, in subcmd_run
    dry_run=args.dry_run,
  File "/home/zjin/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/caper_runner.py", line 462, in run
    self._cromwell.validate(wdl=wdl, inputs=inputs, imports=imports)
  File "/home/zjin/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/cromwell.py", line 155, in validate
    'RC={rc}\nSTDERR={stderr}'.format(rc=th.returncode, stderr=stderr)
caper.cromwell.WomtoolValidationFailed: RC=1
STDERR=Exception in thread "main" java.lang.BootstrapMethodError: java.lang.UnsupportedClassVersionError: wdl/draft3/parser/WdlParser$Ast has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at wdl.draft3.transforms.ast2wdlom.package$.<init>(ast2wdlom.scala:16)
	at wdl.draft3.transforms.ast2wdlom.package$.<clinit>(ast2wdlom.scala)
	at languages.wdl.draft3.WdlDraft3LanguageFactory.makeWomBundle(WdlDraft3LanguageFactory.scala:64)
	at languages.wdl.draft3.WdlDraft3LanguageFactory$$anon$1.call(WdlDraft3LanguageFactory.scala:79)
	at languages.wdl.draft3.WdlDraft3LanguageFactory$$anon$1.call(WdlDraft3LanguageFactory.scala:78)
	at cromwell.languages.util.ParserCache.$anonfun$retrieveOrCalculate$2(ParserCache.scala:35)
	at scala.Option.getOrElse(Option.scala:189)
	at cromwell.languages.util.ParserCache.retrieveOrCalculate(ParserCache.scala:35)
	at cromwell.languages.util.ParserCache.retrieveOrCalculate$(ParserCache.scala:25)
	at languages.wdl.draft3.WdlDraft3LanguageFactory.retrieveOrCalculate(WdlDraft3LanguageFactory.scala:30)
	at languages.wdl.draft3.WdlDraft3LanguageFactory.$anonfun$getWomBundle$2(WdlDraft3LanguageFactory.scala:86)
	at scala.util.Either.flatMap(Either.scala:341)
	at languages.wdl.draft3.WdlDraft3LanguageFactory.getWomBundle(WdlDraft3LanguageFactory.scala:85)
	at womtool.input.WomGraphMaker$.$anonfun$getBundleAndFactory$1(WomGraphMaker.scala:40)
	at scala.util.Either.flatMap(Either.scala:341)
	at womtool.input.WomGraphMaker$.getBundleAndFactory(WomGraphMaker.scala:31)
	at womtool.input.WomGraphMaker$.fromFiles(WomGraphMaker.scala:47)
	at womtool.validate.Validate$.validate(Validate.scala:26)
	at womtool.WomtoolMain$.dispatchCommand(WomtoolMain.scala:54)
	at womtool.WomtoolMain$.runWomtool(WomtoolMain.scala:161)
	at womtool.WomtoolMain$.delayedEndpoint$womtool$WomtoolMain$1(WomtoolMain.scala:166)
	at womtool.WomtoolMain$delayedInit$body.apply(WomtoolMain.scala:27)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at womtool.WomtoolMain$.main(WomtoolMain.scala:27)
	at womtool.WomtoolMain.main(WomtoolMain.scala)
Caused by: java.lang.UnsupportedClassVersionError: wdl/draft3/parser/WdlParser$Ast has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 morecription of what the problem is.

## **OS/Platform**
- OS/Platform: [e.g. Ubuntu 18.04, Google Cloud, Stanford Sherlock/SCG cluster, ...]
- Conda version: If you used Conda (`conda 4.11.0`).
- Pipeline version: []
- Caper version: [e.g. v2.1.3]

## **Input JSON file**
sample

**Comment by leepc12** [comment]
Upgrade your Java version to >=11

**Comment by gavinjzg** [comment]
i have upgrade the java
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21)
OpenJDK 64-Bit Server VM JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21, mixed mode)

but i meet a new trouble，just like this.can you give me the hint? i have read the issue280,but can' solve it.


(encode-atac-seq-pipeline) [zjin@www atac]$ caper run /home/zjin/atac/atac-seq-pipeline/atac.wdl -i 1.json  --out-dir out  --backend-file your_backend_file_to_override_on_sync.conf
/home/zjin/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py:11: MatplotlibDeprecationWarning: 
The support for Qt4  was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  from matplotlib.backends.qt_compat import QtGui
2022-03-01 17:09:37,947|caper.cli|INFO| Cromwell stdout: /home/zjin/atac/cromwell.out
2022-03-01 17:09:37,948|caper.caper_base|INFO| Creating a timestamped temporary directory. /home/zjin/atac/out/.caper_tmp/atac/20220301_170937_947783
2022-03-01 17:09:37,948|caper.caper_runner|INFO| Localizing files on work_dir. /home/zjin/atac/out/.caper_tmp/atac/20220301_170937_947783
2022-03-01 17:09:38,288|autouri.autouri|INFO| cp: (08e410fe) started. src=https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15/@@download/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz, dest=/home/zjin/atac/out/.caper_tmp/caf534ed3cf684406e731d19be272b4a/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz
2022-03-01 17:10:47,462|autouri.autouri|INFO| cp: (08e410fe) done.
2022-03-01 17:10:47,465|autouri.autouri|INFO| cp: (ab7f014f) started. src=https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15_mito_only/@@download/GRCh38_no_alt_analysis_set_GCA_000001405.15_mito_only.fasta.gz, dest=/home/zjin/atac/out/.caper_tmp/f43b63a83784d3ec8055f1a22168ed89/GRCh38_no_alt_analysis_set_GCA_000001405.15_mito_only.fasta.gz
2022-03-01 17:10:49,463|autouri.autouri|INFO| cp: (ab7f014f) done.
2022-03-01 17:10:49,465|autouri.autouri|INFO| cp: (2c658750) started. src=https://www.encodeproject.org/files/ENCFF356LFX/@@download/ENCFF356LFX.bed.gz, dest=/home/zjin/atac/out/.caper_tmp/f183dcba5d34f959d8b55ed438ee2e22/ENCFF356LFX.bed.gz
2022-03-01 17:10:51,497|autouri.autouri|INFO| cp: (2c658750) done.
2022-03-01 17:10:53,550|autouri.autouri|INFO| cp: (04b15329) started. src=https://www.encodeproject.org/files/GRCh38_EBV.chrom.sizes/@@download/GRCh38_EBV.chrom.sizes.tsv, dest=/home/zjin/atac/out/.caper_tmp/c52f52c7bfa357f55a39b1de7e4d0b0c/GRCh38_EBV.chrom.sizes.tsv
2022-03-01 17:10:55,535|autouri.autouri|INFO| cp: (04b15329) done.
2022-03-01 17:10:55,536|autouri.autouri|INFO| cp: (d33e2da7) started. src=https://www.encodeproject.org/files/ENCFF110MCL/@@download/ENCFF110MCL.tar.gz, dest=/home/zjin/atac/out/.caper_tmp/3ff4ac4c3f59d096b1a3842a182072ae/ENCFF110MCL.tar.gz
2022-03-01 17:16:56,415|autouri.autouri|INFO| cp: (d33e2da7) done.
2022-03-01 17:16:56,419|autouri.autouri|INFO| cp: (1494ff4b) started. src=https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15_mito_only_bowtie2_index/@@download/GRCh38_no_alt_analysis_set_GCA_000001405.15_mito_only_bowtie2_index.tar.gz, dest=/home/zjin/atac/out/.caper_tmp/df5193e07055d13c48be59bacd0f56b8/GRCh38_no_alt_analysis_set_GCA_000001405.15_mito_only_bowtie2_index.tar.gz
2022-03-01 17:16:58,887|autouri.autouri|INFO| cp: (1494ff4b) done.
2022-03-01 17:16:58,888|autouri.autouri|INFO| cp: (e307e3f4) started. src=https://www.encodeproject.org/files/ENCFF643CGH/@@download/ENCFF643CGH.tar.gz, dest=/home/zjin/atac/out/.caper_tmp/8c692fba4640609720272154ab0faa30/ENCFF643CGH.tar.gz
2022-03-01 17:22:48,630|autouri.autouri|INFO| cp: (e307e3f4) done.
2022-03-01 17:22:48,631|autouri.autouri|INFO| cp: (2681f609) started. src=https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15_mito_only_bwa_index/@@download/GRCh38_no_alt_analysis_set_GCA_000001405.15_mito_only_bwa_index.tar.gz, dest=/home/zjin/atac/out/.caper_tmp/d3dff25534e93d893902540d81e4f475/GRCh38_no_alt_analysis_set_GCA_000001405.15_mito_only_bwa_index.tar.gz
2022-03-01 17:22:50,907|autouri.autouri|INFO| cp: (2681f609) done.
2022-03-01 17:22:50,908|autouri.autouri|INFO| cp: (d8e672bb) started. src=https://www.encodeproject.org/files/ENCFF766FGL/@@download/ENCFF766FGL.bed.gz, dest=/home/zjin/atac/out/.caper_tmp/f16cc7892540d7a9bc3207cc44eb8288/ENCFF766FGL.bed.gz
2022-03-01 17:22:53,695|autouri.autouri|INFO| cp: (d8e672bb) done.
2022-03-01 17:22:53,696|autouri.autouri|INFO| cp: (914bd0f7) started. src=https://www.encodeproject.org/files/ENCFF304XEX/@@download/ENCFF304XEX.bed.gz, dest=/home/zjin/atac/out/.caper_tmp/805e179275a9c0fb7a37def40c4312d1/ENCFF304XEX.bed.gz
2022-03-01 17:22:58,812|autouri.autouri|INFO| cp: (914bd0f7) done.
2022-03-01 17:22:58,812|autouri.autouri|INFO| cp: (ab2a6ffd) started. src=https://www.encodeproject.org/files/ENCFF140XLU/@@download/ENCFF140XLU.bed.gz, dest=/home/zjin/atac/out/.caper_tmp/0cbd2c602ddad252bc39729fc8a29286/ENCFF140XLU.bed.gz
2022-03-01 17:23:03,959|autouri.autouri|INFO| cp: (ab2a6ffd) done.
2022-03-01 17:23:03,960|autouri.autouri|INFO| cp: (585e94c6) started. src=https://www.encodeproject.org/files/ENCFF212UAV/@@download/ENCFF212UAV.bed.gz, dest=/home/zjin/atac/out/.caper_tmp/1d3aa436b05f16a509edb94789c061d3/ENCFF212UAV.bed.gz
2022-03-01 17:23:10,599|autouri.autouri|INFO| cp: (585e94c6) done.
2022-03-01 17:23:10,600|autouri.autouri|INFO| cp: (7a70cb07) started. src=https://storage.googleapis.com/encode-pipeline-genome-data/hg38/ataqc/hg38_dnase_avg_fseq_signal_formatted.txt.gz, dest=/home/zjin/atac/out/.caper_tmp/3b39284516e676ea52238f0636c0bbbf/hg38_dnase_avg_fseq_signal_formatted.txt.gz
2022-03-01 17:23:13,548|autouri.autouri|INFO| cp: (7a70cb07) done.
2022-03-01 17:23:13,549|autouri.autouri|INFO| cp: (eb01f0bd) started. src=https://storage.googleapis.com/encode-pipeline-genome-data/hg38/ataqc/hg38_celltype_compare_subsample.bed.gz, dest=/home/zjin/atac/out/.caper_tmp/c73f434c3fa4f3f54bc2ecad09c065c2/hg38_celltype_compare_subsample.bed.gz
2022-03-01 17:23:14,329|autouri.autouri|INFO| cp: (eb01f0bd) done.
2022-03-01 17:23:14,330|autouri.autouri|INFO| cp: (991ff11b) started. src=https://storage.googleapis.com/encode-pipeline-genome-data/hg38/ataqc/hg38_dnase_avg_fseq_signal_metadata.txt, dest=/home/zjin/atac/out/.caper_tmp/a9745b33b4ffdd83d7d2c5a7d3c8036a/hg38_dnase_avg_fseq_signal_metadata.txt
2022-03-01 17:23:14,667|autouri.autouri|INFO| cp: (991ff11b) done.
2022-03-01 17:23:14,671|autouri.autouri|INFO| cp: (da2e17ea) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep1/pair1/ENCFF341MYG.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/7ded2935aace2939d00d8fb5b47867ae/ENCFF341MYG.subsampled.400.fastq.gz
2022-03-01 17:23:15,751|autouri.autouri|INFO| cp: (da2e17ea) done.
2022-03-01 17:23:15,752|autouri.autouri|INFO| cp: (b5ef68d4) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep1/pair1/ENCFF106QGY.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/ca04bcf10cb8ac66068bc5f15a436f03/ENCFF106QGY.subsampled.400.fastq.gz
2022-03-01 17:23:16,766|autouri.autouri|INFO| cp: (b5ef68d4) done.
2022-03-01 17:23:16,767|autouri.autouri|INFO| cp: (b89c6f60) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep1/pair2/ENCFF248EJF.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/27d48f46ef8e2ac6910ac87f3ccbe163/ENCFF248EJF.subsampled.400.fastq.gz
2022-03-01 17:23:17,848|autouri.autouri|INFO| cp: (b89c6f60) done.
2022-03-01 17:23:17,848|autouri.autouri|INFO| cp: (306b42c6) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep1/pair2/ENCFF368TYI.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/a7ff3728754970409a3d2f093cf38b52/ENCFF368TYI.subsampled.400.fastq.gz
2022-03-01 17:23:18,897|autouri.autouri|INFO| cp: (306b42c6) done.
2022-03-01 17:23:18,897|autouri.autouri|INFO| cp: (fe6d7e1a) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep2/pair1/ENCFF641SFZ.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/3c6d0cab14c16eaeaf22560de63ac804/ENCFF641SFZ.subsampled.400.fastq.gz
2022-03-01 17:23:19,712|autouri.autouri|INFO| cp: (fe6d7e1a) done.
2022-03-01 17:23:19,713|autouri.autouri|INFO| cp: (d7425de2) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep2/pair1/ENCFF751XTV.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/218fa2f732797e84fa153d479e7dcafb/ENCFF751XTV.subsampled.400.fastq.gz
2022-03-01 17:23:20,575|autouri.autouri|INFO| cp: (d7425de2) done.
2022-03-01 17:23:20,575|autouri.autouri|INFO| cp: (8143d280) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep2/pair1/ENCFF927LSG.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/dfea21b33ce8e0ab13fd158e7e812586/ENCFF927LSG.subsampled.400.fastq.gz
2022-03-01 17:23:21,408|autouri.autouri|INFO| cp: (8143d280) done.
2022-03-01 17:23:21,409|autouri.autouri|INFO| cp: (4a41f94c) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep2/pair1/ENCFF859BDM.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/44b253b6db9e0ea8de62aea604878556/ENCFF859BDM.subsampled.400.fastq.gz
2022-03-01 17:23:22,347|autouri.autouri|INFO| cp: (4a41f94c) done.
2022-03-01 17:23:22,348|autouri.autouri|INFO| cp: (c6289997) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep2/pair1/ENCFF193RRC.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/db6282276790c12cb2e76b1ed84fb26f/ENCFF193RRC.subsampled.400.fastq.gz
2022-03-01 17:23:23,264|autouri.autouri|INFO| cp: (c6289997) done.
2022-03-01 17:23:23,264|autouri.autouri|INFO| cp: (096183db) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep2/pair1/ENCFF366DFI.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/88672b6fafd695007baf55f7f9757fed/ENCFF366DFI.subsampled.400.fastq.gz
2022-03-01 17:23:24,190|autouri.autouri|INFO| cp: (096183db) done.
2022-03-01 17:23:24,190|autouri.autouri|INFO| cp: (1a6622b5) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep2/pair2/ENCFF031ARQ.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/713c163a0f65d7350956d72323fc0310/ENCFF031ARQ.subsampled.400.fastq.gz
2022-03-01 17:23:25,007|autouri.autouri|INFO| cp: (1a6622b5) done.
2022-03-01 17:23:25,008|autouri.autouri|INFO| cp: (80aa297d) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep2/pair2/ENCFF590SYZ.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/1654703543de9eb53b95469e4c26856c/ENCFF590SYZ.subsampled.400.fastq.gz
2022-03-01 17:23:25,872|autouri.autouri|INFO| cp: (80aa297d) done.
2022-03-01 17:23:25,873|autouri.autouri|INFO| cp: (a3802a0b) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep2/pair2/ENCFF734PEQ.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/69b00bab505645c65eb5957a0b6b2392/ENCFF734PEQ.subsampled.400.fastq.gz
2022-03-01 17:23:26,724|autouri.autouri|INFO| cp: (a3802a0b) done.
2022-03-01 17:23:26,725|autouri.autouri|INFO| cp: (da320b67) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep2/pair2/ENCFF007USV.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/3810785b7e92ca7d6c4612c20c3ca534/ENCFF007USV.subsampled.400.fastq.gz
2022-03-01 17:23:27,664|autouri.autouri|INFO| cp: (da320b67) done.
2022-03-01 17:23:27,665|autouri.autouri|INFO| cp: (5de30c04) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep2/pair2/ENCFF886FSC.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/482c9ce8ed007c251adca385c7d4ce95/ENCFF886FSC.subsampled.400.fastq.gz
2022-03-01 17:23:28,588|autouri.autouri|INFO| cp: (5de30c04) done.
2022-03-01 17:23:28,589|autouri.autouri|INFO| cp: (b80b50c1) started. src=https://storage.googleapis.com/encode-pipeline-test-samples/encode-atac-seq-pipeline/ENCSR356KRQ/fastq_subsampled/rep2/pair2/ENCFF573UXK.subsampled.400.fastq.gz, dest=/home/zjin/atac/out/.caper_tmp/a3a22d635ec162098e31bcea6655fb34/ENCFF573UXK.subsampled.400.fastq.gz
2022-03-01 17:23:29,516|autouri.autouri|INFO| cp: (b80b50c1) done.
2022-03-01 17:23:30,967|caper.cromwell|INFO| Validating WDL/inputs/imports with Womtool...
2022-03-01 17:23:34,487|caper.cromwell|INFO| Passed Womtool validation.
2022-03-01 17:23:34,488|caper.caper_runner|INFO| launching run: wdl=/home/zjin/atac/atac-seq-pipeline/atac.wdl, inputs=/home/zjin/atac/out/.caper_tmp/home/zjin/atac/1.local.json, backend_conf=/home/zjin/atac/out/.caper_tmp/atac/20220301_170937_947783/backend.conf
2022-03-01 17:23:44,419|caper.cromwell_workflow_monitor|INFO| Workflow: id=03a5337d-1279-4f1c-83f2-30077f428866, status=Submitted
2022-03-01 17:23:44,470|caper.cromwell_workflow_monitor|INFO| Workflow: id=03a5337d-1279-4f1c-83f2-30077f428866, status=Running
2022-03-01 17:23:59,322|caper.cromwell_workflow_monitor|INFO| Task: id=03a5337d-1279-4f1c-83f2-30077f428866, task=atac.read_genome_tsv:-1, retry=0, status=Started, job_id=5539
2022-03-01 17:23:59,328|caper.cromwell_workflow_monitor|INFO| Task: id=03a5337d-1279-4f1c-83f2-30077f428866, task=atac.read_genome_tsv:-1, retry=0, status=Done
2022-03-01 17:23:59,734|caper.cromwell_workflow_monitor|INFO| Workflow: id=03a5337d-1279-4f1c-83f2-30077f428866, status=Failed
2022-03-01 17:24:10,383|caper.cromwell_metadata|INFO| Wrote metadata file. /home/zjin/atac/out/atac/03a5337d-1279-4f1c-83f2-30077f428866/metadata.json
2022-03-01 17:24:10,383|caper.cromwell|INFO| Workflow failed. Auto-troubleshooting...
* Started troubleshooting workflow: id=03a5337d-1279-4f1c-83f2-30077f428866, status=Failed
* Found failures JSON object.
[
    {
        "causedBy": [
            {
                "causedBy": [],
                "message": "Job atac.read_genome_tsv:NA:1 exited with return code -1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            }
        ],
        "message": "Workflow failed"
    }
]
* Recursively finding failures in calls (tasks)...

==== NAME=atac.read_genome_tsv, STATUS=Failed, PARENT=
SHARD_IDX=-1, RC=-1, JOB_ID=5539
START=2022-03-01T09:23:56.548Z, END=2022-03-01T09:23:59.359Z
STDOUT=/home/zjin/atac/out/atac/03a5337d-1279-4f1c-83f2-30077f428866/call-read_genome_tsv/execution/stdout
STDERR=/home/zjin/atac/out/atac/03a5337d-1279-4f1c-83f2-30077f428866/call-read_genome_tsv/execution/stderr
STDERR_BACKGROUND_CONTENTS=
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
cat: /home/zjin/atac/out/atac/03a5337d-1279-4f1c-83f2-30077f428866/call-read_genome_tsv/execution/docker_cid: No such file or directory
"docker wait" requires at least 1 argument.
See 'docker wait --help'.

Usage:  docker wait CONTAINER [CONTAINER...]

Block until one or more containers stop, then print their exit codes
cat: /home/zjin/atac/out/atac/03a5337d-1279-4f1c-83f2-30077f428866/call-read_genome_tsv/execution/docker_cid: No such file or directory
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers

2022-03-01 17:24:10,385|caper.nb_subproc_thread|ERROR| Cromwell failed. returncode=1
2022-03-01 17:24:10,385|caper.cli|ERROR| Check stdout in /home/zjin/atac/cromwell.out

**Comment by leepc12** [comment]
Found this in your log. It seems like you don't have permission to use docker. Did you run it with `--docker`? If so then ask your admin to add you to `docker` group.
```
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
```
If you have singularity installed on your system then use `--singularity` instead. Or you can install Miniconda3 and pipeline's  Conda environment (`scripts/install_conda_env.sh`) and then use `--conda`.

**Comment by gavinjzg** [comment]
thanks,i get it
