### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by gavinjzg** [ENCODE-DCC/atac-seq-pipeline#380]
## **Describe the bug**
when i append the tss file ,it show this mistake

## **OS/Platform**
- Caper version: 2.1.3

## **Caper configuration file**
2022-04-11 21:37:00,784|caper.cli|INFO| Cromwell stdout: /home/zjin/atac/cromwell.out.2
2022-04-11 21:37:00,786|caper.caper_base|INFO| Creating a timestamped temporary directory. /home/zjin/atac/total-2/.caper_tmp/atac/20220411_213700_785801
2022-04-11 21:37:00,786|caper.caper_runner|INFO| Localizing files on work_dir. /home/zjin/atac/total-2/.caper_tmp/atac/20220411_213700_785801
2022-04-11 21:37:01,777|caper.caper_workflow_opts|INFO| Conda environment name found in WDL metadata. wdl=/home/zjin/atac/atac.wdl, s=encode-atac-seq-pipeline
2022-04-11 21:37:01,780|caper.cromwell|INFO| Validating WDL/inputs/imports with Womtool...
2022-04-11 21:37:05,192|caper.cromwell|INFO| Passed Womtool validation.
2022-04-11 21:37:05,194|caper.caper_runner|INFO| launching run: wdl=/home/zjin/atac/atac.wdl, inputs=/home/zjin/atac/atac.json, backend_conf=/home/zjin/atac/total-2/.caper_tmp/atac/20220411_213700_785801/backend.conf
2022-04-11 21:37:18,138|caper.cromwell_workflow_monitor|INFO| Workflow: id=4b3b3cdf-8c42-415b-9790-1621d79c1fe5, status=Submitted
2022-04-11 21:37:18,248|caper.cromwell_workflow_monitor|INFO| Workflow: id=4b3b3cdf-8c42-415b-9790-1621d79c1fe5, status=Running
2022-04-11 21:37:33,006|caper.cromwell_workflow_monitor|INFO| Task: id=4b3b3cdf-8c42-415b-9790-1621d79c1fe5, task=atac.read_genome_tsv:-1, retry=0, status=Started, job_id=57986
2022-04-11 21:37:33,013|caper.cromwell_workflow_monitor|INFO| Task: id=4b3b3cdf-8c42-415b-9790-1621d79c1fe5, task=atac.read_genome_tsv:-1, retry=0, status=WaitingForReturnCode
2022-04-11 21:37:37,814|caper.cromwell_workflow_monitor|INFO| Task: id=4b3b3cdf-8c42-415b-9790-1621d79c1fe5, task=atac.read_genome_tsv:-1, retry=0, status=Done
2022-04-11 21:37:38,764|caper.cromwell_workflow_monitor|INFO| Workflow: id=4b3b3cdf-8c42-415b-9790-1621d79c1fe5, status=Failed
2022-04-11 21:37:54,026|caper.cromwell_metadata|INFO| Wrote metadata file. /home/zjin/atac/total-2/atac/4b3b3cdf-8c42-415b-9790-1621d79c1fe5/metadata.json
2022-04-11 21:37:54,027|caper.cromwell|INFO| Workflow failed. Auto-troubleshooting...
* Started troubleshooting workflow: id=4b3b3cdf-8c42-415b-9790-1621d79c1fe5, status=Failed
* Found failures JSON object.
[
    {
        "message": "Workflow failed",
        "causedBy": [
            {
                "causedBy": [],
                "message": "Job atac.read_genome_tsv:NA:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            }
        ]
    }
]
* Recursively finding failures in calls (tasks)...

==== NAME=atac.read_genome_tsv, STATUS=Failed, PARENT=
SHARD_IDX=-1, RC=1, JOB_ID=57986
START=2022-04-11T13:37:30.035Z, END=2022-04-11T13:37:37.844Z
STDOUT=/home/zjin/atac/total-2/atac/4b3b3cdf-8c42-415b-9790-1621d79c1fe5/call-read_genome_tsv/execution/stdout
STDERR=/home/zjin/atac/total-2/atac/4b3b3cdf-8c42-415b-9790-1621d79c1fe5/call-read_genome_tsv/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
ValueError: not enough values to unpack (expected 2, got 1)

STDERR_BACKGROUND_CONTENTS=
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
ValueError: not enough values to unpack (expected 2, got 1)

2022-04-11 21:37:54,028|caper.nb_subproc_thread|ERROR| Cromwell failed. returncode=1
2022-04-11 21:37:54,029|caper.cli|ERROR| Check stdout in /home/zjin/atac/cromwell.out.2

## **Input JSON file**
{   
    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "/home/zjin/atac/yxiang_test/02.ensembl_susScr11_encode_atac_seq_no_scaffold/ensembl_susScr11_encode_atac_seq_no_scaffold.tsv",
    "atac.fastqs_rep1_R1" : ["/home/zjin/data/4-1/JM_R1.fq.gz"],
    "atac.fastqs_rep1_R2" : ["/home/zjin/data/4-1/JM_R2.fq.gz"],
    "atac.paired_end" : true,
    "atac.auto_detect_adapter" : true,
    "atac.enable_xcor" : true,
    "atac.title" : "test",
    "atac.description" :"wrsm ",
    "atac.gensz" : "2497530654"
    
}

## **tss.file**
1	88626695	88650761	ENSECAG00000040809.1	0	+
1	89195185	89196911	ENSECAG00000033865.2	0	-
1	126616963	126728581	ENSECAG00000020259.3	0	-
1	89238505	89269098	ENSECAG00000034397.1	0	-
1	6434	15716	ENSECAG00000012421.3	0	+
1	158974107	159019894	ENSECAG00000042840.1	0	-
1	127055125	127057675	ENSECAG00000043695.1	0	-
1	159041627	159044523	ENSECAG00000030042.2	0	+
1	159049816	159051842	ENSECAG00000001454.2	0	+
1	159101630	159107451	ENSECAG00000001538.3	0	-

## tsv.file
genome_name     ensembl_susScr11_encode_atac_seq_no_scaffold
ref_fa  /home/zjin/atac/yxiang_test/02.ensembl_susScr11_encode_atac_seq_no_scaffold/./Equus_caballus.EquCab2.dna.toplevel.fa.gz
ref_mito_fa     /home/zjin/atac/yxiang_test/02.ensembl_susScr11_encode_atac_seq_no_scaffold/./Equus_caballus.EquCab2.dna.toplevel.MT.fa.gz
mito_chr_name   MT
regex_bfilt_peak_chr_name       .*
chrsz   /home/zjin/atac/yxiang_test/02.ensembl_susScr11_encode_atac_seq_no_scaffold/./ensembl_susScr11_encode_atac_seq_no_scaffold.chrom.sizes
gensz   2474929062
bowtie2_idx_tar /home/zjin/atac/yxiang_test/02.ensembl_susScr11_encode_atac_seq_no_scaffold/./bowtie2_index/Equus_caballus.EquCab2.dna.toplevel.fa.tar.gz
bowtie2_mito_idx_tar    /home/zjin/atac/yxiang_test/02.ensembl_susScr11_encode_atac_seq_no_scaffold/./bowtie2_index/Equus_caballus.EquCab2.dna.toplevel.MT.fa.tar.gz
tss     /home/zjin/data/refsq/1.bed

**Comment by leepc12** [comment]
It looks like your genome TSV or TSS is not in a valid format.
Use TAB instead of SPACE in the TSS file.

Example.
```
$ zcat /mnt/data/pipeline_genome_data/hg38/ataqc/hg38_gencode_v29_tss_unique.bed.gz | head
chr1    65417   65418   ENSG00000186092.6       0       +
chr1    451697  451698  ENSG00000284733.1       0       -
chr1    686673  686674  ENSG00000284662.1       0       -
chr1    923926  923927  ENSG00000187634.11      0       +
chr1    959309  959310  ENSG00000188976.10      0       -
chr1    960585  960586  ENSG00000187961.13      0       +
chr1    966495  966496  ENSG00000187583.10      0       +
chr1    982093  982094  ENSG00000187642.9       0       -
chr1    1000172 1000173 ENSG00000188290.10      0       -
chr1    1001136 1001137 ENSG00000187608.9       0       +
```
