### ISSUE TITLE
Error during the end of pipeline at call-reproducibility_overlap step, using real data.

### ISSUE THREAD

**Issue by tiagobrc** [ENCODE-DCC/atac-seq-pipeline#39]
Hi, first things first, thanks for all the help and for this beautiful pipeline.

I was able to install and the test ran smoothly. Now I tried to run my real samples and it broke in the very end. I can't explain why. Can you try to help me understand what is the issue? I am attaching all the logs of the run.

```
cat `./call-reproducibility_overlap/execution/stderr`

 Traceback (most recent call last):
  File "/ru-auth/local/home/trezende/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_reproducibility_qc.py", line 154, in <module>
    main()
  File "/ru-auth/local/home/trezende/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_reproducibility_qc.py", line 50, in main
    args = parse_arguments()
  File "/ru-auth/local/home/trezende/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_reproducibility_qc.py", line 42, in parse_arguments
    'Invalid number of peak files or --peak-pr.')
argparse.ArgumentTypeError: Invalid number of peak files or --peak-pr.

```

So, I built the mm10 mouse database successfully and tried the pipeline.

There is any way of trying to fix/test it without having to start since from the beginning? Can the pipeline skip the successfully and finished things?
[debug_34.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2426742/debug_34.tar.gz)

**Comment by leepc12** [comment]
Please read issue #38 about resuming pipelines.

**Comment by leepc12** [comment]
Please attach your input JSON file too.

**Comment by tiagobrc** [comment]
```
{
    "atac.pipeline_type" : "atac",
    "atac.genome_tsv" : "/ru-auth/local/home/trezende/atac-seq-pipeline/mm10/mm10.tsv",
    "atac.fastqs" : [
        [
            ["/data_alpha/home/trezende/trezende/Mariy/FirstBatch/raw/ATAC/exTreg-IEL1_S3_R1_001.fastq.gz",
             "/data_alpha/home/trezende/trezende/Mariy/FirstBatch/raw/ATAC/exTreg-IEL1_S3_R2_001.fastq.gz"]
        ],
         
        [
            ["/data_alpha/home/trezende/trezende/Mariy/FirstBatch/raw/ATAC/IEL-1_S1_R1_001.fastq.gz",
             "/data_alpha/home/trezende/trezende/Mariy/FirstBatch/raw/ATAC/IEL-1_S1_R2_001.fastq.gz"]
        ],

         [
            ["/data_alpha/home/trezende/trezende/Mariy/FirstBatch/raw/ATAC/Treg-1_S2_R1_001.fastq.gz",
             "/data_alpha/home/trezende/trezende/Mariy/FirstBatch/raw/ATAC/Treg-1_S2_R2_001.fastq.gz"]
        ],
         [
            ["/data_alpha/home/trezende/trezende/Mariy/SecondBatch/raw/ATAC2/exTreg_IEL_S8_R1_001.fastq.gz",
             "/data_alpha/home/trezende/trezende/Mariy/SecondBatch/raw/ATAC2/exTreg_IEL_S8_R2_001.fastq.gz"]
        ],
         [
            ["/data_alpha/home/trezende/trezende/Mariy/SecondBatch/raw/ATAC2/exTreg_S7_R1_001.fastq.gz",
             "/data_alpha/home/trezende/trezende/Mariy/SecondBatch/raw/ATAC2/exTreg_S7_R2_001.fastq.gz"]
        ],
          [
            ["/data_alpha/home/trezende/trezende/Mariy/SecondBatch/raw/ATAC2/IEL_S5_R1_001.fastq.gz",
             "/data_alpha/home/trezende/trezende/Mariy/SecondBatch/raw/ATAC2/IEL_S5_R2_001.fastq.gz"]
        ],
         [
            ["/data_alpha/home/trezende/trezende/Mariy/SecondBatch/raw/ATAC2/Treg_S6_R1_001.fastq.gz",
             "/data_alpha/home/trezende/trezende/Mariy/SecondBatch/raw/ATAC2/Treg_S6_R2_001.fastq.gz"]
        ]
  

],

    "atac.paired_end" : true,
    "atac.multimapping" : 4,

    "atac.trim_adapter.auto_detect_adapter" : true,
    "atac.trim_adapter.cpu" : 5,

    "atac.bowtie2.cpu" : 16,
    "atac.bowtie2.mem_mb" : 24000,

    "atac.filter.cpu" : 4,
    "atac.filter.mem_mb" : 12000,

    "atac.macs2_mem_mb" : 16000,

    "atac.smooth_win" : 73,
    "atac.enable_idr" : true,
    "atac.idr_thresh" : 0.05,

    "atac.qc_report.name" : "Mariya ATAC",
    "atac.qc_report.desc" : "ATAC-seq on Floxed ThPok IELs"
}

```

**Comment by tiagobrc** [comment]
But they are single replicates from different samples. Do to a separate run for each of them? 

Thank you!

**Comment by leepc12** [comment]
@tiagobrc: Yes.

**Comment by tiagobrc** [comment]
Ok, Thank you for all your help!
