### ISSUE TITLE
ERROR when Validating WDL/inputs/imports with Womtool

### ISSUE THREAD

**Issue by wangxiangxiu** [ENCODE-DCC/atac-seq-pipeline#395]
## **Describe the bug**
caper.cromwell.WomtoolValidationFailed: RC=1

## **OS/Platform**
- OS/Platform: [e.g. Ubuntu 18.04, Google Cloud, Stanford Sherlock/SCG cluster, ...]
- Conda version: 4.13.0
- Pipeline version: latest
- Caper version: 2.2.2

## **Caper configuration file**
Paste contents of `~/.caper/default.conf`.
```
backend=local

# Local directory for localized files and Cromwell's intermediate files.
# If not defined then Caper will make .caper_tmp/ on CWD or `local-out-dir`.
# /tmp is not recommended since Caper store localized data files here.
local-loc-dir=/home/data/t0302015/Shear_stress_data/ATAC_seq/git_pipeline/caper_tmp

cromwell=/home/data/t0302015/.caper/cromwell_jar/cromwell-82.jar
womtool=/home/data/t0302015/.caper/womtool_jar/womtool-82.jar

```

## **Input JSON file**
Paste contents of your input JSON file.
```
{
        "atac.pipeline_type" : "atac",
        "atac.genome_tsv" : "https://storage.googleapis.com/encode-pipeline-genome-data/genome_tsv/v4/hg38.tsv",
        "atac.fastqs_rep1_R1" : ["/home/data/t0302015/Shear_stress_data/ATAC_seq/SRR8734980_1.fastq.gz"],
        "atac.fastqs_rep1_R2" : ["/home/data/t0302015/Shear_stress_data/ATAC_seq/SRR8734980_2.fastq.gz"],
        "atac.fastqs_rep2_R1" : ["/home/data/t0302015/Shear_stress_data/ATAC_seq/SRR8734981_1.fastq.gz"],
        "atac.fastqs_rep2_R2" : ["/home/data/t0302015/Shear_stress_data/ATAC_seq/SRR8734981_2.fastq.gz"],
        "atac.paired_end" : true,
        "atac.auto_detect_adapter" : true,
        "atac.enable_xcor" : true,
        "atac.title" : "AdNULL samples",
        "atac.description" : "ATAC-seq on HUVECs"
}

```
##
caper run /home/data/t0302015/bin/atac-seq-pipeline/atac.wdl -i sampled.json --singularity
caper run /home/data/t0302015/bin/atac-seq-pipeline/atac.wdl -i sampled.json --conda

2022-08-17 13:33:09,147|caper.caper_workflow_opts|INFO| Singularity image found in WDL metadata. wdl=/home/data/t0302015/bin/atac-seq-pipeline/atac.wdl, s=https://encode-pipeline-singularity-image.s3.us-west-2.amazonaws.com/atac-seq-pipeline_v2.2.0.sif
2022-08-17 13:33:09,160|caper.cromwell|INFO| Validating WDL/inputs/imports with Womtool...
2022-08-17 13:33:09,173|caper.nb_subproc_thread|ERROR| Subprocess failed. returncode=1
Traceback (most recent call last):
  File "/home/data/t0302015/miniconda3/bin/caper", line 13, in <module>
    main()
  File "/home/data/t0302015/miniconda3/lib/python3.9/site-packages/caper/cli.py", line 713, in main
    return runner(parsed_args, nonblocking_server=nonblocking_server)
  File "/home/data/t0302015/miniconda3/lib/python3.9/site-packages/caper/cli.py", line 255, in runner
    subcmd_run(c, args)
  File "/home/data/t0302015/miniconda3/lib/python3.9/site-packages/caper/cli.py", line 386, in subcmd_run
    thread = caper_runner.run(
  File "/home/data/t0302015/miniconda3/lib/python3.9/site-packages/caper/caper_runner.py", line 462, in run
    self._cromwell.validate(wdl=wdl, inputs=inputs, imports=imports)
  File "/home/data/t0302015/miniconda3/lib/python3.9/site-packages/caper/cromwell.py", line 160, in validate
    raise WomtoolValidationFailed(
caper.cromwell.WomtoolValidationFailed: RC=1
STDERR=Error: Invalid or corrupt jarfile /home/data/t0302015/.caper/womtool_jar/womtool-82.jar

" I retry run 'caper init local' or re-download  womtool-82.jar, the same issue always present "

## **Troubleshooting result**

If you ran `caper run` without Caper server then Caper automatically runs a troubleshooter for failed workflows. Find troubleshooting result in the bottom of Caper's screen log.

If you ran `caper submit` with a running Caper server then first find your workflow ID (1st column) with `caper list` and run `caper debug [WORKFLOW_ID]`.

Paste troubleshooting result.
```
when run 'caper run /home/data/t0302015/bin/atac-seq-pipeline/atac.wdl --dry-run'
the same issue as present
```

**Comment by imk1** [comment]
I am having the same problem, and I am running this on a slurm cluster.

**Comment by imk1** [comment]
@wangxiangxiu I think that I solved the problem.  Here is what I did:

1. Uninstalled caper
2. Deleted my .caper directory
3. Uninstalled jdk
4. Installed openjdk version 11.0.13
5. Reinstalled caper

**Comment by wangxiangxiu** [comment]
@imk1 Thanks for your suggestions~ I solved it by installing Java SE 11. Thx~
