### ISSUE TITLE
configparser.NoSectionError: No section: 'defaults'

### ISSUE THREAD

**Issue by mingjianPeng** [ENCODE-DCC/atac-seq-pipeline#401]
## **Describe the bug**
when use code ‘caper’
result:
configparser.NoSectionError: No section: 'defaults'

## **OS/Platform**
- OS/Platform: Ubuntu
- Conda version: v22.9.0
- Pipeline version: v2.2.1
- Caper version: v2.2.3

## **Caper configuration file**
Paste contents of `~/.caper/default.conf`.
```ini
PASTE CAPER CONF CONTENTS HERE
```

## **Input JSON file**
Paste contents of your input JSON file.
```json
PASTE INPUT JSON CONTENTS HERE
```

## **Troubleshooting result**

when use the code ‘caper’
result：
/home/mingjian/miniconda3/envs/atac/lib/python3.6/site-packages/google/auth/crypt/_cryptography_rsa.py:22: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  import cryptography.exceptions
Traceback (most recent call last):
  File "/home/mingjian/miniconda3/envs/atac/lib/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'defaults'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mingjian/miniconda3/envs/atac/bin/caper", line 13, in <module>
    main()
  File "/home/mingjian/miniconda3/envs/atac/lib/python3.6/site-packages/caper/cli.py", line 690, in main
    parser, _ = get_parser_and_defaults()
  File "/home/mingjian/miniconda3/envs/atac/lib/python3.6/site-packages/caper/caper_args.py", line 958, in get_parser_and_defaults
    parsers=subparsers, conf_file=conf_file, conf_key_map=PARAM_KEY_NAME_CHANGE
  File "/home/mingjian/miniconda3/envs/atac/lib/python3.6/site-packages/caper/arg_tool.py", line 120, in update_parsers_defaults_with_conf
    no_strip_quote=no_strip_quote,
  File "/home/mingjian/miniconda3/envs/atac/lib/python3.6/site-packages/caper/arg_tool.py", line 47, in read_from_conf
    d_ = dict(config.items(conf_section))
  File "/home/mingjian/miniconda3/envs/atac/lib/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'defaults'

```

**Comment by leepc12** [comment]
Please post your Caper config file `~/.caper/default.conf`.
