### ISSUE TITLE
AttributeError: module 'grpc' has no attribute '__version__'

### ISSUE THREAD

**Issue by Rafaelsoler13** [ENCODE-DCC/atac-seq-pipeline#411]
I tried to install caper, but this error is printed in the command tool:

```
$ caper
Traceback (most recent call last):
  File "~/.local/bin/caper", line 3, in <module>
    from caper.cli import main
  File "~/.local/lib/python3.8/site-packages/caper/__init__.py", line 1, in <module>
    from .caper_client import CaperClient, CaperClientSubmit
  File "~/.local/lib/python3.8/site-packages/caper/caper_client.py", line 3, in <module>
    from autouri import AutoURI
  File "~/.local/lib/python3.8/site-packages/autouri/__init__.py", line 3, in <module>
    from .gcsuri import GCSURI
  File "~/.local/lib/python3.8/site-packages/autouri/gcsuri.py", line 23, in <module>
    from google.cloud import storage
  File "~/.local/lib/python3.8/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "~/.local/lib/python3.8/site-packages/google/cloud/storage/batch.py", line 30, in <module>
    from google.cloud.storage._http import Connection
  File "~/.local/lib/python3.8/site-packages/google/cloud/storage/_http.py", line 18, in <module>
    from google.cloud import _http
  File "~/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 26, in <module>
    from google.api_core.client_info import ClientInfo
  File "~/.local/lib/python3.8/site-packages/google/api_core/client_info.py", line 34, in <module>
    _GRPC_VERSION = grpc.__version__
AttributeError: module 'grpc' has no attribute '__version__'

```
I cannot run the init option. What could be happening? Thank you

- OS/Platform: Ubuntu 20.04
- Pipeline version: v2.2.2
- Caper version: v2.2.3

**Comment by Rafaelsoler13** [comment]
I solved the problem installing caper in python v3.10 in conda
