### ISSUE TITLE
ataqc module still fails

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#69]
The ataqc module still will not finish running without an error. It looks like a similar issue to #66 , perhaps related to non-conventional chromosome names.

```
Picked up _JAVA_OPTIONS: -Xms256M -Xmx16000M -XX:ParallelGCThreads=1
Traceback (most recent call last):
  File "/users/nicolerg/anaconda2/envs/encode-atac-seq-pipeline/bin/encode_ataqc.py", line 444, in <module>
    ataqc()
  File "/users/nicolerg/anaconda2/envs/encode-atac-seq-pipeline/bin/encode_ataqc.py", line 231, in ataqc
    read_len)
  File "/users/nicolerg/anaconda2/envs/encode-atac-seq-pipeline/bin/run_ataqc.py", line 438, in make_tss_plot
    processes=processes, stranded=True)
  File "/users/nicolerg/anaconda2/envs/encode-atac-seq-pipeline/lib/python2.7/site-packages/metaseq/_genomic_signal.py", line 122, in array
    chunksize=chunksize, **kwargs)
  File "/users/nicolerg/anaconda2/envs/encode-atac-seq-pipeline/lib/python2.7/site-packages/metaseq/array_helpers.py", line 383, in _array_parallel
    itertools.repeat(kwargs)))
  File "/users/nicolerg/anaconda2/envs/encode-atac-seq-pipeline/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/users/nicolerg/anaconda2/envs/encode-atac-seq-pipeline/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
ValueError: invalid reference `chr1`
```

**OS/Platform and dependencies**
- OS or Platform: Ubuntu 16.04.4 (durga)
- Cromwell/dxWDL version: cromwell 34-unknown-SNAP
- Conda version: conda 4.5.11

[debug_ataqc.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2684786/debug_ataqc.tar.gz)

**Comment by nicolerg** [comment]
Are new versions tested with sample data before being committed? I've been submitting bugs related to non-conventional chromosome names for 6 weeks now and have not been able to get a sample to run to completion.

**Comment by leepc12** [comment]
Chromosome names in two files (`tss_enrich` and `chrsz`) don't match.
Your chrsz file looks like.
```
$ cat rn6_masked.chrom.sizes.txt | head
1       282763074
2       266435125
3       177699992
4       184226339
5       173707219
6       147991367
7       145729302
8       133307652
9       122095297
10      112626471
```

$ cat rn6_masked.chrom.sizes.txt | head
1       282763074
2       266435125
3       177699992
4       184226339
5       173707219
6       147991367
7       145729302
8       133307652
9       122095297
10      112626471
```
Your tss file.
```
$ zcat tss.rn6.bed.gz  | head
chr1    100037072       100037073       ENSRNOG00000048901      0       +
chr1    100047235       100047236       ENSRNOG00000045980      0       +
chr1    100059967       100059968       ENSRNOG00000032857      0       +
chr1    100086520       100086521       ENSRNOG00000032857      0       +
chr1    100131449       100131450       ENSRNOG00000032857      0       +
chr1    100131562       100131563       ENSRNOG00000032857      0       +
chr1    100161872       100161873       ENSRNOG00000033414      0       +
chr1    100164400       100164401       ENSRNOG00000054979      0       +
chr1    100189515       100189516       ENSRNOG00000033805      0       +
chr1    100199057       100199058       ENSRNOG00000032857      0       +
```
