### ISSUE TITLE
Pipeline fails using test data on Google Cloud Platform

### ISSUE THREAD

**Issue by archanaraja** [ENCODE-DCC/atac-seq-pipeline#82]
Hi,
I tried running the pipeline on the test data following instructions on the read me on the google cloud.
Pipeline fails throwing the java runtime exception error. 
 **Failed to evaluate atac.xcor_plots_ (reason 1 of 1): Evaluating flatten(select_all([xcor_plots, xcor.plot_png])) failed: assertion failed: base member type WomMaybeEmptyArrayType(WomAnyType) and womtype WomMaybeEmptyArrayType(WomSingleFileType) are not compatible**

Tried restarted from failed task but no luck. It would be great if you can help me resolve this issue.

**Commands** 
$ PROJECT=[YOUR_PROJECT_NAME]
$ BUCKET=gs://[YOUR_BUCKET_NAME]/ENCSR356KRQ_subsampled
$ INPUT=examples/google/ENCSR356KRQ_subsampled.json
$ PIPELINE_METADATA=metadata.json

` java -jar -Dconfig.file=backends/backend.conf -Dbackend.default=google -Dbackend.providers.google.config.project=${PROJECT} -Dbackend.providers.google.config.root=${BUCKET} cromwell-36.jar run atac.wdl -i ${INPUT} -o workflow_opts/docker.json -m ${PIPELINE_METADATA}`

**Sample error from console**

`[92b7db3aatac.macs2_pr2:0:1]: Status change from Running to Success
[2019-02-05 11:26:59,17] [info] PipelinesApiAsyncBackendJobExecutionActor [92b7db3aatac.macs2_pooled:NA:1]: Status change from Running to Success
[92b7db3aatac.macs2_pr1:1:1]: Status change from Running to Success
[2019-02-05 11:28:07,93] [error] WorkflowManagerActor Workflow 92b7db3a-cc58-4bd0-b023-d7920388bcae failed (during ExecutingWorkflowState): java.lang.RuntimeException: Failed to evaluate 'atac.xcor_plots_' (reason 1 of 1): Evaluating flatten(select_all([xcor_plots, xcor.plot_png])) failed: assertion failed: base member type WomMaybeEmptyArrayType(WomAnyType) and womtype WomMaybeEmptyArrayType(WomSingleFileType) are not compatible
	at cromwell.engine.workflow.lifecycle.execution.keys.ExpressionKey.processRunnable(ExpressionKey.scala:29)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.$anonfun$startRunnableNodes$7(WorkflowExecutionActor.scala:510)
	at cats.instances.ListInstances$$anon$1.$anonfun$traverse$2(list.scala:73)
	at cats.instances.ListInstances$$anon$1.loop$2(list.scala:63)
	at cats.instances.ListInstances$$anon$1.$anonfun$foldRight$2(list.scala:65)`

Thanks,
Archana

**Comment by leepc12** [comment]
Please try with cromwell-34. 36 has a known bug and will be fixed in 37.

**Comment by archanaraja** [comment]
Thank you. Will try 34.

Archana

**Comment by archanaraja** [comment]
Fixed by rerunning the entire pipeline using cromwell-34.

Thanks,
Archana
